### ISSUE TITLE
System wavpack not working

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#1041]
```
Thread 3 "DDNet" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffebfff700 (LWP 29331)]
0x00007ffff6a83767 in ?? () from /usr/lib/libwavpack.so.1
(gdb) bt
#0  0x00007ffff6a83767 in ?? () from /usr/lib/libwavpack.so.1
#1  0x00007ffff6a82b71 in WavpackOpenFileInputEx64 () from /usr/lib/libwavpack.so.1
#2  0x0000555555621fc3 in CSound::DecodeWV (SampleID=0, pData=0x7fffa800b050, DataSize=25152)
    at /media/ddnet/src/engine/client/sound.cpp:524
#3  0x000055555562257d in CSound::LoadWV (this=0x555555bd6030, pFilename=0x55555577ea00 "audio/wp_gun_fire-01.wv")
    at /media/ddnet/src/engine/client/sound.cpp:665
#4  0x00005555556ae17a in CSoundLoading::Run (this=0x555555e2dd60)
    at /media/ddnet/src/game/client/components/sounds.cpp:28
#5  0x0000555555741a9f in CJobPool::WorkerThread (pUser=0x555555ba81d0) at /media/ddnet/src/engine/shared/jobs.cpp:77
#6  0x00007ffff7bc108c in start_thread () from /usr/lib/libpthread.so.0
#7  0x00007ffff501be7f in clone () from /usr/lib/libc.so.6
```
Wavpack 5.1.0-1 on Arch Linux x86-64.

**Comment by yangfl** [comment]
Also on Wavpack 5.1.0-2 on Debian testing
