### ISSUE TITLE
Segfault when connecting to CSqlServer (on RUS)

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#1131]
```
(gdb) bt
#0  0x00007fe2bc001140 in ?? ()
#1  0x000056106a94b91b in CSqlServer::Connect (this=this@entry=0x56106b4a7240)
    at /home/teeworlds/src/master/src/engine/server/sql_server.cpp:118
#2  0x000056106a94c656 in CSqlServer::CreateTables (this=0x56106b4a7240)
    at /home/teeworlds/src/master/src/engine/server/sql_server.cpp:165
#3  0x00007fe2cf3b3494 in start_thread (arg=0x7fe2c997c700) at pthread_create.c:333
#4  0x00007fe2cd95aacf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
```

**Comment by def-** [comment]
Doesn't seem to happen anymore?

**Comment by def-** [comment]
New one on RUS, not sure if related and why they only happen on RUS:

```
Program terminated with signal SIGSEGV, Segmentation fault.
t#0  std::__atomic_base<int>::load (__m=std::memory_order_seq_cst, this=0x18)
    at /usr/include/c++/6/bits/atomic_base.h:396
396		return __atomic_load_n(&_M_i, __m);
[Current thread is 1 (Thread 0x7f1336c13780 (LWP 652))]

(gdb) bt
#0  std::__atomic_base<int>::load (__m=std::memory_order_seq_cst, this=0x18)
    at /usr/include/c++/6/bits/atomic_base.h:396
#1  IJob::Status (this=0x0) at /home/teeworlds/src/master/src/engine/shared/jobs.cpp:27
#2  0x000055d7ca251e26 in CServer::Run (this=0x7f132ea78010)
    at /home/teeworlds/src/master/src/engine/server/server.cpp:1883
#3  0x000055d7ca246b2a in main (argc=3, argv=0x7ffd3186e178)
    at /home/teeworlds/src/master/src/engine/server/server.cpp:2926
```

**Comment by def-** [comment]
Other threads:

```
(gdb) info threads
  Id   Target Id         Frame 
* 1    Thread 0x7f1336c13780 (LWP 652) std::__atomic_base<int>::load (__m=std::memory_order_seq_cst, this=0x18)
    at /usr/include/c++/6/bits/atomic_base.h:396
  2    Thread 0x7f132ea77700 (LWP 780) 0x00007f1336802536 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, 
    expected=0, futex_word=0x55d7cc3891f0) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
  3    Thread 0x7f132c060700 (LWP 817) 0x00007f1336802536 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, 
    expected=0, futex_word=0x55d7cc3fc9d0) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
  4    Thread 0x7f132e276700 (LWP 781) 0x00007f1336802536 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, 
    expected=0, futex_word=0x55d7cc39bfe8) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
  5    Thread 0x7f132af6f700 (LWP 4275) 0x00007f1336802536 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, 
    expected=0, futex_word=0x55d7cc3fbd60) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
(gdb) thread 2
[Switching to thread 2 (Thread 0x7f132ea77700 (LWP 780))]
#0  0x00007f1336802536 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, 
    futex_word=0x55d7cc3891f0) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
205	../sysdeps/unix/sysv/linux/futex-internal.h: No such file or directory.
(gdb) bt
#0  0x00007f1336802536 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, 
    futex_word=0x55d7cc3891f0) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x55d7cc3891f0, abstime=0x0) at sem_waitcommon.c:111
#2  0x00007f13368025e4 in __new_sem_wait_slow (sem=0x55d7cc3891f0, abstime=0x0) at sem_waitcommon.c:181
#3  0x00007f1336802679 in __new_sem_wait (sem=sem@entry=0x55d7cc3891f0) at sem_wait.c:29
#4  0x000055d7ca2dbf72 in sphore_wait (sem=0x55d7cc3891f0) at /home/teeworlds/src/master/src/base/system.c:850
#5  aio_thread (user=user@entry=0x55d7cc3891e0) at /home/teeworlds/src/master/src/base/system.c:444
#6  0x000055d7ca2dbd27 in thread_run (user=<optimized out>) at /home/teeworlds/src/master/src/base/system.c:685
#7  0x00007f13367fa494 in start_thread (arg=0x7f132ea77700) at pthread_create.c:333
#8  0x00007f1334c27acf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
(gdb) thread 3
[Switching to thread 3 (Thread 0x7f132c060700 (LWP 817))]
#0  0x00007f1336802536 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, 
    futex_word=0x55d7cc3fc9d0) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
205	in ../sysdeps/unix/sysv/linux/futex-internal.h
(gdb) bt
#0  0x00007f1336802536 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, 
    futex_word=0x55d7cc3fc9d0) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x55d7cc3fc9d0, abstime=0x0) at sem_waitcommon.c:111
#2  0x00007f13368025e4 in __new_sem_wait_slow (sem=0x55d7cc3fc9d0, abstime=0x0) at sem_waitcommon.c:181
#3  0x00007f1336802679 in __new_sem_wait (sem=sem@entry=0x55d7cc3fc9d0) at sem_wait.c:29
#4  0x000055d7ca2dbf72 in sphore_wait (sem=0x55d7cc3fc9d0) at /home/teeworlds/src/master/src/base/system.c:850
#5  aio_thread (user=user@entry=0x55d7cc3fc9c0) at /home/teeworlds/src/master/src/base/system.c:444
#6  0x000055d7ca2dbd27 in thread_run (user=<optimized out>) at /home/teeworlds/src/master/src/base/system.c:685
#7  0x00007f13367fa494 in start_thread (arg=0x7f132c060700) at pthread_create.c:333
#8  0x00007f1334c27acf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
(gdb) thread 4
[Switching to thread 4 (Thread 0x7f132e276700 (LWP 781))]
#0  0x00007f1336802536 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, 
    futex_word=0x55d7cc39bfe8) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
205	in ../sysdeps/unix/sysv/linux/futex-internal.h
(gdb) bt
#0  0x00007f1336802536 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, 
    futex_word=0x55d7cc39bfe8) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x55d7cc39bfe8, abstime=0x0) at sem_waitcommon.c:111
#2  0x00007f13368025e4 in __new_sem_wait_slow (sem=0x55d7cc39bfe8, abstime=0x0) at sem_waitcommon.c:181
#3  0x00007f1336802679 in __new_sem_wait (sem=sem@entry=0x55d7cc39bfe8) at sem_wait.c:29
#4  0x000055d7ca2dcecd in sphore_wait (sem=sem@entry=0x55d7cc39bfe8)
    at /home/teeworlds/src/master/src/base/system.c:850
#5  0x000055d7ca2ca587 in CJobPool::WorkerThread (pUser=pUser@entry=0x55d7cc39bed0)
    at /home/teeworlds/src/master/src/engine/shared/jobs.cpp:61
#6  0x000055d7ca2dbd27 in thread_run (user=<optimized out>) at /home/teeworlds/src/master/src/base/system.c:685
#7  0x00007f13367fa494 in start_thread (arg=0x7f132e276700) at pthread_create.c:333
#8  0x00007f1334c27acf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
(gdb) thread 5
[Switching to thread 5 (Thread 0x7f132af6f700 (LWP 4275))]
#0  0x00007f1336802536 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, 
    futex_word=0x55d7cc3fbd60) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
205	in ../sysdeps/unix/sysv/linux/futex-internal.h
(gdb) bt
#0  0x00007f1336802536 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, 
    futex_word=0x55d7cc3fbd60) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x55d7cc3fbd60, abstime=0x0) at sem_waitcommon.c:111
#2  0x00007f13368025e4 in __new_sem_wait_slow (sem=0x55d7cc3fbd60, abstime=0x0) at sem_waitcommon.c:181
#3  0x00007f1336802679 in __new_sem_wait (sem=sem@entry=0x55d7cc3fbd60) at sem_wait.c:29
#4  0x000055d7ca2dbf72 in sphore_wait (sem=0x55d7cc3fbd60) at /home/teeworlds/src/master/src/base/system.c:850
#5  aio_thread (user=user@entry=0x55d7cc3fbd50) at /home/teeworlds/src/master/src/base/system.c:444
#6  0x000055d7ca2dbd27 in thread_run (user=<optimized out>) at /home/teeworlds/src/master/src/base/system.c:685
#7  0x00007f13367fa494 in start_thread (arg=0x7f132af6f700) at pthread_create.c:333
#8  0x00007f1334c27acf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
```

**Comment by def-** [comment]
Still seems to happen, also on GER2:
```
(gdb) bt
#0  0x00007fe1b4001140 in ?? ()
#1  0x0000562ad25e8a4b in CSqlServer::Connect (this=this@entry=0x562ad3339bd0)
    at /home/teeworlds/src/master/src/engine/server/sql_server.cpp:118
#2  0x0000562ad25e9786 in CSqlServer::CreateTables (this=0x562ad3339bd0)
    at /home/teeworlds/src/master/src/engine/server/sql_server.cpp:165
#3  0x0000562ad266f197 in thread_run (user=<optimized out>) at /home/teeworlds/src/master/src/base/system.c:685
#4  0x00007fe1cbfbd494 in start_thread (arg=0x7fe1c261f700) at pthread_create.c:333
#5  0x00007fe1ca3eaacf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
```

**Comment by def-** [comment]
Here's the other thread on GER2 for completeness sake:

```
[Current thread is 1 (Thread 0x7fe1c261f700 (LWP 1682))]
(gdb) bt
#0  0x00007fe1b4001140 in ?? ()
#1  0x0000562ad25e8a4b in CSqlServer::Connect (this=this@entry=0x562ad3339bd0)
    at /home/teeworlds/src/master/src/engine/server/sql_server.cpp:118
#2  0x0000562ad25e9786 in CSqlServer::CreateTables (this=0x562ad3339bd0)
    at /home/teeworlds/src/master/src/engine/server/sql_server.cpp:165
#3  0x0000562ad266f197 in thread_run (user=<optimized out>) at /home/teeworlds/src/master/src/base/system.c:685
#4  0x00007fe1cbfbd494 in start_thread (arg=0x7fe1c261f700) at pthread_create.c:333
#5  0x00007fe1ca3eaacf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
(gdb) thread 5
[Switching to thread 5 (Thread 0x7fe1c1e1e700 (LWP 1683))]
#0  0x00007fe1ca3e167d in poll () at ../sysdeps/unix/syscall-template.S:84
84	../sysdeps/unix/syscall-template.S: No such file or directory.
(gdb) bt
#0  0x00007fe1ca3e167d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007fe1cacb6791 in ?? () from /usr/lib/x86_64-linux-gnu/libmariadbclient.so.18
#2  0x00007fe1cacb6da0 in ?? () from /usr/lib/x86_64-linux-gnu/libmariadbclient.so.18
#3  0x00007fe1cac89bbe in mysql_real_connect () from /usr/lib/x86_64-linux-gnu/libmariadbclient.so.18
#4  0x00007fe1caa28813 in sql::mysql::NativeAPI::MySQL_NativeConnectionWrapper::connect(sql::SQLString const&, sql::SQLString const&, sql::SQLString const&, sql::SQLString const&, unsigned int, sql::SQLString const&, unsigned long) ()
   from /usr/lib/x86_64-linux-gnu/libmysqlcppconn.so.7
#5  0x00007fe1ca9dde5f in sql::mysql::MySQL_Connection::init(std::map<sql::SQLString, sql::Variant, std::less<sql::SQLString>, std::allocator<std::pair<sql::SQLString const, sql::Variant> > >&) ()
   from /usr/lib/x86_64-linux-gnu/libmysqlcppconn.so.7
#6  0x00007fe1ca9e1584 in sql::mysql::MySQL_Connection::MySQL_Connection(sql::Driver*, sql::mysql::NativeAPI::NativeConnectionWrapper&, std::map<sql::SQLString, sql::Variant, std::less<sql::SQLString>, std::allocator<std::pair<sql::SQLString const, sql::Variant> > >&) () from /usr/lib/x86_64-linux-gnu/libmysqlcppconn.so.7
#7  0x00007fe1ca9e67a0 in sql::mysql::MySQL_Driver::connect(std::map<sql::SQLString, sql::Variant, std::less<sql::SQLString>, std::allocator<std::pair<sql::SQLString const, sql::Variant> > >&) ()
   from /usr/lib/x86_64-linux-gnu/libmysqlcppconn.so.7
#8  0x0000562ad25e8a4b in CSqlServer::Connect (this=this@entry=0x562ad333b0c0)
    at /home/teeworlds/src/master/src/engine/server/sql_server.cpp:118
#9  0x0000562ad25e9786 in CSqlServer::CreateTables (this=0x562ad333b0c0)
    at /home/teeworlds/src/master/src/engine/server/sql_server.cpp:165
#10 0x0000562ad266f197 in thread_run (user=<optimized out>) at /home/teeworlds/src/master/src/base/system.c:685
#11 0x00007fe1cbfbd494 in start_thread (arg=0x7fe1c1e1e700) at pthread_create.c:333
#12 0x00007fe1ca3eaacf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
```
