### ISSUE TITLE
Crash in CRingBufferBase::MergeBack

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#1307]
```
Core was generated by `./DDRace64-Server_sql -f servers/8330.cfg'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  CRingBufferBase::MergeBack (this=0x7f26f6134fb0, pItem=0x7f26f6135050)
    at /home/teeworlds/src/master/src/engine/shared/ringbuffer.cpp:33
33			pItem->m_pNext->m_pPrev = pItem->m_pPrev;
[Current thread is 1 (Thread 0x7f26fdb4bd80 (LWP 15637))]
(gdb) bt
#0  CRingBufferBase::MergeBack (this=0x7f26f6134fb0, pItem=0x7f26f6135050)
    at /home/teeworlds/src/master/src/engine/shared/ringbuffer.cpp:33
#1  0x000055cd0c738db8 in CRingBufferBase::PopFirst (this=this@entry=0x7f26f6134fb0)
    at /home/teeworlds/src/master/src/engine/shared/ringbuffer.cpp:150
#2  0x000055cd0c734ef6 in TStaticRingBuffer<CNetChunkResend, 32768, 0>::PopFirst (this=0x7f26f6134fb0)
    at /home/teeworlds/src/master/src/engine/shared/ringbuffer.h:59
#3  CNetConnection::AckChunks (this=this@entry=0x7f26f6134f90, Ack=333)
    at /home/teeworlds/src/master/src/engine/shared/network_conn.cpp:77
#4  0x000055cd0c735852 in CNetConnection::Feed (this=this@entry=0x7f26f6134f90, pPacket=pPacket@entry=0x7f26f62db878, 
    pAddr=pAddr@entry=0x7ffeae86d380, SecurityToken=SecurityToken@entry=0)
    at /home/teeworlds/src/master/src/engine/shared/network_conn.cpp:393
#5  0x000055cd0c737f95 in CNetServer::Recv (this=0x7f26f60beb48, pChunk=0x7ffeae86d470)
    at /home/teeworlds/src/master/src/engine/shared/network_server.cpp:642
#6  0x000055cd0c6b4d28 in CServer::PumpNetwork (this=0x7f26f59b5010)
    at /home/teeworlds/src/master/src/engine/server/server.cpp:1625
#7  0x000055cd0c6b5f3a in CServer::Run (this=0x7f26f59b5010)
    at /home/teeworlds/src/master/src/engine/server/server.cpp:1954
#8  0x000055cd0c6aad7a in main (argc=3, argv=0x7ffeae86d928)
    at /home/teeworlds/src/master/src/engine/server/server.cpp:2926
```

**Comment by def-** [comment]
```
(gdb) print pItem
$1 = (CRingBufferBase::CItem *) 0x7f26f6135050
(gdb) print pItem->m_pNext
$2 = (CRingBufferBase::CItem *) 0x7372616579203320
(gdb) print pItem->m_pPrev
$3 = (CRingBufferBase::CItem *) 0x7f26f6134fd8
(gdb) print pItem->m_pNext->m_pPrev
Cannot access memory at address 0x7372616579203320
```
I have the executable and core file if someone has good ideas for where to fish around.

**Comment by def-** [comment]
Unreproducable.

**Comment by def-** [comment]
Similar one:

```
Core was generated by `./DDRace64-Server_sql -f servers/8319.cfg'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  CRingBufferBase::Next (this=this@entry=0x7fd9030146b0, pCurrent=pCurrent@entry=0x7fd903014780)
    at /home/teeworlds/src/master/src/engine/shared/ringbuffer.cpp:178
178			if(!pItem->m_Free)
[Current thread is 1 (Thread 0x7fd905a70740 (LWP 24777))]
(gdb) bt
#0  CRingBufferBase::Next (this=this@entry=0x7fd9030146b0, pCurrent=pCurrent@entry=0x7fd903014780)
    at /home/teeworlds/src/master/src/engine/shared/ringbuffer.cpp:178
#1  0x000055a2c759d986 in TStaticRingBuffer<CNetChunkResend, 32768, 0>::Next (pCurrent=0x7fd903014780, 
    this=0x7fd9030146b0) at /home/teeworlds/src/master/src/engine/shared/ringbuffer.h:62
#2  CNetConnection::Resend (this=this@entry=0x7fd903014690)
    at /home/teeworlds/src/master/src/engine/shared/network_conn.cpp:179
#3  0x000055a2c759de08 in CNetConnection::Feed (this=this@entry=0x7fd903014690, pPacket=pPacket@entry=0x7fd903228c80, 
    pAddr=pAddr@entry=0x7ffdd22a4d50, SecurityToken=SecurityToken@entry=0)
    at /home/teeworlds/src/master/src/engine/shared/network_conn.cpp:273
#4  0x000055a2c75a060d in CNetServer::Recv (this=0x7fd902fd9b48, pChunk=0x7ffdd22a4e40)
    at /home/teeworlds/src/master/src/engine/shared/network_server.cpp:655
#5  0x000055a2c751cf58 in CServer::PumpNetwork (this=0x7fd9028d0010)
    at /home/teeworlds/src/master/src/engine/server/server.cpp:1676
#6  0x000055a2c751e473 in CServer::Run (this=0x7fd9028d0010)
    at /home/teeworlds/src/master/src/engine/server/server.cpp:2017
#7  0x000055a2c7512d78 in main (argc=3, argv=0x7ffdd22a52f8)
    at /home/teeworlds/src/master/src/engine/server/server.cpp:2974
(gdb) info threads
  Id   Target Id         Frame 
* 1    Thread 0x7fd905a70740 (LWP 24777) CRingBufferBase::Next (this=this@entry=0x7fd9030146b0, 
    pCurrent=pCurrent@entry=0x7fd903014780) at /home/teeworlds/src/master/src/engine/shared/ringbuffer.cpp:178
  2    Thread 0x7fd9028cf700 (LWP 24781) 0x00007fd904d9b556 in futex_abstimed_wait_cancelable (private=0, 
    abstime=0x0, expected=0, futex_word=0x55a2c7e630f0) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
  3    Thread 0x7fd9018cd700 (LWP 24786) 0x00007fd904d9b556 in futex_abstimed_wait_cancelable (private=0, 
    abstime=0x0, expected=0, futex_word=0x55a2c7e642d8) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
  4    Thread 0x7fd9020ce700 (LWP 24785) 0x00007fd904d9b556 in futex_abstimed_wait_cancelable (private=0, 
    abstime=0x0, expected=0, futex_word=0x55a2c7e642d8) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
  5    Thread 0x7fd8fb7fe700 (LWP 16152) 0x00007fd904d9b556 in futex_abstimed_wait_cancelable (private=0, 
    abstime=0x0, expected=0, futex_word=0x55a2c7e63080) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
  6    Thread 0x7fd8fbfff700 (LWP 24853) 0x00007fd904d9b556 in futex_abstimed_wait_cancelable (private=0, 
    abstime=0x0, expected=0, futex_word=0x55a2c7eaa850) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
(gdb) 
```

Will put in crash4 on GER for now.

**Comment by def-** [comment]
In the logs I see that a map change happened 2 seconds prior, then player reconnected and immediately used /timeout:

```
[2019-03-26 17:24:54][datafile]: loading data index=0 size=42 uncompressed=34
[2019-03-26 17:24:54][console]: executing 'maps/GG.map.cfg'
[2019-03-26 17:24:54][teehistorian]: recording to 'teehistorian/395e5f1d-6622-46d6-8123-519435fda7b2.teehistorian'
[2019-03-26 17:24:54][sql]: Getting best time on server done
[2019-03-26 17:24:54][server]: player is ready. ClientID=0 addr=91.8.103.171:33586 secure=yes
[2019-03-26 17:24:54][server]: player is ready. ClientID=1 addr=87.168.212.183:11260 secure=yes
[2019-03-26 17:24:54][server]: 'Genex' -> 'Genex'
[2019-03-26 17:24:55][server]: 'MoonCake' -> 'MoonCake'
[2019-03-26 17:24:55][server]: player has entered the game. ClientID=1 addr=87.168.212.183:11260
[2019-03-26 17:24:55][sql]: Getting best time done
[2019-03-26 17:24:55][sql]: checking birthday done
[2019-03-26 17:24:55][server]: player has entered the game. ClientID=0 addr=91.8.103.171:33586
[2019-03-26 17:24:55][sql]: Getting best time done
[2019-03-26 17:24:55][sql]: checking birthday done
[2019-03-26 17:24:55][ddnet]: 0 using Custom Client 11090
[2019-03-26 17:24:56][chat-command]: 0 used /pause
[2019-03-26 17:24:56][chat-command]: 1 used /mapinfo
[2019-03-26 17:24:56][ddnet]: 1 using Custom Client 11090
[2019-03-26 17:24:57][chat-command]: 0 used /timeout XXX
```

**Comment by def-** [comment]
```
Core was generated by `./DDRace64-Server_sql -f servers/8305.cfg'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  CRingBufferBase::Allocate (this=this@entry=0x7fb20976e0a8, Size=Size@entry=44)
    at /home/teeworlds/src/master/src/engine/shared/ringbuffer.cpp:109
109				pNewItem->m_pNext->m_pPrev = pNewItem;
[Current thread is 1 (Thread 0x7fb20c12a740 (LWP 13629))]
(gdb) bt
#0  CRingBufferBase::Allocate (this=this@entry=0x7fb20976e0a8, Size=Size@entry=44)
    at /home/teeworlds/src/master/src/engine/shared/ringbuffer.cpp:109
#1  0x00005615f8c73df4 in TStaticRingBuffer<CNetChunkResend, 32768, 0>::Allocate (Size=44, this=0x7fb20976e0a8)
    at /home/teeworlds/src/master/src/engine/shared/ringbuffer.h:58
#2  CNetConnection::QueueChunkEx (this=0x7fb20976e088, Flags=1, DataSize=4, pData=0x7ffc1820a250, Sequence=24)
    at /home/teeworlds/src/master/src/engine/shared/network_conn.cpp:136
#3  0x00005615f8c73e85 in CNetConnection::QueueChunk (this=<optimized out>, Flags=<optimized out>, 
    DataSize=<optimized out>, pData=<optimized out>)
    at /home/teeworlds/src/master/src/engine/shared/network_conn.cpp:161
#4  0x00005615f8c76e25 in CNetServer::Send (this=0x7fb209692d48, pChunk=0x7ffc1820a1d0)
    at /home/teeworlds/src/master/src/engine/shared/network_server.cpp:697
#5  0x00005615f8bed9bf in CServer::SendMsgEx (this=0x7fb208f89010, pMsg=0x7ffc1820a250, Flags=<optimized out>, 
    ClientID=20, System=<optimized out>) at /home/teeworlds/src/master/src/engine/server/server.cpp:668
#6  0x00005615f8c22758 in IServer::SendPackMsgOne<CNetMsg_Sv_Chat> (this=0x7fb208f89010, pMsg=0x7ffc1820aac0, 
    Flags=5, ClientID=20) at /home/teeworlds/src/master/src/engine/server.h:106
#7  0x00005615f8c1afdc in IServer::SendPackMsgTranslate (ClientID=20, Flags=5, pMsg=0x7ffc1820aac0, 
    this=0x7fb208f89010) at /home/teeworlds/src/master/src/engine/server.h:90
#8  IServer::SendPackMsg<CNetMsg_Sv_Chat> (ClientID=20, Flags=5, pMsg=0x7ffc1820aab0, this=0x7fb208f89010)
    at /home/teeworlds/src/master/src/engine/server.h:64
#9  CGameContext::SendChatTarget (this=<optimized out>, To=20, pText=pText@entry=0x7fb20c109648 "")
    at /home/teeworlds/src/master/src/game/server/gamecontext.cpp:296
#10 0x00005615f8c044c6 in CCharacter::SendZoneMsgs (this=this@entry=0x5615f8ee4da0 <ms_PoolDataCCharacter+37920>)
    at /home/teeworlds/src/master/src/game/server/entities/character.cpp:2115
#11 0x00005615f8c06c0b in CCharacter::Spawn (this=this@entry=0x5615f8ee4da0 <ms_PoolDataCCharacter+37920>, 
    pPlayer=pPlayer@entry=0x5615f8efdf40 <ms_PoolDataCPlayer+19360>, Pos=...)
    at /home/teeworlds/src/master/src/game/server/entities/character.cpp:77
#12 0x00005615f8c28965 in CPlayer::TryRespawn (this=this@entry=0x5615f8efdf40 <ms_PoolDataCPlayer+19360>)
    at /home/teeworlds/src/master/src/game/server/player.cpp:580
#13 0x00005615f8c294a5 in CPlayer::Tick (this=0x5615f8efdf40 <ms_PoolDataCPlayer+19360>)
    at /home/teeworlds/src/master/src/game/server/player.cpp:217
#14 0x00005615f8c1ec82 in CGameContext::OnTick (this=0x7fb20c0fa010)
    at /home/teeworlds/src/master/src/game/server/gamecontext.cpp:655
#15 0x00005615f8bf3433 in CServer::Run (this=0x7fb208f89010)
    at /home/teeworlds/src/master/src/engine/server/server.cpp:2033
#16 0x00005615f8be8018 in main (argc=3, argv=0x7ffc1820c238)
    at /home/teeworlds/src/master/src/engine/server/server.cpp:3026
(gdb) 
```

**Comment by def-** [comment]
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  CRingBufferBase::Allocate (this=this@entry=0x7f9224480ef8, Size=Size@entry=43)
    at /home/teeworlds/src/master/src/engine/shared/ringbuffer.cpp:109
109				pNewItem->m_pNext->m_pPrev = pNewItem;
[Current thread is 1 (Thread 0x7f9224a54980 (LWP 15141))]
(gdb) bt
#0  CRingBufferBase::Allocate (this=this@entry=0x7f9224480ef8, Size=Size@entry=43)
    at /home/teeworlds/src/master/src/engine/shared/ringbuffer.cpp:109
#1  0x000055cd84abafa4 in TStaticRingBuffer<CNetChunkResend, 32768, 0>::Allocate (Size=43, this=0x7f9224480ef8)
    at /home/teeworlds/src/master/src/engine/shared/ringbuffer.h:58
#2  CNetConnection::QueueChunkEx (this=0x7f9224480ed8, Flags=1, DataSize=3, pData=0x7ffeae2547a0, Sequence=642)
    at /home/teeworlds/src/master/src/engine/shared/network_conn.cpp:136
#3  0x000055cd84abb036 in CNetConnection::QueueChunk (this=<optimized out>, Flags=<optimized out>, 
    DataSize=<optimized out>, pData=<optimized out>)
    at /home/teeworlds/src/master/src/engine/shared/network_conn.cpp:161
#4  0x000055cd84abdf4a in CNetServer::Send (this=this@entry=0x7f9224394d48, pChunk=pChunk@entry=0x7ffeae2546a0)
    at /home/teeworlds/src/master/src/engine/shared/network_server.cpp:700
#5  0x000055cd84a37710 in CServer::SendMsgEx (this=0x7f9223c8b010, pMsg=0x7ffeae2547a0, Flags=<optimized out>, 
    ClientID=22, System=<optimized out>) at /home/teeworlds/src/master/src/engine/server/server.cpp:667
#6  0x000055cd84a68ba4 in IServer::SendPackMsgOne<CNetMsg_Sv_Emoticon> (ClientID=22, Flags=1, pMsg=0x7ffeae254768, 
    this=0x7f9223c8b010) at /home/teeworlds/src/master/src/engine/shared/packer.h:27
#7  IServer::SendPackMsgTranslate (ClientID=22, Flags=1, pMsg=0x7ffeae254768, this=0x7f9223c8b010)
    at /home/teeworlds/src/master/src/engine/server.h:77
#8  IServer::SendPackMsg<CNetMsg_Sv_Emoticon> (ClientID=-1, Flags=1, pMsg=0x7ffeae254760, this=0x7f9223c8b010)
    at /home/teeworlds/src/master/src/engine/server.h:60
#9  CGameContext::SendEmoticon (Emoticon=<optimized out>, ClientID=<optimized out>, this=0x7f9222458010)
    at /home/teeworlds/src/master/src/game/server/gamecontext.cpp:384
#10 CGameContext::OnMessage (this=0x7f9222458010, MsgID=<optimized out>, pUnpacker=<optimized out>, 
    ClientID=<optimized out>) at /home/teeworlds/src/master/src/game/server/gamecontext.cpp:1850
#11 0x000055cd84a3b1c4 in CServer::ProcessClientPacket (this=this@entry=0x7f9223c8b010, 
    pPacket=pPacket@entry=0x7ffeae256ce0) at /home/teeworlds/src/master/src/engine/server/server.h:107
#12 0x000055cd84a3c096 in CServer::PumpNetwork (this=this@entry=0x7f9223c8b010)
    at /home/teeworlds/src/master/src/engine/server/server.cpp:1764
#13 0x000055cd84a3d4e9 in CServer::Run (this=this@entry=0x7f9223c8b010)
    at /home/teeworlds/src/master/src/engine/server/server.cpp:2070
#14 0x000055cd84a31f06 in main (argc=3, argv=0x7ffeae257198)
    at /home/teeworlds/src/master/src/engine/server/server.cpp:3039
```

**Comment by def-** [comment]
My guess would be that we send packets from two threads at once.

**Comment by heinrich5991** [comment]
Probably https://github.com/ddnet/ddnet/issues/946.

The SQL code does (among other things) also send packets (chat messages) in threads.

**Comment by def-** [comment]
Will be fixed by https://github.com/ddnet/ddnet/pull/2247

**Comment by heinrich5991** [comment]
#2247 was merged.
