### ISSUE TITLE
[Windows/Map Editor] Segfault ?

### ISSUE THREAD

**Issue by xse** [ddnet/ddnet#1362]
Hi, 
I'm not able to login on the forum since my account isn't yet accepted, i'll just describe the issue : 
I've only tested it on windows so far.

[ version : 0.6.4, 11.4.4 ]

1. Launch ddnet, open map editor, default stuff without any map loaded.
2. Left click on "#1 Game".
3. From that point on you keep shift pressed, you drag your mouse around with right click, then you drag your mouse around with left click.

This gets me an instant segfault.

If for any reasons you're not able to reproduce I'll gladly provide more information.
Have a good day !

**Comment by Learath2** [comment]
Finally figured it out. Will fix soon(tm)[2-3 days maybe].

**Comment by Ryozuki** [comment]
```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x00000000004e0615 in CLayerTiles::FillSelection (this=0xe21a6c0, Empty=true, pBrush=0xbaadf00dbaadf00d, Rect=...) at C:\Users\----\Desktop\ddnet\src\game\editor\layer_tiles.cpp:382
382		if(pBrush->m_Type != LAYERTYPE_TILES)
```

```
backtrace:
#0  0x00000000004e0615 in CLayerTiles::FillSelection (this=0xe21a6c0, Empty=true, pBrush=0xbaadf00dbaadf00d, Rect=...) at C:\Users\----\Desktop\ddnet\src\game\editor\layer_tiles.cpp:382
#1  0x00000000004c547c in CEditor::DoMapEditor (this=0x16bcd80, View=...) at C:\Users\Edgar\Desktop\ddnet\src\game\editor\editor.cpp:2627
#2  0x00000000004d4f6c in CEditor::Render (this=0x16bcd80) at C:\Users\----\Desktop\ddnet\src\game\editor\editor.cpp:5426
#3  0x00000000004d7a5a in CEditor::UpdateAndRender (this=0x16bcd80) at C:\Users\----\Desktop\ddnet\src\game\editor\editor.cpp:6026
Traceback (most recent call last):
  File "C:/Program Files/JetBrains/CLion 2018.2/bin/gdb/renderers\default\printers.py", line 154, in lookup
    dereferenced.fetch_lazy()
gdb.error: value of type `CClient' requires 4362280 bytes, which is more than max-value-size
#4  0x0000000000416e58 in CClient::Run (this=0x3a1b040) at C:\Users\----\Desktop\ddnet\src\engine\client\client.cpp:2923
#5  0x000000000041af4d in main (argc=1, argv=0x1744e90) at C:\Users\----\Desktop\ddnet\src\engine\client\client.cpp:3706
#6  0x00000000004013a5 in __tmainCRTStartup () at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:339
#7  0x000000000040150b in mainCRTStartup () at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:223```
