### ISSUE TITLE
Crash while stopping server

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#1461]
```
Core was generated by `./DDRace64-Server_sql -f servers/8309.cfg'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  malloc_consolidate (av=av@entry=0x7f51dd922b00 <main_arena>) at malloc.c:4205
4205	malloc.c: No such file or directory.
[Current thread is 1 (Thread 0x7f51df98c740 (LWP 25144))]
(gdb) bt
#0  malloc_consolidate (av=av@entry=0x7f51dd922b00 <main_arena>) at malloc.c:4205
#1  0x00007f51dd600ed8 in _int_free (av=0x7f51dd922b00 <main_arena>, p=0x5641eba884d0, have_lock=0) at malloc.c:4113
#2  0x00005641ea9ad469 in CHeap::Clear (this=<optimized out>)
    at /home/teeworlds/src/master/src/engine/shared/memheap.cpp:71
#3  CHeap::~CHeap (this=<optimized out>, __in_chrg=<optimized out>)
    at /home/teeworlds/src/master/src/engine/shared/memheap.cpp:53
#4  0x00005641ea9934a7 in CConsole::CExecutionQueue::~CExecutionQueue (this=0x5641eba428c8, __in_chrg=<optimized out>)
    at /home/teeworlds/src/master/src/engine/shared/console.h:151
#5  CConsole::~CConsole (this=0x5641eba427f0, __in_chrg=<optimized out>)
    at /home/teeworlds/src/master/src/engine/shared/console.cpp:857
#6  0x00005641ea9934fd in CConsole::~CConsole (this=0x5641eba427f0, __in_chrg=<optimized out>)
    at /home/teeworlds/src/master/src/engine/shared/console.cpp:868
#7  0x00005641ea9ab921 in CKernel::~CKernel (this=0x5641eba3f780, __in_chrg=<optimized out>)
    at /home/teeworlds/src/master/src/engine/shared/kernel.cpp:55
#8  CKernel::~CKernel (this=0x5641eba3f780, __in_chrg=<optimized out>)
    at /home/teeworlds/src/master/src/engine/shared/kernel.cpp:59
#9  0x00005641ea927c61 in main (argc=3, argv=0x7ffdc3e43598)
    at /home/teeworlds/src/master/src/engine/server/server.cpp:2990
```
Coredump on RUS. Tell me if anyone has ideas where to look.

**Comment by edg-l** [comment]
Ia this still a problem?

**Comment by def-** [comment]
Maybe, maybe not. I'll reopen if I see it again.
