### ISSUE TITLE
Client crash on invalid position

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#1728]
If the server sends the client a position that is out of the map it crashes.
```
#0  0x00005555557d9f6f in CCollision::GetMapIndices[abi:cxx11](vector2_base<float>, vector2_base<float>, unsigned int) (this=0x55555589d718 <g_GameClient+2296>, PrevPos=..., Pos=..., MaxIndices=0)
    at /home/chiller/Desktop/git/ddnet/src/game/collision.cpp:787
```

**Comment by ChillerDragon** [comment]
I tested it with the server sending this what should be very similar to what I got when I opend the issue:

https://github.com/DDNetPP/DDNetPP/commit/1fab749cd01f6d3c528a7c232b57deeddb264514#diff-a2df712cfb938eda9a173f36c865c2ccR7059

Going back to a commit in May I was able to reproduce the crashbug:
```
$ git checkout 13807edc6ab7c09d7fab9f37236498ef29df8344
```

```
Thread 1 "DDNet" received signal SIGINT, Interrupt.
0x00005555557da3f4 in CCollision::TileExists (this=0x55555589e218 <g_GameClient+2296>, Index=42223) at /home/chiller/Desktop/git/ddnet/src/game/collision.cpp:701
701		return TileExistsNext(Index);
(gdb) bt
#0  0x00005555557da3f4 in CCollision::TileExists (this=0x55555589e218 <g_GameClient+2296>, Index=42223) at /home/chiller/Desktop/git/ddnet/src/game/collision.cpp:701
#1  0x00005555557dadcc in CCollision::GetMapIndices[abi:cxx11](vector2_base<float>, vector2_base<float>, unsigned int) (this=0x55555589e218 <g_GameClient+2296>, PrevPos=..., Pos=..., MaxIndices=0)
    at /home/chiller/Desktop/git/ddnet/src/game/collision.cpp:791
#2  0x00005555557354e8 in CRaceHelper::IsStart (pClient=0x55555589d920 <g_GameClient>, Prev=..., Pos=...) at /home/chiller/Desktop/git/ddnet/src/game/client/race.cpp:85
#3  0x0000555555697d10 in CGhost::CheckStartLocal (this=0x5555559e9580 <gs_Ghost>, Predicted=false) at /home/chiller/Desktop/git/ddnet/src/game/client/components/ghost.cpp:233
#4  0x0000555555697fb3 in CGhost::OnNewSnapshot (this=0x5555559e9580 <gs_Ghost>) at /home/chiller/Desktop/git/ddnet/src/game/client/components/ghost.cpp:277
#5  0x0000555555718b9c in CGameClient::OnNewSnapshot (this=0x55555589d920 <g_GameClient>) at /home/chiller/Desktop/git/ddnet/src/game/client/gameclient.cpp:1357
#6  0x00005555556324bb in CClient::Update (this=0x7ffff35f5010) at /home/chiller/Desktop/git/ddnet/src/engine/client/client.cpp:2529
#7  0x0000555555633dc7 in CClient::Run (this=0x7ffff35f5010) at /home/chiller/Desktop/git/ddnet/src/engine/client/client.cpp:2943
#8  0x0000555555638b86 in main (argc=1, argv=0x7fffffffdaa8) at /home/chiller/Desktop/git/ddnet/src/engine/client/client.cpp:3809
```

But current DDNet client seems stable. I do not know what changes but seems to be solved.
