### ISSUE TITLE
SQL server crash in executeSql

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#1780]
```
Core was generated by `./DDRace64-Server_sql -f servers/8305.cfg'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  CSqlServer::executeSql (this=this@entry=0x0, pCommand=pCommand@entry=0x55ecdd83379f "unlock tables;")
    at /home/teeworlds/src/master/src/engine/server/sql_server.cpp:207
207		m_pStatement->execute(pCommand);
[Current thread is 1 (Thread 0x7fbf36d3d700 (LWP 20325))]
(gdb) bt
#0  CSqlServer::executeSql (this=this@entry=0x0, pCommand=pCommand@entry=0x55ecdd83379f "unlock tables;")
    at /home/teeworlds/src/master/src/engine/server/sql_server.cpp:207
#1  0x000055ecdd7d2c1b in CSqlScore::SaveTeamThread (pSqlServer=<optimized out>, pGameData=<optimized out>, 
    HandleFailure=<optimized out>) at /home/teeworlds/src/master/src/game/server/score/sql_score.cpp:1518
#2  0x000055ecdd7c8cc7 in CSqlScore::ExecSqlFunc (pUser=pUser@entry=0x55ecdfd2e7e0)
    at /home/teeworlds/src/master/src/game/server/score/sql_score.cpp:116
#3  0x000055ecdd818e67 in thread_run (user=<optimized out>) at /home/teeworlds/src/master/src/base/system.c:697
#4  0x00007fbf40e134a4 in start_thread (arg=0x7fbf36d3d700) at pthread_create.c:456
#5  0x00007fbf3fa00d0f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
(gdb) print m_pStatement
Cannot access memory at address 0x10
```
Stored in crash2 on CHL if anyone has ideas for where to look.

**Comment by def-** [comment]
Log before the crash:
```
[2019-06-11 02:09:00][ddnet]: 3 using Custom Client 11044
[2019-06-11 02:09:01][game]: kill killer='1:NiC0_99' victim='1:NiC0_99' weapon=-2 special=0
[2019-06-11 02:09:01][sql]: MySQL Error: Can't connect to MySQL server on '95.172.92.151' (110 "Connection timed out")
[2019-06-11 02:09:01][sql]: ERROR: SQL connection failed
[2019-06-11 02:09:01][sql]: Warning: Unable to connect to SqlReadServer 1 ('95.172.92.151'), trying next...
[2019-06-11 02:09:01][sql]: MySQL Error: Can't connect to MySQL server on '74.91.114.132' (110 "Connection timed out")
[2019-06-11 02:09:01][sql]: ERROR: SQL connection failed
[2019-06-11 02:09:01][sql]: Warning: Unable to connect to SqlReadServer 0 ('74.91.114.132'), trying next...
[2019-06-11 02:09:02][sql]: MySQL Error: Can't connect to MySQL server on '31.186.251.128' (110 "Connection timed out")
[2019-06-11 02:09:02][sql]: ERROR: sql connection failed
[2019-06-11 02:09:02][sql]: Warning: Unable to connect to SqlWriteServer 2 ('31.186.251.128'), trying next...
[2019-06-11 02:09:02][sql]: FATAL ERROR: No SqlWriteServers available
[2019-06-11 02:09:02][sql]: WARNING: Aborted saving team due to reload/change of map.
```
I'm guessing our locking is lacking. We shouldn't attempt to access m_pStatement while it's being overwritten.

**Comment by def-** [comment]
Most of the SQL code changed meanwhile, let's hope it's fixed.
