### ISSUE TITLE
Crash in SendServerInfo

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#1958]
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00005651e5bc9e36 in CServer::SendServerInfo (this=this@entry=0x7f5c64614010, pAddr=pAddr@entry=0x7f5c64d58850, 
    Token=Token@entry=-1, Type=Type@entry=4, SendClients=SendClients@entry=false)
    at /home/teeworlds/src/master/src/engine/server/server.cpp:1745
1745		p.AddRaw(FirstChunk.m_aData, FirstChunk.m_DataSize);
[Current thread is 1 (Thread 0x7f5c653dd980 (LWP 1026))]
(gdb) bt
#0  0x00005651e5bc9e36 in CServer::SendServerInfo (this=this@entry=0x7f5c64614010, pAddr=pAddr@entry=0x7f5c64d58850, 
    Token=Token@entry=-1, Type=Type@entry=4, SendClients=SendClients@entry=false)
    at /home/teeworlds/src/master/src/engine/server/server.cpp:1745
#1  0x00005651e5bca04f in CServer::UpdateServerInfo (this=0x7f5c64614010, Resend=<optimized out>)
    at /home/teeworlds/src/master/src/engine/shared/network.h:358
#2  0x00005651e5c39447 in CConsole::ExecuteLineStroked (this=this@entry=0x5651e6cdeb30, Stroke=Stroke@entry=1, 
    pStr=<optimized out>, pStr@entry=0x7ffca84a67d0 "sv_name \"DDNet RUS - Solo [DDraceNetwork]\"", 
    ClientID=ClientID@entry=-1, InterpretSemicolons=InterpretSemicolons@entry=true)
    at /home/teeworlds/src/master/src/engine/shared/console.cpp:504
#3  0x00005651e5c396b8 in CConsole::ExecuteLine (this=0x5651e6cdeb30, 
    pStr=0x7ffca84a67d0 "sv_name \"DDNet RUS - Solo [DDraceNetwork]\"", ClientID=-1, InterpretSemicolons=true)
    at /home/teeworlds/src/master/src/engine/shared/console.cpp:558
#4  0x00005651e5c293f6 in CConsole::ExecuteFile (this=0x5651e6cdeb30, pFilename=<optimized out>, ClientID=-1, 
    LogFailure=<optimized out>, StorageType=<optimized out>)
    at /home/teeworlds/src/master/src/engine/shared/console.cpp:604
#5  0x00005651e5c39447 in CConsole::ExecuteLineStroked (this=this@entry=0x5651e6cdeb30, Stroke=Stroke@entry=1, 
    pStr=<optimized out>, pStr@entry=0x7ffca84b8acf "exec types/solo/flexname.cfg", ClientID=ClientID@entry=-1, 
    InterpretSemicolons=InterpretSemicolons@entry=true)
    at /home/teeworlds/src/master/src/engine/shared/console.cpp:504
#6  0x00005651e5c396b8 in CConsole::ExecuteLine (this=0x5651e6cdeb30, 
    pStr=0x7ffca84b8acf "exec types/solo/flexname.cfg", ClientID=-1, InterpretSemicolons=true)
    at /home/teeworlds/src/master/src/engine/shared/console.cpp:558
#7  0x00005651e5c293f6 in CConsole::ExecuteFile (this=0x5651e6cdeb30, pFilename=<optimized out>, ClientID=-1, 
    LogFailure=<optimized out>, StorageType=<optimized out>)
    at /home/teeworlds/src/master/src/engine/shared/console.cpp:604
#8  0x00005651e5befa7d in CGameContext::OnInit (this=0x7f5c62de1010)
    at /home/teeworlds/src/master/src/game/server/gamecontext.h:122
#9  0x00005651e5bcdc05 in CServer::Run (this=this@entry=0x7f5c64614010)
    at /home/teeworlds/src/master/src/engine/server/server.h:109
#10 0x00005651e5bc2004 in main (argc=3, argv=0x7ffca84c1288)
    at /home/teeworlds/src/master/src/engine/server/server.cpp:3126
```

**Comment by def-** [comment]
Might have been fixed by https://github.com/ddnet/ddnet/commit/c2bcd3bd4d80ba38a309bb57981f2888df5372a3, so I restarted servers for now.

**Comment by def-** [comment]
Haven't seen it again, so I'll consider this fixed.
