### ISSUE TITLE
Segfault in CSqlServer::Connect while shutting down

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#2043]
```
Core was generated by `./DDRace64-Server_sql -f servers/block.cfg'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  lock::take (this=0x7fd28dc19428) at /home/teeworlds/src/master/src/base/tl/threading.h:103
103			var->take();
[Current thread is 1 (Thread 0x7fd27f7fe700 (LWP 15066))]
(gdb) bt
#0  lock::take (this=0x7fd28dc19428) at /home/teeworlds/src/master/src/base/tl/threading.h:103
#1  scope_lock::scope_lock (l=0x7fd28dc19428, this=<synthetic pointer>)
    at /home/teeworlds/src/master/src/base/tl/threading.h:103
#2  CSqlServer::Connect (this=0x55ddeeb597f0) at /home/teeworlds/src/master/src/engine/server/sql_server.cpp:119
#3  0x000055ddee6927f6 in CSqlServer::CreateTables (this=0x55ddeeb597f0)
    at /home/teeworlds/src/master/src/engine/server/sql_server.cpp:172
#4  0x000055ddee7147d7 in thread_run (user=<optimized out>) at /home/teeworlds/src/master/src/base/system.c:697
#5  0x00007fd28f808fa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#6  0x00007fd28f30a4cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) info threads
  Id   Target Id                         Frame 
* 1    Thread 0x7fd27f7fe700 (LWP 15066) lock::take (this=0x7fd28dc19428)
    at /home/teeworlds/src/master/src/base/tl/threading.h:103
  2    Thread 0x7fd28dc18700 (LWP 15062) futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, 
    futex_word=0x55ddeeb11480) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
  3    Thread 0x7fd27ffff700 (LWP 15065) _int_malloc (av=av@entry=0x7fd280000020, bytes=bytes@entry=72)
    at malloc.c:4108
  4    Thread 0x7fd27effd700 (LWP 15067) 0x00007fd28f305133 in __GI___mmap64 (offset=0, fd=-1, flags=16418, prot=0, 
    len=134217728, addr=0x0) at ../sysdeps/unix/sysv/linux/mmap64.c:52
  5    Thread 0x7fd28e9e2980 (LWP 15060) 0x00007fd28f3051d7 in munmap () at ../sysdeps/unix/syscall-template.S:78
(gdb) thread 5
[Switching to thread 5 (Thread 0x7fd28e9e2980 (LWP 15060))]
#0  0x00007fd28f3051d7 in munmap () at ../sysdeps/unix/syscall-template.S:78
78	../sysdeps/unix/syscall-template.S: No such file or directory.
(gdb) bt
#0  0x00007fd28f3051d7 in munmap () at ../sysdeps/unix/syscall-template.S:78
#1  0x000055ddee703fca in CKernel::~CKernel (this=0x55ddeeb10890, __in_chrg=<optimized out>)
    at /home/teeworlds/src/master/src/engine/kernel.h:45
#2  CKernel::~CKernel (this=0x55ddeeb10890, __in_chrg=<optimized out>)
    at /home/teeworlds/src/master/src/engine/shared/kernel.cpp:59
#3  0x000055ddee682f6f in main (argc=3, argv=0x7ffd5dc55288)
    at /home/teeworlds/src/master/src/engine/server/server.cpp:3141
```

**Comment by edg-l** [comment]
is this still relevant?

**Comment by def-** [comment]
Haven't seen it in a while so I assume no
