### ISSUE TITLE
AntibotDestroy crashes on nullpointer

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#2094]
Happens on all official DDNet servers, hopefully only while shutting down:

```
Core was generated by `./DDRace64-Server_sql -f servers/8316.cfg'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fe16bfc87e4 in _IO_new_fclose (fp=0x0) at iofclose.c:48
48      iofclose.c: No such file or directory.
[Current thread is 1 (Thread 0x7fe16b6d2dc0 (LWP 5357))]
(gdb) bt
#0  0x00007fe16bfc87e4 in _IO_new_fclose (fp=0x0) at iofclose.c:48
#1  0x00007fe16c43fc2f in AntibotDestroy () from /home/teeworlds/servers/libantibot.so
#2  0x000055cf2eccc049 in CAntibot::~CAntibot (this=<optimized out>, __in_chrg=<optimized out>)
    at /home/teeworlds/src/master/src/game/server/antibot.cpp:28
#3  0x000055cf2ece6fbc in CGameContext::~CGameContext (this=0x7fe1690d4010, __in_chrg=<optimized out>)
    at /usr/include/c++/8/ext/atomicity.h:82
#4  0x000055cf2ece712d in CGameContext::~CGameContext (this=0x7fe1690d4010, __in_chrg=<optimized out>)
    at /home/teeworlds/src/master/src/game/server/gamecontext.cpp:75
#5  0x000055cf2ed3cdea in CKernel::~CKernel (this=0x55cf2f44d890, __in_chrg=<optimized out>)
    at /home/teeworlds/src/master/src/engine/kernel.h:45
#6  CKernel::~CKernel (this=0x55cf2f44d890, __in_chrg=<optimized out>)
    at /home/teeworlds/src/master/src/engine/shared/kernel.cpp:59
#7  0x000055cf2ecbb08f in main (argc=3, argv=0x7ffff0717cf8)
    at /home/teeworlds/src/master/src/engine/server/server.cpp:3137
```

**Comment by heinrich5991** [comment]
Should've been fixed by #2095.
