### ISSUE TITLE
Same image embedded twice causes crash

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#2148]
As reported by Hawerer on Discord

**Comment by def-** [comment]
[foo.zip](https://github.com/ddnet/ddnet/files/4496626/foo.zip)
Ok, not so easy to reproduce after all, not sure why it crashes, but it seems to have hundreds of textures and one of them is huge:
```
Thread 1 "DDNet" received signal SIGSEGV, Segmentation fault.
0x00007ffff6d73408 in __memmove_avx_unaligned_erms () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff6d73408 in __memmove_avx_unaligned_erms () at /usr/lib/libc.so.6
#1  0x000055555566b636 in mem_copy (dest=0x7fff6e7e5010, source=0x555555d667a0, size=495035044)
    at src/base/system.c:263
#2  0x00005555556b21a4 in CGraphics_Threaded::LoadTextureRaw(int, int, int, void const*, int, int)
    (this=0x7ffff4587010, Width=1037, Height=9438221, Format=1, pData=0x555555d667a0, StoreFormat=1, Flags=0)
    at src/engine/client/graphics_threaded.cpp:440
#3  0x0000555555718c34 in CMapImages::OnMapLoad() (this=0x555555a84720 <gs_MapImages>)
    at src/game/client/components/mapimages.cpp:58
#4  0x0000555555785624 in CGameClient::OnConnected() (this=0x5555559310a0 <g_GameClient>)
    at src/game/client/gameclient.cpp:478
#5  0x000055555569bfae in CClient::ProcessServerPacket(CNetChunk*) (this=0x7ffff5e2f010, pPacket=0x7fffffffc440)
    at src/engine/client/client.cpp:1716
#6  0x000055555569f0c1 in CClient::PumpNetwork() (this=0x7ffff5e2f010) at src/engine/client/client.cpp:2425
#7  0x00005555556a0152 in CClient::Update() (this=0x7ffff5e2f010) at src/engine/client/client.cpp:2680
#8  0x00005555556a1535 in CClient::Run() (this=0x7ffff5e2f010) at src/engine/client/client.cpp:3031
#9  0x00005555556a712c in main(int, char const**) (argc=1, argv=0x7fffffffe4e8) at src/engine/client/client.cpp:4091
```
I guess we have many crashes on invalid map data, so not sure if we should keep looking into it.

**Comment by Jupeyy** [comment]
its very simple:
teeworlds has a hard limit for map images and that is 64.
that map uses 71 textures, maybe we need a editor warning for this too
