### ISSUE TITLE
Crash with super

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#2262]
Thanks to jao & Lady Saavik for the report, working on a fix:

```
Core was generated by `../DDRace64-Server_sql -f servers/test2.cfg'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055db789c8562 in CGameContext::ConSuper (pResult=0x7ffd5c20bd10, pUserData=0x7f75c2916010)
    at /home/teeworlds/src/master/src/game/server/ddracecommands.cpp:109
109			pSelf->m_World.m_Core.m_apCharacters[pResult->m_ClientID]->m_Super = true;
[Current thread is 1 (Thread 0x7f75c4f17dc0 (LWP 4801))]
(gdb) bt
#0  0x000055db789c8562 in CGameContext::ConSuper (pResult=0x7ffd5c20bd10, pUserData=0x7f75c2916010)
    at /home/teeworlds/src/master/src/game/server/ddracecommands.cpp:109
#1  0x000055db78a2cbd7 in CConsole::ExecuteLineStroked (this=this@entry=0x55db79cb0de0, Stroke=Stroke@entry=1, 
    pStr=<optimized out>, pStr@entry=0x7f75c4aa5494 "super", ClientID=ClientID@entry=0, 
    InterpretSemicolons=InterpretSemicolons@entry=true)
    at /home/teeworlds/src/master/src/engine/shared/console.cpp:504
#2  0x000055db78a2ce48 in CConsole::ExecuteLine (this=0x55db79cb0de0, pStr=0x7f75c4aa5494 "super", ClientID=0, 
    InterpretSemicolons=true) at /home/teeworlds/src/master/src/engine/shared/console.cpp:558
#3  0x000055db78a1be00 in CConsole::ExecuteLineFlag (this=0x55db79cb0de0, pStr=<optimized out>, 
    FlagMask=<optimized out>, ClientID=<optimized out>, InterpretSemicolons=<optimized out>)
    at /home/teeworlds/src/master/src/engine/shared/console.cpp:566
#4  0x000055db789bd533 in CServer::ProcessClientPacket (this=this@entry=0x7f75c414b010, 
    pPacket=pPacket@entry=0x7ffd5c217320) at /home/teeworlds/src/master/src/engine/server/server.h:120
#5  0x000055db789bdca6 in CServer::PumpNetwork (this=this@entry=0x7f75c414b010)
    at /home/teeworlds/src/master/src/engine/server/server.cpp:1922
#6  0x000055db789beaa7 in CServer::Run (this=this@entry=0x7f75c414b010)
    at /home/teeworlds/src/master/src/engine/server/server.cpp:2239
#7  0x000055db789b226b in main (argc=3, argv=0x7ffd5c2177d8)
    at /home/teeworlds/src/master/src/engine/server/server.cpp:3224
(gdb) print pResult->m_ClientID
$1 = 0
(gdb) print pSelf->m_World.m_Core.m_apCharacters
$2 = {0x0, 0x55db78aa9708 <ms_PoolDataCCharacter+2280>, 0x55db78aa9d48 <ms_PoolDataCCharacter+3880>, 
  0x0 <repeats 61 times>}
(gdb) print pSelf->m_World.m_Core.m_apCharacters[0]
$3 = (CCharacterCore *) 0x0
```

**Comment by def-** [comment]
To reproduce: /spec and super
