### ISSUE TITLE
Crash in CPlayer::Snap on many servers

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#2323]
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000564005314ee7 in CPlayer::Snap (this=0x5640053efcf8 <ms_PoolDataCPlayer+10296>, SnappingClient=SnappingClient@entry=4) at /home/teeworlds/src/master/src/game/server/gamecontext.h:122
122             IServer *Server() const { return m_pServer; }
[Current thread is 1 (Thread 0x7f055fe0bdc0 (LWP 1095))]
(gdb) bt
#0  0x0000564005314ee7 in CPlayer::Snap (this=0x5640053efcf8 <ms_PoolDataCPlayer+10296>, SnappingClient=SnappingClient@entry=4) at /home/teeworlds/src/master/src/game/server/gamecontext.h:122
#1  0x0000564005301148 in CGameContext::OnSnap (this=0x7f055d809010, ClientID=4) at /home/teeworlds/src/master/src/game/server/gamecontext.cpp:3331
#2  0x00005640052d90d3 in CServer::DoSnapshot (this=this@entry=0x7f055f03f010) at /home/teeworlds/src/master/src/engine/server/server.h:119
#3  0x00005640052dfb2d in CServer::Run (this=this@entry=0x7f055f03f010) at /home/teeworlds/src/master/src/engine/server/server.cpp:2508
#4  0x00005640052d23c6 in main (argc=3, argv=0x7ffdddd56d28) at /home/teeworlds/src/master/src/engine/server/server.cpp:3525
```
@Learath2 Can you take a look? I think this was caused by https://github.com/ddnet/ddnet/commit/62d014d999285859e4f948dcb8621f1485e7dce7

I reverted official servers to https://github.com/ddnet/ddnet/commit/07830c868fa9af85c3f202b1616144609c127130 for now.

**Comment by def-** [comment]
Hasn't occured again since reverting the servers, so my guess seems good. Another change that was also reverted by this was https://github.com/ddnet/ddnet/commit/287e3e2a45b766214532288be83a1c92c86574ba though
