### ISSUE TITLE
Segfault on Server when trying to load a map that doesn't exist

### ISSUE THREAD

**Issue by edg-l** [ddnet/ddnet#2539]
```
(gdb) run
Starting program: /home/ryozuki/Documents/ddnet/build/DDNet-Server
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff6880700 (LWP 29353)]
[2020-08-06 20:39:42][engine]: running on unix-linux-amd64
[2020-08-06 20:39:42][engine]: arch is little endian
[New Thread 0x7ffff607f700 (LWP 29354)]
[New Thread 0x7ffff587e700 (LWP 29355)]
[2020-08-06 20:39:42][storage]: couldn't open storage.cfg
[2020-08-06 20:39:42][storage]: using standard paths
[2020-08-06 20:39:42][storage]: added path '$USERDIR' ('/home/ryozuki/.teeworlds')
[2020-08-06 20:39:42][storage]: added path '$DATADIR' ('data')
[2020-08-06 20:39:42][storage]: added path '$CURRENTDIR' ('/home/ryozuki/Documents/ddnet/build')
[2020-08-06 20:39:42][host lookup]: host='localhost' port=0 1
[2020-08-06 20:39:42][host lookup]: host='localhost' port=0 2
[2020-08-06 20:39:42][console]: executing 'autoexec.cfg'
[2020-08-06 20:39:42][server]: starting...
[2020-08-06 20:39:42][datafile]: loading. filename='maps/TowerOfGod .map'
[2020-08-06 20:39:42][datafile]: could not open 'maps/TowerOfGod .map'
[2020-08-06 20:39:42][server]: failed to load map. mapname='TowerOfGod '
[Thread 0x7ffff587e700 (LWP 29355) exited]
[Thread 0x7ffff607f700 (LWP 29354) exited]
free(): invalid pointer
[Thread 0x7ffff6880700 (LWP 29353) exited]

Thread 1 "DDNet-Server" received signal SIGABRT, Aborted.
0x00007ffff7723355 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff7723355 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff770c853 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff7766878 in __libc_message () from /usr/lib/libc.so.6
#3  0x00007ffff776dd3a in malloc_printerr () from /usr/lib/libc.so.6
#4  0x00007ffff776eef4 in _int_free () from /usr/lib/libc.so.6
#5  0x0000555555667d57 in sql::SQLString::~SQLString (this=0x55555588edb0 <sql::mysql::emptyStr>, __in_chrg=<optimized out>) at ../ddnet-libs/mysql/include/cppconn/sqlstring.h:55
#6  0x00007ffff7725c57 in __run_exit_handlers () from /usr/lib/libc.so.6
#7  0x00007ffff7725dfe in exit () from /usr/lib/libc.so.6
#8  0x00007ffff770e009 in __libc_start_main () from /usr/lib/libc.so.6
#9  0x00005555555e9b8e in _start ()
(gdb)
```

Most possible related to SQLString

**Comment by def-** [comment]
Can't reproduce.

**Comment by def-** [comment]
@edg-l Any hints?

**Comment by edg-l** [comment]
When i tried it, sql was not connected to any server, in fact i didnt even add the config for it
