### ISSUE TITLE
move_sqlite.py: Handle case of empty tables

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#2565]
@Zwelf want to take it or should I?

```
Traceback (most recent call last):
  File "scripts/move_sqlite.py", line 90, in <module>
    main()
  File "scripts/move_sqlite.py", line 60, in main
    num_ranks = sqlite_num_transfer(conn, 'record_race')
  File "scripts/move_sqlite.py", line 22, in sqlite_num_transfer
    c.execute('SELECT COUNT(*) FROM {}'.format(table))
sqlite3.OperationalError: no such table: record_race
```

**Comment by Zwelf** [comment]
I can create a PR for this one.

**Comment by def-** [comment]
Other than the script works really well, I like it. Also seems safer with the exclusive connection.
