### ISSUE TITLE
Client segfault when trying to join teesmash mod

### ISSUE THREAD

**Issue by edg-l** [ddnet/ddnet#2643]
Client crashes after connecting (but you never get ingame)

```
Thread 1 "DDNet" received signal SIGSEGV, Segmentation fault.
CCollision::Init (this=0x55555596a278 <g_GameClient+2296>, pLayers=0x55555596a228 <g_GameClient+2216>) at ../src/game/collision.cpp:66
66		m_Width = m_pLayers->GameLayer()->m_Width;
(gdb) bt
#0  CCollision::Init(CLayers*) (this=0x55555596a278 <g_GameClient+2296>, pLayers=0x55555596a228 <g_GameClient+2216>) at ../src/game/collision.cpp:66
#1  0x00005555557b1a10 in CGameClient::OnConnected() (this=0x555555969980 <g_GameClient>) at ../src/game/client/gameclient.cpp:467
#2  0x00005555556be9ec in CClient::ProcessServerPacket(CNetChunk*) (this=0x7ffff5f5d010, pPacket=0x7fffffffb600) at ../src/engine/client/client.cpp:1784
#3  0x00005555556c1bf0 in CClient::PumpNetwork() (this=0x7ffff5f5d010) at ../src/engine/client/client.cpp:2502
#4  0x00005555556c2cea in CClient::Update() (this=0x7ffff5f5d010) at ../src/engine/client/client.cpp:2772
#5  0x00005555556c42d6 in CClient::Run() (this=0x7ffff5f5d010) at ../src/engine/client/client.cpp:3146
#6  0x00005555556ca075 in main(int, char const**) (argc=1, argv=0x7fffffffdec8) at ../src/engine/client/client.cpp:4225
```

**Comment by edg-l** [comment]
```
heinrich5991Today at 21:17
vanilla token?
RyozukiToday at 21:17
hm?
heinrich5991Today at 21:17
some version of the vanilla token system is implemented with dm1
RyozukiToday at 21:18
@heinrich5991 does it use the client map too?
https://github.com/ddnet/ddnet/commit/4da0592d78ed57b15738cc6cc63ce5e59723f070
GitHub
Replace Kobra 4 and Goo! with Gold Mine · ddnet/ddnet@4da0592
and add maps7 version

this commit removes dm1
i think
maybe its that
heinrich5991Today at 21:19
ah yea, maybe that
RyozukiToday at 21:19
so git bisect never lies
we should add dm1 then?
```

**Comment by def-** [comment]
Ooooh, sorry. I haven't thought about that!
