### ISSUE TITLE
Retry SQL server on writes before writing to sqlite file

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#2746]
@Zwelf What do you think about keeping a failed job around and retrying X seconds later? Or keep retrying for a while. Would make my life much easier than having to insert SQlite file into real DB from all locations multiple times a day.

**Comment by Zwelf** [comment]
Yes, I think it would be worth. A few problems, that should be encountered:
* When the server shuts down, it waits max 60 seconds for SQL queries to finish before completely shutting down. The queries waiting X seconds should be completed as soon as possible, when a shutdown is issued.
*  `/save` and `/load` shouldn't be re-requested after X seconds, because players need the feedback as soon as possible. I think it would be worth considering to not even forward the `/load`/`/save`-requests to the backup SQLite database, therefore disabling the `/save`-feature when the database is unreachable.

**Comment by def-** [comment]
@Zwelf Do you want to take this issue?

**Comment by Zwelf** [comment]
Yes, I have roughly an idea how I would like to implement it. I try to make the PR tomorrow.

**Comment by def-** [comment]
Btw, I also keep getting deadlocks:
```
Traceback (most recent call last):
  File "/home/teeworlds/servers/scripts/remove-duplicate-teamranks.py", line 25, in <module>
    cur.execute("delete from record_teamrace where ID in (%s)" % (','.join(['"%s"' % con.escape_string(i) for i in
ids])))
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
_mysql_exceptions.OperationalError: (1213, 'Deadlock found when trying to get lock; try restarting transaction')
```

**Comment by def-** [comment]
I have tried setting the tcp_keepalive_timet to 600 and increasing the write/read/connect mysql timeouts in the hopes of reducing the constant timeouts we are seeing.

**Comment by def-** [comment]
I think I know one of the reasons things have gotten worse since I switched to a single SQL server. It's the same SQL server the ddnet website runs on, and refreshing the /ranks/ page will lock things for so long that the queries will fail. The SQL intensive part of the /ranks/refresh always runs every hour from minutes 3-25. And in the logs you can clearly see that that's when the timeouts happen:
```
8301.log:[2020-09-06 20:15:15][sql]: save team score failed
8301.log:[2020-09-06 21:18:59][sql]: save team score failed
8301.log:[2020-09-06 21:20:51][sql]: save team score failed
8304.log:[2020-09-06 20:24:01][sql]: save team score failed
8305.log:[2020-09-06 12:22:15][sql]: save team score failed
8305.log:[2020-09-06 14:21:33][sql]: save team score failed
8306.log:[2020-09-06 19:17:28][sql]: save team score failed
8306.log:[2020-09-06 19:22:57][sql]: save team score failed
8309.log:[2020-09-06 14:04:04][sql]: save team score failed
8313.log:[2020-09-06 00:14:01][sql]: save team score failed
8313.log:[2020-09-06 18:17:31][sql]: show team rank failed
8314.log:[2020-09-06 12:18:20][sql]: save team score failed
8314.log:[2020-09-06 17:23:51][sql]: save team score failed
8314.log:[2020-09-06 22:05:09][sql]: save team score failed
8318.log:[2020-09-06 11:02:22][sql]: save team score failed
8318.log:[2020-09-06 15:11:51][sql]: save team score failed
8318.log:[2020-09-06 21:03:42][sql]: save team score failed
8321.log:[2020-09-06 13:02:21][sql]: save team score failed
8321.log:[2020-09-06 18:04:10][sql]: save team score failed
8324.log:[2020-09-06 22:03:37][sql]: save team score failed
8326.log:[2020-09-06 14:03:52][sql]: save team score failed
8326.log:[2020-09-06 16:15:12][sql]: save team score failed
```
So I guess the clean solution would be to get a separate database server or improve my /ranks/ code so that it doesn't overload the DB for so long
