### ISSUE TITLE
LAN tab crashes with websockets

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#2853]
@QingGo 
```
Thread 1 "DDNet" received signal SIGSEGV, Segmentation fault.
0x00007ffff7594b0f in __memmove_avx_unaligned_erms () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff7594b0f in __memmove_avx_unaligned_erms () at /usr/lib/libc.so.6
#1  0x0000555555c53b01 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&) ()
#2  0x000055555577577a in websocket_callback(lws*, lws_callback_reasons, void*, void*, size_t)
    (wsi=0x5555568ab0a0, reason=LWS_CALLBACK_WSI_CREATE, user=0x55555724af40, in=0x0, len=0)
    at src/engine/shared/websockets.cpp:100
#3  0x0000555555975627 in lws_client_connect_3_connect (wsi=0x5555568ab0a0, ads=0x0, result=0x0, n=0, opaque=0x0)
    at /x86-64/libwebsockets-4.1.1/lib/roles/http/client/client-handshake.c:794
#4  0x0000555555971ec5 in lws_client_socket_service (wsi=0x5555568ab0a0, pollfd=0x555556843d30)
    at /x86-64/libwebsockets-4.1.1/lib/roles/http/client/client-http.c:136
#5  0x000055555595f2f4 in rops_handle_POLLIN_h1 (pt=0x5555568426b0, wsi=0x5555568ab0a0, pollfd=0x555556843d30)
    at /x86-64/libwebsockets-4.1.1/lib/roles/h1/ops-h1.c:699
#6  0x000055555594efec in lws_service_fd_tsi (context=0x555556842530, pollfd=0x555556843d30, tsi=0)
    at /x86-64/libwebsockets-4.1.1/lib/core-net/service.c:710
#7  0x000055555597786d in _lws_plat_service_forced_tsi (context=0x555556842530, tsi=0)
    at /x86-64/libwebsockets-4.1.1/lib/plat/unix/unix-service.c:49
#8  0x0000555555977bf1 in _lws_plat_service_tsi (context=0x555556842530, timeout_ms=0, tsi=0)
    at /x86-64/libwebsockets-4.1.1/lib/plat/unix/unix-service.c:207
#9  0x0000555555977c54 in lws_plat_service (context=0x555556842530, timeout_ms=-1)
    at /x86-64/libwebsockets-4.1.1/lib/plat/unix/unix-service.c:221
#10 0x000055555594f17b in lws_service (context=0x555556842530, timeout_ms=-1)
    at /x86-64/libwebsockets-4.1.1/lib/core-net/service.c:779
#11 0x0000555555775f6d in websocket_send(int, unsigned char const*, size_t, char const*, int)
    (socket=2, data=0x7fffffffa4d0 "xe\314", <incomplete sequence \351>, size=15, addr_str=0x7fffffffa440 "0.0.0.0", port=8303) at src/engine/shared/websockets.cpp:270
#12 0x00005555557832c5 in net_udp_send (sock=..., addr=0x7fffffffab04, data=0x7fffffffa4d0, size=15)
    at src/base/system.c:1510
#13 0x0000555555766fb1 in CNetBase::SendPacketConnless(NETSOCKET, NETADDR*, void const*, int, bool, unsigned char*)
    (Socket=..., pAddr=0x7fffffffab04, pData=0x7fffffffab3f, DataSize=9, Extended=true, aExtra=0x7fffffffab30 "\314", <incomplete sequence \351>) at src/engine/shared/network.cpp:110
#14 0x0000555555768431 in CNetClient::Send(CNetChunk*) (this=0x7ffff6334960, pChunk=0x7fffffffab00)
    at src/engine/shared/network_client.cpp:115
#15 0x00005555557f59a3 in CServerBrowser::Refresh(int) (this=0x7ffff63c4270, Type=2)
    at src/engine/client/serverbrowser.cpp:690
#16 0x0000555555869111 in CMenus::RenderMenubar(CUIRect) (this=0x55555620d460 <gs_Menus>, r=...)
    at src/game/client/components/menus.cpp:837
#17 0x000055555586b0d3 in CMenus::Render() (this=0x55555620d460 <gs_Menus>)
    at src/game/client/components/menus.cpp:1243
#18 0x000055555587176a in CMenus::OnRender() (this=0x55555620d460 <gs_Menus>)
    at src/game/client/components/menus.cpp:2219
#19 0x00005555558c28fc in CGameClient::OnRender() (this=0x5555560b1860 <g_GameClient>)
    at src/game/client/gameclient.cpp:644
#20 0x00005555557bb559 in CClient::Render() (this=0x7ffff62bd010) at src/engine/client/client.cpp:1138
#21 0x00005555557c3ed8 in CClient::Run() (this=0x7ffff62bd010) at src/engine/client/client.cpp:3266
#22 0x00005555557c9fc1 in main(int, char const**) (argc=1, argv=0x7fffffffe4d8) at src/engine/client/client.cpp:4311
(gdb)
```

**Comment by QingGo** [comment]
I think the reason is that connect to an address "0.0.0.0" didn't make sense to libwebsockets. And when we are trying to connect to "localhost", actually Client will use the address "0.0.0.0". I 'll try to find a fix later.

**Comment by QingGo** [comment]
Any maybe there are some problem on the commit 65ca97a5fa9e1441e3933b0f2e5ea5cab89b12fc, it let the websocket client can not connect to websocket server.

**Comment by def-** [comment]
Oh, aren't the websocket sockets able to use select?

**Comment by QingGo** [comment]
> Oh, aren't the websocket sockets able to use select?

actully it could, but we should enter libwebsockets' event loop first and let it establish the connection, or it could get the correct fd

**Comment by QingGo** [comment]
this PR https://github.com/ddnet/ddnet/pull/2859 should fix the "select" problem. but now it is still some problem when connect with ws://localhost:8303

**Comment by QingGo** [comment]
when connecting with ws://localhost:8303, some time it could successfully find the address of "localhost" is "127.0.0.1" and connect successfully but sometime it can not. It is weird. maybe it is related to the implement of getaddrinfo and we should give it enough hint

**Comment by QingGo** [comment]
maybe this PR https://github.com/ddnet/ddnet/pull/2860 can fix the localhost lookup problem when websockets enable

**Comment by def-** [comment]
Probably it tries ipv6 localhost half of the time.

**Comment by QingGo** [comment]
maybe. By the way, will it crash when connecting to the local server?

**Comment by def-** [comment]
I don't know. Shouldn't you test?

**Comment by QingGo** [comment]
I have tested it. At least it work well in MacOS computer.

**Comment by edg-l** [comment]
It still crashes on when looking at lan tab.

**Comment by QingGo** [comment]
> It still crashes on when looking at lan tab. (linux)

did it crashed when you switch to the LAN tab? Or did it crached when you try to connect a local LAN websocket game server?

**Comment by edg-l** [comment]
when i switched to lan tab

**Comment by QingGo** [comment]
> when i switched to lan tab

ah, actully I have no idea what happen. it will be appreciate if you can provide a gdb tracktrace info to me.

**Comment by edg-l** [comment]
```
[2020-09-20 14:34:09][register]: fetching server counts
[2020-09-20 14:34:09][regsixup]: fetching server counts
[2020-09-20 14:34:09][websockets]: connection established with 127.0.0.1:8303

Thread 1 "DDNet" received signal SIGSEGV, Segmentation fault.
0x00007ffff509fb0f in __memmove_avx_unaligned_erms () from /usr/lib/libc.so.6
(gdb) [2020-09-20 14:34:10][regsixup]: chose 'master2.teeworlds.com' as master, sending heartbeats
bt
#0  0x00007ffff509fb0f in __memmove_avx_unaligned_erms () at /usr/lib/libc.so.6
#1  0x00007ffff53a34f1 in std::char_traits<char>::copy(char*, char const*, unsigned long) (__n=<optimized out>, __s2=<optimized out>, __s1=<optimized out>)
    at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/char_traits.h:395
#2  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_copy(char*, char const*, unsigned long)
    (__n=<optimized out>, __s=<optimized out>, __d=<optimized out>) at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.h:351
#3  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_copy(char*, char const*, unsigned long)
    (__n=<optimized out>, __s=<optimized out>, __d=<optimized out>) at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.h:346
#4  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)
    (this=0x5555567918a8, __str=...) at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.h:722
#5  0x000055555568ab42 in websocket_callback(lws*, lws_callback_reasons, void*, void*, size_t) (wsi=0x555556780c30, reason=LWS_CALLBACK_WSI_CREATE, user=0x5555567918a0, in=0x0, len=0)
    at ../src/engine/shared/websockets.cpp:100
#6  0x00007ffff7c6d598 in  () at /usr/lib/libwebsockets.so.17
#7  0x00007ffff7c6c239 in  () at /usr/lib/libwebsockets.so.17
#8  0x00007ffff7c5cb0b in  () at /usr/lib/libwebsockets.so.17
#9  0x00007ffff7c4a3c6 in lws_service_fd_tsi () at /usr/lib/libwebsockets.so.17
#10 0x00007ffff7c2af0c in _lws_plat_service_forced_tsi () at /usr/lib/libwebsockets.so.17
#11 0x00007ffff7c2b19c in _lws_plat_service_tsi () at /usr/lib/libwebsockets.so.17
#12 0x00007ffff7c4a60e in lws_service () at /usr/lib/libwebsockets.so.17
#13 0x000055555568b335 in websocket_send(int, unsigned char const*, size_t, char const*, int) (socket=2, data=0x7fffffff9f70 "xe?\205", size=15, addr_str=0x7fffffff9ee0 "0.0.0.0", port=8303)
    at ../src/engine/shared/websockets.cpp:270
#14 0x0000555555697c62 in net_udp_send (sock=..., addr=0x7fffffffa5a4, data=0x7fffffff9f70, size=15) at ../src/base/system.c:1514
#15 0x000055555567c371 in CNetBase::SendPacketConnless(NETSOCKET, NETADDR*, void const*, int, bool, unsigned char*)
    (Socket=..., pAddr=0x7fffffffa5a4, pData=0x7fffffffa5df, DataSize=9, Extended=true, aExtra=0x7fffffffa5d0 "?\205") at ../src/engine/shared/network.cpp:110
#16 0x000055555567d7f1 in CNetClient::Send(CNetChunk*) (this=0x7fffef5df960, pChunk=0x7fffffffa5a0) at ../src/engine/shared/network_client.cpp:115
#17 0x000055555570a3f1 in CServerBrowser::Refresh(int) (this=0x7fffef66f270, Type=2) at ../src/engine/client/serverbrowser.cpp:690
#18 0x000055555577dd9f in CMenus::RenderMenubar(CUIRect) (this=0x555555cf1d80 <gs_Menus>, r=...) at ../src/game/client/components/menus.cpp:837
#19 0x000055555577fd61 in CMenus::Render() (this=0x555555cf1d80 <gs_Menus>) at ../src/game/client/components/menus.cpp:1243
#20 0x00005555557863f8 in CMenus::OnRender() (this=0x555555cf1d80 <gs_Menus>) at ../src/game/client/components/menus.cpp:2219
#21 0x00005555557d74ec in CGameClient::OnRender() (this=0x555555b96180 <g_GameClient>) at ../src/game/client/gameclient.cpp:644
#22 0x00005555556cffa7 in CClient::Render() (this=0x7fffef568010) at ../src/engine/client/client.cpp:1138
#23 0x00005555556d8926 in CClient::Run() (this=0x7fffef568010) at ../src/engine/client/client.cpp:3266
#24 0x00005555556dea0f in main(int, char const**) (argc=1, argv=0x7fffffffdf78) at ../src/engine/client/client.cpp:4311
(gdb) [2020-09-20 14:34:14][register]: chose 'master4.teeworlds.com' as master, sending heartbeats
```

**Comment by QingGo** [comment]
> ```
> [2020-09-20 14:34:09][register]: fetching server counts
> [2020-09-20 14:34:09][regsixup]: fetching server counts
> [2020-09-20 14:34:09][websockets]: connection established with 127.0.0.1:8303
> 
> Thread 1 "DDNet" received signal SIGSEGV, Segmentation fault.
> 0x00007ffff509fb0f in __memmove_avx_unaligned_erms () from /usr/lib/libc.so.6
> (gdb) [2020-09-20 14:34:10][regsixup]: chose 'master2.teeworlds.com' as master, sending heartbeats
> bt
> #0  0x00007ffff509fb0f in __memmove_avx_unaligned_erms () at /usr/lib/libc.so.6
> #1  0x00007ffff53a34f1 in std::char_traits<char>::copy(char*, char const*, unsigned long) (__n=<optimized out>, __s2=<optimized out>, __s1=<optimized out>)
>     at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/char_traits.h:395
> #2  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_copy(char*, char const*, unsigned long)
>     (__n=<optimized out>, __s=<optimized out>, __d=<optimized out>) at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.h:351
> #3  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_copy(char*, char const*, unsigned long)
>     (__n=<optimized out>, __s=<optimized out>, __d=<optimized out>) at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.h:346
> #4  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)
>     (this=0x5555567918a8, __str=...) at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.h:722
> #5  0x000055555568ab42 in websocket_callback(lws*, lws_callback_reasons, void*, void*, size_t) (wsi=0x555556780c30, reason=LWS_CALLBACK_WSI_CREATE, user=0x5555567918a0, in=0x0, len=0)
>     at ../src/engine/shared/websockets.cpp:100
> #6  0x00007ffff7c6d598 in  () at /usr/lib/libwebsockets.so.17
> #7  0x00007ffff7c6c239 in  () at /usr/lib/libwebsockets.so.17
> #8  0x00007ffff7c5cb0b in  () at /usr/lib/libwebsockets.so.17
> #9  0x00007ffff7c4a3c6 in lws_service_fd_tsi () at /usr/lib/libwebsockets.so.17
> #10 0x00007ffff7c2af0c in _lws_plat_service_forced_tsi () at /usr/lib/libwebsockets.so.17
> #11 0x00007ffff7c2b19c in _lws_plat_service_tsi () at /usr/lib/libwebsockets.so.17
> #12 0x00007ffff7c4a60e in lws_service () at /usr/lib/libwebsockets.so.17
> #13 0x000055555568b335 in websocket_send(int, unsigned char const*, size_t, char const*, int) (socket=2, data=0x7fffffff9f70 "xe?\205", size=15, addr_str=0x7fffffff9ee0 "0.0.0.0", port=8303)
>     at ../src/engine/shared/websockets.cpp:270
> #14 0x0000555555697c62 in net_udp_send (sock=..., addr=0x7fffffffa5a4, data=0x7fffffff9f70, size=15) at ../src/base/system.c:1514
> #15 0x000055555567c371 in CNetBase::SendPacketConnless(NETSOCKET, NETADDR*, void const*, int, bool, unsigned char*)
>     (Socket=..., pAddr=0x7fffffffa5a4, pData=0x7fffffffa5df, DataSize=9, Extended=true, aExtra=0x7fffffffa5d0 "?\205") at ../src/engine/shared/network.cpp:110
> #16 0x000055555567d7f1 in CNetClient::Send(CNetChunk*) (this=0x7fffef5df960, pChunk=0x7fffffffa5a0) at ../src/engine/shared/network_client.cpp:115
> #17 0x000055555570a3f1 in CServerBrowser::Refresh(int) (this=0x7fffef66f270, Type=2) at ../src/engine/client/serverbrowser.cpp:690
> #18 0x000055555577dd9f in CMenus::RenderMenubar(CUIRect) (this=0x555555cf1d80 <gs_Menus>, r=...) at ../src/game/client/components/menus.cpp:837
> #19 0x000055555577fd61 in CMenus::Render() (this=0x555555cf1d80 <gs_Menus>) at ../src/game/client/components/menus.cpp:1243
> #20 0x00005555557863f8 in CMenus::OnRender() (this=0x555555cf1d80 <gs_Menus>) at ../src/game/client/components/menus.cpp:2219
> #21 0x00005555557d74ec in CGameClient::OnRender() (this=0x555555b96180 <g_GameClient>) at ../src/game/client/gameclient.cpp:644
> #22 0x00005555556cffa7 in CClient::Render() (this=0x7fffef568010) at ../src/engine/client/client.cpp:1138
> #23 0x00005555556d8926 in CClient::Run() (this=0x7fffef568010) at ../src/engine/client/client.cpp:3266
> #24 0x00005555556dea0f in main(int, char const**) (argc=1, argv=0x7fffffffdf78) at ../src/engine/client/client.cpp:4311
> (gdb) [2020-09-20 14:34:14][register]: chose 'master4.teeworlds.com' as master, sending heartbeats
> ```

thank you. It seem that client are still trying to fetch LAN server info from 0.0.0.0 and the last fix I submit did not solve this problem. I will continue to find how to solve this problem in linux.

**Comment by QingGo** [comment]
![image](https://user-images.githubusercontent.com/13678719/93898299-a6117280-fd25-11ea-9259-fadcbb9b889b.png)
I test it on debian 9 under WSL2, but client did not crash under LAN tab. wried.

**Comment by def-** [comment]
Works fine form e too in LAN tab now. @edg-l Did you run the most recent version?

**Comment by def-** [comment]
Actually I forgot I disabled websockets in build. It crashes on Linux after all:

```
(gdb) bt
#0  0x00007ffff50b9b0f in __memmove_avx_unaligned_erms () at /usr/lib/libc.so.6
#1  0x00007ffff53bd4f1 in std::char_traits<char>::copy(char*, char const*, unsigned long) (__n=<optimized out>, __s2=<optimized out>, __s1=<optimized out>)
    at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/char_traits.h:395
#2  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_copy(char*, char const*, unsigned long) (__n=<optimized out>, __s=<optimized out>, __d=<optimized out>)
    at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.h:351
#3  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_copy(char*, char const*, unsigned long) (__n=<optimized out>, __s=<optimized out>, __d=<optimized out>)
    at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.h:346
#4  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&) (this=0x555556253078, __str=...)
    at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.h:722
#5  0x0000555555698970 in websocket_callback(lws*, lws_callback_reasons, void*, void*, size_t) (wsi=0x555557adb5a0, reason=LWS_CALLBACK_WSI_CREATE, user=0x555556253070, in=0x0, len=0) at src/engine/shared/websockets.cpp:100
#6  0x00007ffff7c825c8 in  () at /usr/lib/libwebsockets.so.17
#7  0x00007ffff7c81269 in  () at /usr/lib/libwebsockets.so.17
#8  0x00007ffff7c71b3b in  () at /usr/lib/libwebsockets.so.17
#9  0x00007ffff7c5f406 in lws_service_fd_tsi () at /usr/lib/libwebsockets.so.17
#10 0x00007ffff7c3ff0c in _lws_plat_service_forced_tsi () at /usr/lib/libwebsockets.so.17
#11 0x00007ffff7c4019c in _lws_plat_service_tsi () at /usr/lib/libwebsockets.so.17
#12 0x00007ffff7c5f64e in lws_service () at /usr/lib/libwebsockets.so.17
#13 0x0000555555699163 in websocket_send(int, unsigned char const*, size_t, char const*, int) (socket=2, data=0x7fffffffa4f0 "xe", <incomplete sequence \373>, size=15, addr_str=0x7fffffffa460 "0.0.0.0", port=8303)
    at src/engine/shared/websockets.cpp:270
#14 0x00005555556a5a90 in net_udp_send (sock=..., addr=0x7fffffffab24, data=0x7fffffffa4f0, size=15) at src/base/system.c:1530
#15 0x000055555568a027 in CNetBase::SendPacketConnless(NETSOCKET, NETADDR*, void const*, int, bool, unsigned char*)
    (Socket=..., pAddr=0x7fffffffab24, pData=0x7fffffffab5f, DataSize=9, Extended=true, aExtra=0x7fffffffab50 <incomplete sequence \373>) at src/engine/shared/network.cpp:109
#16 0x000055555568b4a7 in CNetClient::Send(CNetChunk*) (this=0x7fffef5e0960, pChunk=0x7fffffffab20) at src/engine/shared/network_client.cpp:113
#17 0x000055555571bc05 in CServerBrowser::Refresh(int) (this=0x7fffef670270, Type=2) at src/engine/client/serverbrowser.cpp:665
#18 0x000055555579545d in CMenus::RenderMenubar(CUIRect) (this=0x555555d1b340 <gs_Menus>, r=...) at src/game/client/components/menus.cpp:842
#19 0x0000555555797530 in CMenus::Render() (this=0x555555d1b340 <gs_Menus>) at src/game/client/components/menus.cpp:1281
#20 0x000055555579e328 in CMenus::OnRender() (this=0x555555d1b340 <gs_Menus>) at src/game/client/components/menus.cpp:2334
#21 0x00005555557f88e2 in CGameClient::OnRender() (this=0x555555bbf660 <g_GameClient>) at src/game/client/gameclient.cpp:671
#22 0x00005555556df615 in CClient::Render() (this=0x7fffef569010) at src/engine/client/client.cpp:1135
#23 0x00005555556e80f0 in CClient::Run() (this=0x7fffef569010) at src/engine/client/client.cpp:3288
#24 0x00005555556ee2cd in main(int, char const**) (argc=1, argv=0x7fffffffe508) at src/engine/client/client.cpp:4344
```

**Comment by Robyt3** [comment]
Seems like a duplicate of #1900.
