### ISSUE TITLE
Various Undefined Behaviour on real server run

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3135]
GER2:8309:
```
/home/teeworlds/src/master/src/base/vmath.h:106:17: runtime error: division by zero
    #0 0x545572 in vector2_base<float> normalize<float>(vector2_base<float> const&) /home/teeworlds/src/master/src/base/vmath.h:106:17
    #1 0x7091b2 in CCharacterCore::Tick(bool) /home/teeworlds/src/master/src/game/gamecore.cpp:130:25
    #2 0x510354 in CCharacter::Tick() /home/teeworlds/src/master/src/game/server/entities/character.cpp:772:9
    #3 0x5e828e in CGameWorld::Tick() /home/teeworlds/src/master/src/game/server/gameworld.cpp:261:11
    #4 0x58bb90 in CGameContext::OnTick() /home/teeworlds/src/master/src/game/server/gamecontext.cpp:751:10
    #5 0x4aeb9e in CServer::Run() /home/teeworlds/src/master/src/engine/server/server.cpp:2544:19
    #6 0x4c139d in main /home/teeworlds/src/master/src/engine/server/server.cpp:3537:21
    #7 0x7f1de53dd09a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)
    #8 0x4504f9 in _start (/home/teeworlds/servers/DDNet-Server-ubsan+0x4504f9)

/home/teeworlds/src/master/src/game/gamecore.cpp:474:16: runtime error: division by zero
    #0 0x70d555 in CCharacterCore::Move() /home/teeworlds/src/master/src/game/gamecore.cpp:474:16
    #1 0x515827 in CCharacter::TickDefered() /home/teeworlds/src/master/src/game/server/entities/character.cpp:817:9
    #2 0x5e84ee in CGameWorld::Tick() /home/teeworlds/src/master/src/game/server/gameworld.cpp:269:11
    #3 0x58bb90 in CGameContext::OnTick() /home/teeworlds/src/master/src/game/server/gamecontext.cpp:751:10
    #4 0x4aeb9e in CServer::Run() /home/teeworlds/src/master/src/engine/server/server.cpp:2544:19
    #5 0x4c139d in main /home/teeworlds/src/master/src/engine/server/server.cpp:3537:21
    #6 0x7f1de53dd09a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)
    #7 0x4504f9 in _start (/home/teeworlds/servers/DDNet-Server-ubsan+0x4504f9)

/home/teeworlds/src/master/src/base/vmath.h:121:18: runtime error: division by zero
    #0 0x70a373 in vector2_base<float> closest_point_on_line<float>(vector2_base<float>, vector2_base<float>, vector2_base<float>) /home/teeworlds/src/master/src/base/vmath.h:121:18
    #1 0x70a373 in CCharacterCore::Tick(bool) /home/teeworlds/src/master/src/game/gamecore.cpp:274
    #2 0x510354 in CCharacter::Tick() /home/teeworlds/src/master/src/game/server/entities/character.cpp:772:9
    #3 0x5e828e in CGameWorld::Tick() /home/teeworlds/src/master/src/game/server/gameworld.cpp:261:11
    #4 0x58bb90 in CGameContext::OnTick() /home/teeworlds/src/master/src/game/server/gamecontext.cpp:751:10
    #5 0x4aeb9e in CServer::Run() /home/teeworlds/src/master/src/engine/server/server.cpp:2544:19
    #6 0x4c139d in main /home/teeworlds/src/master/src/engine/server/server.cpp:3537:21
    #7 0x7f1de53dd09a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)
    #8 0x4504f9 in _start (/home/teeworlds/servers/DDNet-Server-ubsan+0x4504f9)

/home/teeworlds/src/master/src/game/server/entities/dragger.cpp:112:14: runtime error: member access within address 0x00000132c7f8 which does not point to an object of type 'CEntity'
0x00000132c7f8: note: object has invalid vptr
 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              invalid vptr
    #0 0x54ed43 in CDragger::Drag() /home/teeworlds/src/master/src/game/server/entities/dragger.cpp:112:14
    #1 0x55084f in CDragger::Tick() /home/teeworlds/src/master/src/game/server/entities/dragger.cpp:155:2
    #2 0x5e828e in CGameWorld::Tick() /home/teeworlds/src/master/src/game/server/gameworld.cpp:261:11
    #3 0x58bb90 in CGameContext::OnTick() /home/teeworlds/src/master/src/game/server/gamecontext.cpp:751:10
    #4 0x4aeb9e in CServer::Run() /home/teeworlds/src/master/src/engine/server/server.cpp:2544:19
    #5 0x4c139d in main /home/teeworlds/src/master/src/engine/server/server.cpp:3537:21
    #6 0x7f1de53dd09a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)
    #7 0x4504f9 in _start (/home/teeworlds/servers/DDNet-Server-ubsan+0x4504f9)

/home/teeworlds/src/master/src/game/server/entities/dragger.cpp:32:29: runtime error: member call on address 0x00000132b840 which does not point to an object of type 'CCharacter'
0x00000132b840: note: object has invalid vptr
 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              invalid vptr
    #0 0x54e71e in CDragger::Move() /home/teeworlds/src/master/src/game/server/entities/dragger.cpp:32:29
    #1 0x550802 in CDragger::Tick() /home/teeworlds/src/master/src/game/server/entities/dragger.cpp:153:3
    #2 0x5e828e in CGameWorld::Tick() /home/teeworlds/src/master/src/game/server/gameworld.cpp:261:11
    #3 0x58bb90 in CGameContext::OnTick() /home/teeworlds/src/master/src/game/server/gamecontext.cpp:751:10
    #4 0x4aeb9e in CServer::Run() /home/teeworlds/src/master/src/engine/server/server.cpp:2544:19
    #5 0x4c139d in main /home/teeworlds/src/master/src/engine/server/server.cpp:3537:21
    #6 0x7f1de53dd09a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)
    #7 0x4504f9 in _start (/home/teeworlds/servers/DDNet-Server-ubsan+0x4504f9)

/home/teeworlds/src/master/src/game/server/entities/character.h:263:26: runtime error: member access within address 0x00000132b840 which does not point to an object of type 'CCharacter'
0x00000132b840: note: object has invalid vptr
 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              invalid vptr
    #0 0x545816 in CCharacter::IsAlive() /home/teeworlds/src/master/src/game/server/entities/character.h:263:26
    #1 0x54c371 in CDragger::Move() /home/teeworlds/src/master/src/game/server/entities/dragger.cpp:32:29
    #2 0x550802 in CDragger::Tick() /home/teeworlds/src/master/src/game/server/entities/dragger.cpp:153:3
    #3 0x5e828e in CGameWorld::Tick() /home/teeworlds/src/master/src/game/server/gameworld.cpp:261:11
    #4 0x58bb90 in CGameContext::OnTick() /home/teeworlds/src/master/src/game/server/gamecontext.cpp:751:10
    #5 0x4aeb9e in CServer::Run() /home/teeworlds/src/master/src/engine/server/server.cpp:2544:19
    #6 0x4c139d in main /home/teeworlds/src/master/src/engine/server/server.cpp:3537:21
    #7 0x7f1de53dd09a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)
    #8 0x4504f9 in _start (/home/teeworlds/servers/DDNet-Server-ubsan+0x4504f9)

/home/teeworlds/src/master/src/game/collision.cpp:1198:20: runtime error: division by zero
    #0 0x70668a in CCollision::IntersectNoLaser(vector2_base<float>, vector2_base<float>, vector2_base<float>*, vector2_base<float>*) /home/teeworlds/src/master/src/game/collision.cpp:1198:20
    #1 0x54dd13 in CDragger::Move() /home/teeworlds/src/master/src/game/server/entities/dragger.cpp:61:38
    #2 0x550802 in CDragger::Tick() /home/teeworlds/src/master/src/game/server/entities/dragger.cpp:153:3
    #3 0x5e828e in CGameWorld::Tick() /home/teeworlds/src/master/src/game/server/gameworld.cpp:261:11
    #4 0x58bb90 in CGameContext::OnTick() /home/teeworlds/src/master/src/game/server/gamecontext.cpp:751:10
    #5 0x4aeb9e in CServer::Run() /home/teeworlds/src/master/src/engine/server/server.cpp:2544:19
    #6 0x4c139d in main /home/teeworlds/src/master/src/engine/server/server.cpp:3537:21
    #7 0x7f1de53dd09a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)
    #8 0x4504f9 in _start (/home/teeworlds/servers/DDNet-Server-ubsan+0x4504f9)

/home/teeworlds/src/master/src/base/math.h:22:40: runtime error: -nan is outside the range of representable values of type 'int'
    #0 0x70670e in CCollision::IntersectNoLaser(vector2_base<float>, vector2_base<float>, vector2_base<float>*, vector2_base<float>*) /home/teeworlds/src/master/src/base/math.h
    #1 0x54dd13 in CDragger::Move() /home/teeworlds/src/master/src/game/server/entities/dragger.cpp:61:38
    #2 0x550802 in CDragger::Tick() /home/teeworlds/src/master/src/game/server/entities/dragger.cpp:153:3
    #3 0x5e828e in CGameWorld::Tick() /home/teeworlds/src/master/src/game/server/gameworld.cpp:261:11
    #4 0x58bb90 in CGameContext::OnTick() /home/teeworlds/src/master/src/game/server/gamecontext.cpp:751:10
    #5 0x4aeb9e in CServer::Run() /home/teeworlds/src/master/src/engine/server/server.cpp:2544:19
    #6 0x4c139d in main /home/teeworlds/src/master/src/engine/server/server.cpp:3537:21
    #7 0x7f1de53dd09a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)
    #8 0x4504f9 in _start (/home/teeworlds/servers/DDNet-Server-ubsan+0x4504f9)

/home/teeworlds/src/master/src/base/vmath.h:121:18: runtime error: division by zero
    #0 0x5e8e32 in vector2_base<float> closest_point_on_line<float>(vector2_base<float>, vector2_base<float>, vector2_base<float>) /home/teeworlds/src/master/src/base/vmath.h:121:18
    #1 0x5e8e32 in CGameWorld::IntersectCharacter(vector2_base<float>, vector2_base<float>, float, vector2_base<float>&, CCharacter*, int, CCharacter*) /home/teeworlds/src/master/src/game/server/gameworld.cpp:318
    #2 0x573105 in CProjectile::Tick() /home/teeworlds/src/master/src/game/server/entities/projectile.cpp:121:38
    #3 0x5e828e in CGameWorld::Tick() /home/teeworlds/src/master/src/game/server/gameworld.cpp:261:11
    #4 0x58bb90 in CGameContext::OnTick() /home/teeworlds/src/master/src/game/server/gamecontext.cpp:751:10
    #5 0x4aeb9e in CServer::Run() /home/teeworlds/src/master/src/engine/server/server.cpp:2544:19
    #6 0x4c139d in main /home/teeworlds/src/master/src/engine/server/server.cpp:3537:21
    #7 0x7f1de53dd09a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)
    #8 0x4504f9 in _start (/home/teeworlds/servers/DDNet-Server-ubsan+0x4504f9)

/home/teeworlds/src/master/src/game/server/entities/character.cpp:1429:32: runtime error: division by zero
    #0 0x5244d4 in CCharacter::HandleSkippableTiles(int) /home/teeworlds/src/master/src/game/server/entities/character.cpp:1429:32
    #1 0x513941 in CCharacter::DDRacePostCoreTick() /home/teeworlds/src/master/src/game/server/entities/character.cpp:2247:2
    #2 0x510433 in CCharacter::Tick() /home/teeworlds/src/master/src/game/server/entities/character.cpp:782:2
    #3 0x5e828e in CGameWorld::Tick() /home/teeworlds/src/master/src/game/server/gameworld.cpp:261:11
    #4 0x58bb90 in CGameContext::OnTick() /home/teeworlds/src/master/src/game/server/gamecontext.cpp:751:10
    #5 0x4aeb9e in CServer::Run() /home/teeworlds/src/master/src/engine/server/server.cpp:2544:19
    #6 0x4c139d in main /home/teeworlds/src/master/src/engine/server/server.cpp:3537:21
    #7 0x7f1de53dd09a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)
    #8 0x4504f9 in _start (/home/teeworlds/servers/DDNet-Server-ubsan+0x4504f9)

/home/teeworlds/src/master/src/game/server/entities/dragger.cpp:215:51: runtime error: member call on address 0x00000132c7f8 which does not point to an object of type 'CCharacter'
0x00000132c7f8: note: object has invalid vptr
 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              invalid vptr
    #0 0x551277 in CDragger::Snap(int) /home/teeworlds/src/master/src/game/server/entities/dragger.cpp:215:51
    #1 0x5e58d3 in CGameWorld::Snap(int) /home/teeworlds/src/master/src/game/server/gameworld.cpp:114:10
    #2 0x5cb105 in CGameContext::OnSnap(int) /home/teeworlds/src/master/src/game/server/gamecontext.cpp:3511:10
    #3 0x493dfe in CServer::DoSnapshot() /home/teeworlds/src/master/src/engine/server/server.cpp:856:18
    #4 0x4aeccd in CServer::Run() /home/teeworlds/src/master/src/engine/server/server.cpp:2555:6
    #5 0x4c139d in main /home/teeworlds/src/master/src/engine/server/server.cpp:3537:21
    #6 0x7f1de53dd09a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)
    #7 0x4504f9 in _start (/home/teeworlds/servers/DDNet-Server-ubsan+0x4504f9)

/home/teeworlds/src/master/src/game/server/entities/dragger.cpp:241:32: runtime error: member access within address 0x00000132c7f8 which does not point to an object of type 'CEntity'
0x00000132c7f8: note: object has invalid vptr
 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              invalid vptr
    #0 0x5512f0 in CDragger::Snap(int) /home/teeworlds/src/master/src/game/server/entities/dragger.cpp:241:32
    #1 0x5e58d3 in CGameWorld::Snap(int) /home/teeworlds/src/master/src/game/server/gameworld.cpp:114:10
    #2 0x5cb105 in CGameContext::OnSnap(int) /home/teeworlds/src/master/src/game/server/gamecontext.cpp:3511:10
    #3 0x493dfe in CServer::DoSnapshot() /home/teeworlds/src/master/src/engine/server/server.cpp:856:18
    #4 0x4aeccd in CServer::Run() /home/teeworlds/src/master/src/engine/server/server.cpp:2555:6
    #5 0x4c139d in main /home/teeworlds/src/master/src/engine/server/server.cpp:3537:21
    #6 0x7f1de53dd09a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)
    #7 0x4504f9 in _start (/home/teeworlds/servers/DDNet-Server-ubsan+0x4504f9)

/home/teeworlds/src/master/src/game/server/entities/dragger.cpp:242:32: runtime error: member access within address 0x00000132c7f8 which does not point to an object of type 'CEntity'
0x00000132c7f8: note: object has invalid vptr
 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              invalid vptr
    #0 0x551323 in CDragger::Snap(int) /home/teeworlds/src/master/src/game/server/entities/dragger.cpp:242:32
    #1 0x5e58d3 in CGameWorld::Snap(int) /home/teeworlds/src/master/src/game/server/gameworld.cpp:114:10
    #2 0x5cb105 in CGameContext::OnSnap(int) /home/teeworlds/src/master/src/game/server/gamecontext.cpp:3511:10
    #3 0x493dfe in CServer::DoSnapshot() /home/teeworlds/src/master/src/engine/server/server.cpp:856:18
    #4 0x4aeccd in CServer::Run() /home/teeworlds/src/master/src/engine/server/server.cpp:2555:6
    #5 0x4c139d in main /home/teeworlds/src/master/src/engine/server/server.cpp:3537:21
    #6 0x7f1de53dd09a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)
    #7 0x4504f9 in _start (/home/teeworlds/servers/DDNet-Server-ubsan+0x4504f9)

/home/teeworlds/src/master/src/game/server/entities/dragger.cpp:211:28: runtime error: member call on address 0x00000132c7f8 which does not point to an object of type 'CCharacter'
0x00000132c7f8: note: object has invalid vptr
 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00
              ^~~~~~~~~~~~~~~~~~~~~~~
              invalid vptr
    #0 0x550fbf in CDragger::Snap(int) /home/teeworlds/src/master/src/game/server/entities/dragger.cpp:211:28
    #1 0x5e58d3 in CGameWorld::Snap(int) /home/teeworlds/src/master/src/game/server/gameworld.cpp:114:10
    #2 0x5cb105 in CGameContext::OnSnap(int) /home/teeworlds/src/master/src/game/server/gamecontext.cpp:3511:10
    #3 0x493dfe in CServer::DoSnapshot() /home/teeworlds/src/master/src/engine/server/server.cpp:856:18
    #4 0x4aeccd in CServer::Run() /home/teeworlds/src/master/src/engine/server/server.cpp:2555:6
    #5 0x4c139d in main /home/teeworlds/src/master/src/engine/server/server.cpp:3537:21
    #6 0x7f1de53dd09a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)
    #7 0x4504f9 in _start (/home/teeworlds/servers/DDNet-Server-ubsan+0x4504f9)

/home/teeworlds/src/master/src/base/math.h:22:40: runtime error: -nan is outside the range of representable values of type 'int'
    #0 0x545fd6 in CCollision::GetCollisionAt(float, float) /home/teeworlds/src/master/src/base/math.h
    #1 0x7067ca in CCollision::IntersectNoLaser(vector2_base<float>, vector2_base<float>, vector2_base<float>*, vector2_base<float>*) /home/teeworlds/src/master/src/game/collision.cpp:1211:12
    #2 0x562be1 in CLight::Step() /home/teeworlds/src/master/src/game/server/entities/light.cpp:73:29
    #3 0x5623f3 in CLight::CLight(CGameWorld*, vector2_base<float>, float, int, int, int) /home/teeworlds/src/master/src/game/server/entities/light.cpp:21:2
    #4 0x5dc640 in IGameController::OnEntity(int, vector2_base<float>, int, int, int) /home/teeworlds/src/master/src/game/server/gamecontroller.cpp:282:23
    #5 0x5c81c7 in CGameContext::OnInit() /home/teeworlds/src/master/src/game/server/gamecontext.cpp:3281:21
    #6 0x4ad0ea in CServer::Run() /home/teeworlds/src/master/src/engine/server/server.cpp:2459:20
    #7 0x4c139d in main /home/teeworlds/src/master/src/engine/server/server.cpp:3537:21
    #8 0x7f1de53dd09a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)
    #9 0x4504f9 in _start (/home/teeworlds/servers/DDNet-Server-ubsan+0x4504f9)

/home/teeworlds/src/master/src/game/teamscore.h:40:10: runtime error: index -1 out of bounds for type 'bool const[64]'
    #0 0x54573f in CTeamsCore::GetSolo(int) const /home/teeworlds/src/master/src/game/teamscore.h:40:10
    #1 0x63505b in CGameTeams::TeamMask(int, int, int) /home/teeworlds/src/master/src/game/server/teams.cpp:390:16
    #2 0x5690bb in CPickup::Tick() /home/teeworlds/src/master/src/game/server/entities/pickup.cpp:101:77
    #3 0x5e828e in CGameWorld::Tick() /home/teeworlds/src/master/src/game/server/gameworld.cpp:261:11
    #4 0x58bb90 in CGameContext::OnTick() /home/teeworlds/src/master/src/game/server/gamecontext.cpp:751:10
    #5 0x4aeb9e in CServer::Run() /home/teeworlds/src/master/src/engine/server/server.cpp:2544:19
    #6 0x4c139d in main /home/teeworlds/src/master/src/engine/server/server.cpp:3537:21
    #7 0x7f1de53dd09a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)
    #8 0x4504f9 in _start (/home/teeworlds/servers/DDNet-Server-ubsan+0x4504f9)
```

**Comment by def-** [comment]
Some will be fixed by https://github.com/ddnet/ddnet/pull/3122

**Comment by def-** [comment]
https://github.com/ddnet/ddnet/pull/3247 and https://github.com/ddnet/ddnet/pull/3245 fix the more serious ones.

For now I don't care much about the "outside of the range", "signed integer overflow" & "division by zero" errors.
