### ISSUE TITLE
src/game/server/gamecontext.cpp:2743:11: runtime error: member access within misaligned address 0x63100001488e for type 'CVoteOptionServer', which requires 8 byte alignment

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3163]
```
src/game/server/gamecontext.cpp:2743:11: runtime error: member access within misaligned address 0x63100001488e for type 'CVoteOptionServer', which requires 8 byte alignment
0x63100001488e: note: pointer points here
 be be be be be be  be be be be be be be be  be be be be be be be be  be be be be be be be be  be be
             ^ 
    #0 0x55bf1f01812d in CGameContext::ConAddVote(IConsole::IResult*, void*) /media/ddnet/src/game/server/gamecontext.cpp:2743:11
    #1 0x55bf1eae27c8 in CConsole::ExecuteLineStroked(int, char const*, int, bool) /media/ddnet/src/engine/shared/console.cpp:501:8
    #2 0x55bf1eae3f24 in CConsole::ExecuteLine(char const*, int, bool) /media/ddnet/src/engine/shared/console.cpp:555:12
    #3 0x55bf1eae55f4 in CConsole::ExecuteFile(char const*, int, bool, int) /media/ddnet/src/engine/shared/console.cpp:600:4
    #4 0x55bf1edd29ae in main /media/ddnet/src/engine/server/server.cpp:3533:13
    #5 0x7ff5426b1151 in __libc_start_main (/usr/lib/libc.so.6+0x28151)
    #6 0x55bf1e9bb35d in _start (/media/ddnet/DDNet-Server+0x42d35d)
```

**Comment by Jupeyy** [comment]
should be fixed by #3854
