### ISSUE TITLE
Crash when > 60 players join

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3238]
Reported by HamidReza:

```
(gdb) bt
#0  GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff63f042a in GI_abort () at abort.c:89
#2  0x00007ffff642cc00 in __libc_message (do_abort=do_abort@entry=2, fmt=fmt@entry=0x7ffff6521fd0 " Error in `%s': %s: 0x%s \n")
    at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff6432fc6 in malloc_printerr (action=3, str=0x7ffff6522028 "munmap_chunk(): invalid pointer", ptr=<optimized out>, ar_ptr=<optimized out>)
    at malloc.c:5049
#4  0x00005555556a6786 in CSnapshotStorage::PurgeUntil (this=0x7ffff551ef78, Tick=7068) at /home/ddnet-master/src/engine/shared/snapshot.cpp:458
#5  0x00005555555d3c92 in CServer::DoSnapshot (this=0x7ffff53ee010) at /home/ddnet-master/src/engine/server/server.cpp:889
#6  0x00005555555db981 in CServer::Run (this=0x7ffff53ee010) at /home/ddnet-master/src/engine/server/server.cpp:2569
#7  0x00005555555e0a25 in main (argc=1, argv=0x7fffffffebe8) at /home/ddnet-master/src/engine/server/server.cpp:3551
```

**Comment by def-** [comment]
Anyone got good ideas? I haven't seen this on our servers.

**Comment by def-** [comment]
Oh, actually we had this before in #2677
