### ISSUE TITLE
Segfault when closing client while updater is downloading file

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3326]
```
Thread 3 "DDNet" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffeec21640 (LWP 360916)]
CUpdaterFetchTask::OnProgress (this=0x5555578ccc90) at src/engine/client/updater.cpp:54
54		lock_wait(m_pUpdater->m_Lock);
(gdb) bt
#0  CUpdaterFetchTask::OnProgress() (this=0x5555578ccc90) at src/engine/client/updater.cpp:54
#1  0x0000555555723cfa in CRequest::ProgressCallback(void*, double, double, double, double)
    (pUser=0x5555578ccc90, DlTotal=0, DlCurr=2112, UlTotal=0, UlCurr=0) at src/engine/client/http.cpp:173
#2  0x00007ffff7c1ac35 in  () at /usr/lib/libcurl.so.4
#3  0x00007ffff7c30946 in  () at /usr/lib/libcurl.so.4
#4  0x00007ffff7c15405 in  () at /usr/lib/libcurl.so.4
#5  0x00007ffff7c168c6 in curl_multi_perform () at /usr/lib/libcurl.so.4
#6  0x00007ffff7beca6c in curl_easy_perform () at /usr/lib/libcurl.so.4
#7  0x0000555555723b18 in CRequest::RunImpl(void*) (this=0x5555578ccc90, pHandle=0x7fffe01e8400)
    at src/engine/client/http.cpp:147
#8  0x000055555572378c in CRequest::Run() (this=0x5555578ccc90) at src/engine/client/http.cpp:99
#9  0x000055555568ca1f in CJobPool::WorkerThread(void*) (pUser=0x555555b96aa0) at src/engine/shared/jobs.cpp:79
#10 0x00005555556ad4de in thread_run (user=0x555555b7eea0) at src/base/system.c:694
#11 0x00007ffff7c723e9 in start_thread () at /usr/lib/libpthread.so.0
#12 0x00007ffff50ce293 in clone () at /usr/lib/libc.so.6
```
@Learath2 want to take a look or should I?

**Comment by Learath2** [comment]
Is this really something you want fixed with #2754 coming up? It fixes a lot of the multithreading issues in the updater.

Though I guess since I'm being very slow with that one, we might want to fix this separately.

**Comment by def-** [comment]
Nope, it's fine if #2754 fixes this

**Comment by def-** [comment]
Fixed by #7683
