### ISSUE TITLE
client suddenly takes 100% cpu and starts lagging

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3379]
No idea why, restarting client and using timeout protection makes it happen again.

```
(gdb) thread apply all bt

Thread 11 (Thread 0x7f2f2f405640 (LWP 373309) "SDLAudioP2"):
#0  0x00007f2f62fbb56e in ppoll () at /usr/lib/libc.so.6
#1  0x00005606a28040d3 in ppoll ()
#2  0x00007f2f4f784a33 in pa_mainloop_poll () at /usr/lib/libpulse.so.0
#3  0x00007f2f4f78f281 in pa_mainloop_iterate () at /usr/lib/libpulse.so.0
#4  0x00007f2f63ab7ac7 in  () at /usr/lib/libSDL2-2.0.so.0
#5  0x00007f2f639fc1d6 in  () at /usr/lib/libSDL2-2.0.so.0
#6  0x00007f2f63a55cff in  () at /usr/lib/libSDL2-2.0.so.0
#7  0x00007f2f63ae96aa in  () at /usr/lib/libSDL2-2.0.so.0
#8  0x00007f2f630ba3e9 in start_thread () at /usr/lib/libpthread.so.0
#9  0x00007f2f62fc6293 in clone () at /usr/lib/libc.so.6

Thread 10 (Thread 0x7f2f3f446640 (LWP 373308) "PulseHotplug"):
#0  0x00007f2f62fbb56e in ppoll () at /usr/lib/libc.so.6
#1  0x00005606a28040d3 in ppoll ()
#2  0x00007f2f4f784a33 in pa_mainloop_poll () at /usr/lib/libpulse.so.0
#3  0x00007f2f4f78f281 in pa_mainloop_iterate () at /usr/lib/libpulse.so.0
#4  0x00007f2f4f78f331 in pa_mainloop_run () at /usr/lib/libpulse.so.0
#5  0x00007f2f63ab7dd0 in  () at /usr/lib/libSDL2-2.0.so.0
#6  0x00007f2f63a55cff in  () at /usr/lib/libSDL2-2.0.so.0
#7  0x00007f2f63ae96aa in  () at /usr/lib/libSDL2-2.0.so.0
#8  0x00007f2f630ba3e9 in start_thread () at /usr/lib/libpthread.so.0
#9  0x00007f2f62fc6293 in clone () at /usr/lib/libc.so.6

Thread 9 (Thread 0x7f2f507d4640 (LWP 373307) "DDNet"):
#0  0x00007f2f630c3014 in do_futex_wait.constprop () at /usr/lib/libpthread.so.0
#1  0x00007f2f630c3118 in __new_sem_wait_slow.constprop.0 () at /usr/lib/libpthread.so.0
#2  0x00005606a2abf553 in sphore_wait (sem=0x614000000260) at src/base/system.c:901
#3  0x00005606a2c2c412 in CSemaphore::Wait() (this=0x614000000260) at src/base/tl/threading.h:14
#4  0x00005606a2b5b259 in CGraphicsBackend_Threaded::ThreadFunc(void*) (pUser=0x614000000240) at src/engine/client/backend_sdl.cpp:74
#5  0x00005606a2abf182 in thread_run (user=0x602000070730) at src/base/system.c:694
#6  0x00007f2f630ba3e9 in start_thread () at /usr/lib/libpthread.so.0
#7  0x00007f2f62fc6293 in clone () at /usr/lib/libc.so.6

Thread 8 (Thread 0x7f2f51c78640 (LWP 373306) "DDNet:disk$3"):
#0  0x00007f2f630c06a2 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f2f5b4e2eac in  () at /usr/lib/dri/iris_dri.so
#2  0x00007f2f5b4e2da8 in  () at /usr/lib/dri/iris_dri.so
#3  0x00007f2f630ba3e9 in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007f2f62fc6293 in clone () at /usr/lib/libc.so.6

Thread 7 (Thread 0x7f2f52481640 (LWP 373305) "DDNet:disk$2"):
#0  0x00007f2f630c06a2 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f2f5b4e2eac in  () at /usr/lib/dri/iris_dri.so
#2  0x00007f2f5b4e2da8 in  () at /usr/lib/dri/iris_dri.so
#3  0x00007f2f630ba3e9 in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007f2f62fc6293 in clone () at /usr/lib/libc.so.6

Thread 6 (Thread 0x7f2f52c82640 (LWP 373304) "DDNet:disk$1"):
#0  0x00007f2f630c06a2 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f2f5b4e2eac in  () at /usr/lib/dri/iris_dri.so
#2  0x00007f2f5b4e2da8 in  () at /usr/lib/dri/iris_dri.so
#3  0x00007f2f630ba3e9 in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007f2f62fc6293 in clone () at /usr/lib/libc.so.6

Thread 5 (Thread 0x7f2f53483640 (LWP 373303) "DDNet:disk$0"):
#0  0x00007f2f630c06a2 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f2f5b4e2eac in  () at /usr/lib/dri/iris_dri.so
#2  0x00007f2f5b4e2da8 in  () at /usr/lib/dri/iris_dri.so
#3  0x00007f2f630ba3e9 in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007f2f62fc6293 in clone () at /usr/lib/libc.so.6

Thread 4 (Thread 0x7f2f5da87640 (LWP 373302) "DDNet"):
#0  0x00007f2f630c3014 in do_futex_wait.constprop () at /usr/lib/libpthread.so.0
#1  0x00007f2f630c3118 in __new_sem_wait_slow.constprop.0 () at /usr/lib/libpthread.so.0
#2  0x00005606a2abf553 in sphore_wait (sem=0x608000001bb0) at src/base/system.c:901
#3  0x00005606a2ab91bc in aio_thread (user=0x608000001ba0) at src/base/system.c:453
#4  0x00005606a2abf182 in thread_run (user=0x602000005890) at src/base/system.c:694
#5  0x00007f2f630ba3e9 in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007f2f62fc6293 in clone () at /usr/lib/libc.so.6

Thread 3 (Thread 0x7f2f5e288640 (LWP 373301) "DDNet"):
#0  0x00007f2f630c3014 in do_futex_wait.constprop () at /usr/lib/libpthread.so.0
#1  0x00007f2f630c3118 in __new_sem_wait_slow.constprop.0 () at /usr/lib/libpthread.so.0
#2  0x00005606a2abf553 in sphore_wait (sem=0x613000000328) at src/base/system.c:901
#3  0x00005606a29e5e7d in CJobPool::WorkerThread(void*) (pUser=0x613000000210) at src/engine/shared/jobs.cpp:64
#4  0x00005606a2abf182 in thread_run (user=0x602000001050) at src/base/system.c:694
#5  0x00007f2f630ba3e9 in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007f2f62fc6293 in clone () at /usr/lib/libc.so.6

Thread 2 (Thread 0x7f2f5ea89640 (LWP 373300) "DDNet"):
#0  0x00007f2f630c3014 in do_futex_wait.constprop () at /usr/lib/libpthread.so.0
--Type <RET> for more, q to quit, c to continue without paging--
#1  0x00007f2f630c3118 in __new_sem_wait_slow.constprop.0 () at /usr/lib/libpthread.so.0
#2  0x00005606a2abf553 in sphore_wait (sem=0x608000001ab0) at src/base/system.c:901
#3  0x00005606a2ab91bc in aio_thread (user=0x608000001aa0) at src/base/system.c:453
#4  0x00005606a2abf182 in thread_run (user=0x602000000ff0) at src/base/system.c:694
#5  0x00007f2f630ba3e9 in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007f2f62fc6293 in clone () at /usr/lib/libc.so.6

Thread 1 (Thread 0x7f2f625ff800 (LWP 373299) "DDNet"):
#0  0x00005606a2a7043e in CSnapshotItem::Type() (this=0x62a0006c94b8) at src/engine/shared/snapshot.h:16
#1  0x00005606a2a620fc in CSnapshot::GetItemType(int) (this=0x62a0006c8f38, Index=2) at src/engine/shared/snapshot.cpp:26
#2  0x00005606a2c8be34 in CClient::SnapFindItem(int, int, int) (this=0x7f2f5ea8b800, SnapID=0, Type=10, ID=3) at src/engine/client/client.cpp:963
#3  0x00005606a349885a in CPlayers::OnRender() (this=0x5606a4d94340 <gs_Players>) at src/game/client/components/players.cpp:701
#4  0x00005606a35c211a in CGameClient::OnRender() (this=0x5606a4bcac00 <g_GameClient>) at src/game/client/gameclient.cpp:676
#5  0x00005606a2c939c4 in CClient::Render() (this=0x7f2f5ea8b800) at src/engine/client/client.cpp:1136
#6  0x00005606a2ce91fa in CClient::Run() (this=0x7f2f5ea8b800) at src/engine/client/client.cpp:3305
#7  0x00005606a2d1aca5 in main(int, char const**) (argc=3, argv=0x7fffecd1c258) at src/engine/client/client.cpp:4387
(gdb) c
Continuing.
^C
Thread 1 "DDNet" received signal SIGINT, Interrupt.
0x00005606a2a83bb7 in find_binary<plain_range_sorted<CNameIndexed>, CUuid> (range=..., value=...)
    at src/base/tl/algorithm.h:70
warning: Source file is more recent than executable.
70	{
(gdb) thread apply all bt

Thread 11 (Thread 0x7f2f2f405640 (LWP 373309) "SDLAudioP2"):
#0  0x00007f2f62fbb56e in ppoll () at /usr/lib/libc.so.6
#1  0x00005606a28040d3 in ppoll ()
#2  0x00007f2f4f784a33 in pa_mainloop_poll () at /usr/lib/libpulse.so.0
#3  0x00007f2f4f78f281 in pa_mainloop_iterate () at /usr/lib/libpulse.so.0
#4  0x00007f2f63ab7ac7 in  () at /usr/lib/libSDL2-2.0.so.0
#5  0x00007f2f639fc1d6 in  () at /usr/lib/libSDL2-2.0.so.0
#6  0x00007f2f63a55cff in  () at /usr/lib/libSDL2-2.0.so.0
#7  0x00007f2f63ae96aa in  () at /usr/lib/libSDL2-2.0.so.0
#8  0x00007f2f630ba3e9 in start_thread () at /usr/lib/libpthread.so.0
#9  0x00007f2f62fc6293 in clone () at /usr/lib/libc.so.6

Thread 10 (Thread 0x7f2f3f446640 (LWP 373308) "PulseHotplug"):
#0  0x00007f2f62fbb56e in ppoll () at /usr/lib/libc.so.6
#1  0x00005606a28040d3 in ppoll ()
#2  0x00007f2f4f784a33 in pa_mainloop_poll () at /usr/lib/libpulse.so.0
#3  0x00007f2f4f78f281 in pa_mainloop_iterate () at /usr/lib/libpulse.so.0
#4  0x00007f2f4f78f331 in pa_mainloop_run () at /usr/lib/libpulse.so.0
#5  0x00007f2f63ab7dd0 in  () at /usr/lib/libSDL2-2.0.so.0
#6  0x00007f2f63a55cff in  () at /usr/lib/libSDL2-2.0.so.0
#7  0x00007f2f63ae96aa in  () at /usr/lib/libSDL2-2.0.so.0
#8  0x00007f2f630ba3e9 in start_thread () at /usr/lib/libpthread.so.0
#9  0x00007f2f62fc6293 in clone () at /usr/lib/libc.so.6

Thread 9 (Thread 0x7f2f507d4640 (LWP 373307) "DDNet"):
#0  0x00007f2f630c3014 in do_futex_wait.constprop () at /usr/lib/libpthread.so.0
#1  0x00007f2f630c3118 in __new_sem_wait_slow.constprop.0 () at /usr/lib/libpthread.so.0
#2  0x00005606a2abf553 in sphore_wait (sem=0x614000000260) at src/base/system.c:901
#3  0x00005606a2c2c412 in CSemaphore::Wait() (this=0x614000000260) at src/base/tl/threading.h:14
#4  0x00005606a2b5b259 in CGraphicsBackend_Threaded::ThreadFunc(void*) (pUser=0x614000000240) at src/engine/client/backend_sdl.cpp:74
#5  0x00005606a2abf182 in thread_run (user=0x602000070730) at src/base/system.c:694
#6  0x00007f2f630ba3e9 in start_thread () at /usr/lib/libpthread.so.0
#7  0x00007f2f62fc6293 in clone () at /usr/lib/libc.so.6

Thread 8 (Thread 0x7f2f51c78640 (LWP 373306) "DDNet:disk$3"):
#0  0x00007f2f630c06a2 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f2f5b4e2eac in  () at /usr/lib/dri/iris_dri.so
#2  0x00007f2f5b4e2da8 in  () at /usr/lib/dri/iris_dri.so
#3  0x00007f2f630ba3e9 in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007f2f62fc6293 in clone () at /usr/lib/libc.so.6

Thread 7 (Thread 0x7f2f52481640 (LWP 373305) "DDNet:disk$2"):
#0  0x00007f2f630c06a2 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f2f5b4e2eac in  () at /usr/lib/dri/iris_dri.so
#2  0x00007f2f5b4e2da8 in  () at /usr/lib/dri/iris_dri.so
#3  0x00007f2f630ba3e9 in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007f2f62fc6293 in clone () at /usr/lib/libc.so.6

Thread 6 (Thread 0x7f2f52c82640 (LWP 373304) "DDNet:disk$1"):
#0  0x00007f2f630c06a2 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f2f5b4e2eac in  () at /usr/lib/dri/iris_dri.so
#2  0x00007f2f5b4e2da8 in  () at /usr/lib/dri/iris_dri.so
#3  0x00007f2f630ba3e9 in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007f2f62fc6293 in clone () at /usr/lib/libc.so.6

Thread 5 (Thread 0x7f2f53483640 (LWP 373303) "DDNet:disk$0"):
#0  0x00007f2f630c06a2 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f2f5b4e2eac in  () at /usr/lib/dri/iris_dri.so
#2  0x00007f2f5b4e2da8 in  () at /usr/lib/dri/iris_dri.so
#3  0x00007f2f630ba3e9 in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007f2f62fc6293 in clone () at /usr/lib/libc.so.6

Thread 4 (Thread 0x7f2f5da87640 (LWP 373302) "DDNet"):
#0  0x00007f2f630c3014 in do_futex_wait.constprop () at /usr/lib/libpthread.so.0
#1  0x00007f2f630c3118 in __new_sem_wait_slow.constprop.0 () at /usr/lib/libpthread.so.0
#2  0x00005606a2abf553 in sphore_wait (sem=0x608000001bb0) at src/base/system.c:901
#3  0x00005606a2ab91bc in aio_thread (user=0x608000001ba0) at src/base/system.c:453
#4  0x00005606a2abf182 in thread_run (user=0x602000005890) at src/base/system.c:694
#5  0x00007f2f630ba3e9 in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007f2f62fc6293 in clone () at /usr/lib/libc.so.6

Thread 3 (Thread 0x7f2f5e288640 (LWP 373301) "DDNet"):
#0  0x00007f2f630c3014 in do_futex_wait.constprop () at /usr/lib/libpthread.so.0
#1  0x00007f2f630c3118 in __new_sem_wait_slow.constprop.0 () at /usr/lib/libpthread.so.0
#2  0x00005606a2abf553 in sphore_wait (sem=0x613000000328) at src/base/system.c:901
#3  0x00005606a29e5e7d in CJobPool::WorkerThread(void*) (pUser=0x613000000210) at src/engine/shared/jobs.cpp:64
#4  0x00005606a2abf182 in thread_run (user=0x602000001050) at src/base/system.c:694
#5  0x00007f2f630ba3e9 in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007f2f62fc6293 in clone () at /usr/lib/libc.so.6

Thread 2 (Thread 0x7f2f5ea89640 (LWP 373300) "DDNet"):
#0  0x00007f2f630c3014 in do_futex_wait.constprop () at /usr/lib/libpthread.so.0
--Type <RET> for more, q to quit, c to continue without paging--
#1  0x00007f2f630c3118 in __new_sem_wait_slow.constprop.0 () at /usr/lib/libpthread.so.0
#2  0x00005606a2abf553 in sphore_wait (sem=0x608000001ab0) at src/base/system.c:901
#3  0x00005606a2ab91bc in aio_thread (user=0x608000001aa0) at src/base/system.c:453
#4  0x00005606a2abf182 in thread_run (user=0x602000000ff0) at src/base/system.c:694
#5  0x00007f2f630ba3e9 in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007f2f62fc6293 in clone () at /usr/lib/libc.so.6

Thread 1 (Thread 0x7f2f625ff800 (LWP 373299) "DDNet"):
#0  0x00005606a2a83bb7 in find_binary<plain_range_sorted<CNameIndexed>, CUuid>(plain_range_sorted<CNameIndexed>, CUuid) (range=..., value=...) at src/base/tl/algorithm.h:70
#1  0x00005606a2a81762 in CUuidManager::LookupUuid(CUuid) const (this=0x5606a4b7c7a0 <g_UuidManager>, Uuid=...) at src/engine/shared/uuid_manager.cpp:112
#2  0x00005606a2a6319c in CSnapshot::GetItemType(int) (this=0x62a000a88f38, Index=291) at src/engine/shared/snapshot.cpp:48
#3  0x00005606a2c8be34 in CClient::SnapFindItem(int, int, int) (this=0x7f2f5ea8b800, SnapID=0, Type=10, ID=29) at src/engine/client/client.cpp:963
#4  0x00005606a349885a in CPlayers::OnRender() (this=0x5606a4d94340 <gs_Players>) at src/game/client/components/players.cpp:701
#5  0x00005606a35c211a in CGameClient::OnRender() (this=0x5606a4bcac00 <g_GameClient>) at src/game/client/gameclient.cpp:676
#6  0x00005606a2c939c4 in CClient::Render() (this=0x7f2f5ea8b800) at src/engine/client/client.cpp:1136
#7  0x00005606a2ce91fa in CClient::Run() (this=0x7f2f5ea8b800) at src/engine/client/client.cpp:3305
#8  0x00005606a2d1aca5 in main(int, char const**) (argc=3, argv=0x7fffecd1c258) at src/engine/client/client.cpp:4387
(gdb) c
Continuing.
^C
Thread 1 "DDNet" received signal SIGINT, Interrupt.
0x00005606a2b1dae4 in vector2_base<float>::operator- (this=0x7fffecd124e0, v=...) at src/base/vmath.h:33
warning: Source file is more recent than executable.
33		vector2_base operator-(const vector2_base &v) const { return vector2_base(x - v.x, y - v.y); }
(gdb) thread apply all bt

Thread 11 (Thread 0x7f2f2f405640 (LWP 373309) "SDLAudioP2"):
#0  0x00007f2f62fbb56e in ppoll () at /usr/lib/libc.so.6
#1  0x00005606a28040d3 in ppoll ()
#2  0x00007f2f4f784a33 in pa_mainloop_poll () at /usr/lib/libpulse.so.0
#3  0x00007f2f4f78f281 in pa_mainloop_iterate () at /usr/lib/libpulse.so.0
#4  0x00007f2f63ab7ac7 in  () at /usr/lib/libSDL2-2.0.so.0
#5  0x00007f2f639fc1d6 in  () at /usr/lib/libSDL2-2.0.so.0
#6  0x00007f2f63a55cff in  () at /usr/lib/libSDL2-2.0.so.0
#7  0x00007f2f63ae96aa in  () at /usr/lib/libSDL2-2.0.so.0
#8  0x00007f2f630ba3e9 in start_thread () at /usr/lib/libpthread.so.0
#9  0x00007f2f62fc6293 in clone () at /usr/lib/libc.so.6

Thread 10 (Thread 0x7f2f3f446640 (LWP 373308) "PulseHotplug"):
#0  0x00007f2f62fbb56e in ppoll () at /usr/lib/libc.so.6
#1  0x00005606a28040d3 in ppoll ()
#2  0x00007f2f4f784a33 in pa_mainloop_poll () at /usr/lib/libpulse.so.0
#3  0x00007f2f4f78f281 in pa_mainloop_iterate () at /usr/lib/libpulse.so.0
#4  0x00007f2f4f78f331 in pa_mainloop_run () at /usr/lib/libpulse.so.0
#5  0x00007f2f63ab7dd0 in  () at /usr/lib/libSDL2-2.0.so.0
#6  0x00007f2f63a55cff in  () at /usr/lib/libSDL2-2.0.so.0
#7  0x00007f2f63ae96aa in  () at /usr/lib/libSDL2-2.0.so.0
#8  0x00007f2f630ba3e9 in start_thread () at /usr/lib/libpthread.so.0
#9  0x00007f2f62fc6293 in clone () at /usr/lib/libc.so.6

Thread 9 (Thread 0x7f2f507d4640 (LWP 373307) "DDNet"):
#0  0x00007f2f630c3014 in do_futex_wait.constprop () at /usr/lib/libpthread.so.0
#1  0x00007f2f630c3118 in __new_sem_wait_slow.constprop.0 () at /usr/lib/libpthread.so.0
#2  0x00005606a2abf553 in sphore_wait (sem=0x614000000260) at src/base/system.c:901
#3  0x00005606a2c2c412 in CSemaphore::Wait() (this=0x614000000260) at src/base/tl/threading.h:14
#4  0x00005606a2b5b259 in CGraphicsBackend_Threaded::ThreadFunc(void*) (pUser=0x614000000240) at src/engine/client/backend_sdl.cpp:74
#5  0x00005606a2abf182 in thread_run (user=0x602000070730) at src/base/system.c:694
#6  0x00007f2f630ba3e9 in start_thread () at /usr/lib/libpthread.so.0
#7  0x00007f2f62fc6293 in clone () at /usr/lib/libc.so.6

Thread 8 (Thread 0x7f2f51c78640 (LWP 373306) "DDNet:disk$3"):
#0  0x00007f2f630c06a2 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f2f5b4e2eac in  () at /usr/lib/dri/iris_dri.so
#2  0x00007f2f5b4e2da8 in  () at /usr/lib/dri/iris_dri.so
#3  0x00007f2f630ba3e9 in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007f2f62fc6293 in clone () at /usr/lib/libc.so.6

Thread 7 (Thread 0x7f2f52481640 (LWP 373305) "DDNet:disk$2"):
#0  0x00007f2f630c06a2 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f2f5b4e2eac in  () at /usr/lib/dri/iris_dri.so
#2  0x00007f2f5b4e2da8 in  () at /usr/lib/dri/iris_dri.so
#3  0x00007f2f630ba3e9 in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007f2f62fc6293 in clone () at /usr/lib/libc.so.6

Thread 6 (Thread 0x7f2f52c82640 (LWP 373304) "DDNet:disk$1"):
#0  0x00007f2f630c06a2 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f2f5b4e2eac in  () at /usr/lib/dri/iris_dri.so
#2  0x00007f2f5b4e2da8 in  () at /usr/lib/dri/iris_dri.so
#3  0x00007f2f630ba3e9 in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007f2f62fc6293 in clone () at /usr/lib/libc.so.6

Thread 5 (Thread 0x7f2f53483640 (LWP 373303) "DDNet:disk$0"):
#0  0x00007f2f630c06a2 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007f2f5b4e2eac in  () at /usr/lib/dri/iris_dri.so
#2  0x00007f2f5b4e2da8 in  () at /usr/lib/dri/iris_dri.so
#3  0x00007f2f630ba3e9 in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007f2f62fc6293 in clone () at /usr/lib/libc.so.6

Thread 4 (Thread 0x7f2f5da87640 (LWP 373302) "DDNet"):
#0  0x00007f2f630c3014 in do_futex_wait.constprop () at /usr/lib/libpthread.so.0
#1  0x00007f2f630c3118 in __new_sem_wait_slow.constprop.0 () at /usr/lib/libpthread.so.0
#2  0x00005606a2abf553 in sphore_wait (sem=0x608000001bb0) at src/base/system.c:901
#3  0x00005606a2ab91bc in aio_thread (user=0x608000001ba0) at src/base/system.c:453
#4  0x00005606a2abf182 in thread_run (user=0x602000005890) at src/base/system.c:694
#5  0x00007f2f630ba3e9 in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007f2f62fc6293 in clone () at /usr/lib/libc.so.6

Thread 3 (Thread 0x7f2f5e288640 (LWP 373301) "DDNet"):
#0  0x00007f2f630c3014 in do_futex_wait.constprop () at /usr/lib/libpthread.so.0
#1  0x00007f2f630c3118 in __new_sem_wait_slow.constprop.0 () at /usr/lib/libpthread.so.0
#2  0x00005606a2abf553 in sphore_wait (sem=0x613000000328) at src/base/system.c:901
#3  0x00005606a29e5e7d in CJobPool::WorkerThread(void*) (pUser=0x613000000210) at src/engine/shared/jobs.cpp:64
#4  0x00005606a2abf182 in thread_run (user=0x602000001050) at src/base/system.c:694
#5  0x00007f2f630ba3e9 in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007f2f62fc6293 in clone () at /usr/lib/libc.so.6

Thread 2 (Thread 0x7f2f5ea89640 (LWP 373300) "DDNet"):
#0  0x00007f2f630c3014 in do_futex_wait.constprop () at /usr/lib/libpthread.so.0
--Type <RET> for more, q to quit, c to continue without paging--
#1  0x00007f2f630c3118 in __new_sem_wait_slow.constprop.0 () at /usr/lib/libpthread.so.0
#2  0x00005606a2abf553 in sphore_wait (sem=0x608000001ab0) at src/base/system.c:901
#3  0x00005606a2ab91bc in aio_thread (user=0x608000001aa0) at src/base/system.c:453
#4  0x00005606a2abf182 in thread_run (user=0x602000000ff0) at src/base/system.c:694
#5  0x00007f2f630ba3e9 in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007f2f62fc6293 in clone () at /usr/lib/libc.so.6

Thread 1 (Thread 0x7f2f625ff800 (LWP 373299) "DDNet"):
#0  0x00005606a2b1dae4 in vector2_base<float>::operator-(vector2_base<float> const&) const (this=0x7fffecd124e0, v=...) at src/base/vmath.h:33
#1  0x00005606a2b1b970 in distance<float>(vector2_base<float>, vector2_base<float> const&) (a=..., b=...) at src/base/vmath.h:92
#2  0x00005606a36ccbb8 in CGameWorld::FindEntities(vector2_base<float>, float, CEntity**, int, int) (this=0x5606a4c0e210 <g_GameClient+275984>, Pos=..., Radius=20, ppEnts=0x7fffecd128c0, Max=64, Type=4) at src/game/client/prediction/gameworld.cpp:66
#3  0x00005606a36b0330 in CPickup::Tick() (this=0x60b002c5c500) at src/game/client/prediction/entities/pickup.cpp:12
#4  0x00005606a36d3a86 in CGameWorld::Tick() (this=0x5606a4c0e210 <g_GameClient+275984>) at src/game/client/prediction/gameworld.cpp:193
#5  0x00005606a3612299 in CGameClient::OnPredict() (this=0x5606a4bcac00 <g_GameClient>) at src/game/client/gameclient.cpp:1765
#6  0x00005606a2cd3c90 in CClient::Update() (this=0x7f2f5ea8b800) at src/engine/client/client.cpp:2816
#7  0x00005606a2ce5d93 in CClient::Run() (this=0x7f2f5ea8b800) at src/engine/client/client.cpp:3244
#8  0x00005606a2d1aca5 in main(int, char const**) (argc=3, argv=0x7fffecd1c258) at src/engine/client/client.cpp:4387
(gdb) c
```

**Comment by def-** [comment]
Main thread (LWP 373299) is using all the CPU, not the graphics thread.

**Comment by Learath2** [comment]
Next time you get it to happen, instead of sampling like this, it’d be much
better if you could profile with perf. It seems to be the best way to
profile and it can attach to a running process.

**Comment by def-** [comment]
Can't reproduce anymore
