### ISSUE TITLE
AddressSanitizer: heap-buffer-overflow in CSaveTee::GetString(CSaveTeam const*) /home/teeworlds/src/master/src/game/server/save.cpp:226:2

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3380]
```
=================================================================
==6708==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61e00008e66c at pc 0x0000004707fe bp 0x7ffddeb49720 sp 0x7ffddeb48e98
READ of size 41 at 0x61e00008e66c thread T0 
    #0 0x4707fd in printf_common(void*, char const*, __va_list_tag*) (/home/teeworlds/servers/DDNet-Server-asan+0x4707fd)
    #1 0x470d3c in __vsnprintf_chk (/home/teeworlds/servers/DDNet-Server-asan+0x470d3c)
    #2 0x722f76 in vsnprintf /usr/include/x86_64-linux-gnu/bits/stdio2.h:80:10
    #3 0x722f76 in str_format /home/teeworlds/src/master/src/base/system.c:2396
    #4 0x6333aa in CSaveTee::GetString(CSaveTeam const*) /home/teeworlds/src/master/src/game/server/save.cpp:226:2
    #5 0x6385f4 in CSaveTeam::GetString() /home/teeworlds/src/master/src/game/server/save.cpp:542:58
    #6 0x660383 in CGameTeams::ProcessSaveTeam() /home/teeworlds/src/master/src/game/server/teams.cpp:723:43
    #7 0x610652 in CGameControllerDDRace::Tick() /home/teeworlds/src/master/src/game/server/gamemodes/DDRace.cpp:28:10
    #8 0x5d5223 in CGameContext::OnTick() /home/teeworlds/src/master/src/game/server/gamecontext.cpp:754:17
    #9 0x55f92e in CServer::Run() /home/teeworlds/src/master/src/engine/server/server.cpp:2571:19
    #10 0x56b8d2 in main /home/teeworlds/src/master/src/engine/server/server.cpp:3560:21
    #11 0x7f9512bdd09a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)
    #12 0x44aa99 in _start (/home/teeworlds/servers/DDNet-Server-asan+0x44aa99)

0x61e00008e66c is located 0 bytes to the right of 2540-byte region [0x61e00008dc80,0x61e00008e66c)
allocated by thread T1 here:
    #0 0x521cb2 in operator new[](unsigned long) (/home/teeworlds/servers/DDNet-Server-asan+0x521cb2)
    #1 0x638ce4 in CSaveTeam::FromString(char const*) /home/teeworlds/src/master/src/game/server/save.cpp:619:18
    #2 0x65027e in CScore::LoadTeamThread(IDbConnection*, ISqlData const*, bool) /home/teeworlds/src/master/src/game/server/score.cpp:1485:43
    #3 0x52b40d in CDbConnectionPool::ExecSqlFunc(IDbConnection*, CSqlExecData*, bool) /home/teeworlds/src/master/src/engine/server/databases/connection_pool.cpp:216:7
    #4 0x52ae5c in CDbConnectionPool::Worker() /home/teeworlds/src/master/src/engine/server/databases/connection_pool.cpp:174:8
    #5 0x529dd9 in CDbConnectionPool::Worker(void*) /home/teeworlds/src/master/src/engine/server/databases/connection_pool.cpp:132:9
    #6 0x725b5f in thread_run /home/teeworlds/src/master/src/base/system.c:694:2
    #7 0x7f9512da2fa2 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x7fa2)

Thread T1 created by T0 here:
    #0 0x4db1fd in pthread_create (/home/teeworlds/servers/DDNet-Server-asan+0x4db1fd)
    #1 0x725d91 in thread_init /home/teeworlds/src/master/src/base/system.c:706:16
    #2 0x725d91 in thread_init_and_detach /home/teeworlds/src/master/src/base/system.c:777
    #3 0x52997a in CDbConnectionPool::CDbConnectionPool() /home/teeworlds/src/master/src/engine/server/databases/connection_pool.cpp:65:2
    #4 0x54527a in CServer::CServer() /home/teeworlds/src/master/src/engine/server/server.cpp:325:26
    #5 0x56b0e5 in CreateServer() /home/teeworlds/src/master/src/engine/server/server.cpp:3467:45
    #6 0x56b0e5 in main /home/teeworlds/src/master/src/engine/server/server.cpp:3491
    #7 0x7f9512bdd09a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)

SUMMARY: AddressSanitizer: heap-buffer-overflow (/home/teeworlds/servers/DDNet-Server-asan+0x4707fd) in printf_common(void*, char const*, __va_list_tag*)
Shadow bytes around the buggy address:
  0x0c3c80009c70: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
  0x0c3c80009c80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
  0x0c3c80009c90: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
  0x0c3c80009ca0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
  0x0c3c80009cb0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
=>0x0c3c80009cc0: 00 00 00 00 00 00 00 00 00 00 00 00 00[04]fa fa 
  0x0c3c80009cd0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa 
  0x0c3c80009ce0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa 
  0x0c3c80009cf0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa 
  0x0c3c80009d00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa 
  0x0c3c80009d10: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd 
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00 
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa 
  Freed heap region:       fd 
  Stack left redzone:      f1 
  Stack mid redzone:       f2 
  Stack right redzone:     f3 
  Stack after return:      f5 
  Stack use after scope:   f8 
  Global redzone:          f9 
  Global init order:       f6 
  Poisoned by user:        f7 
  Container overflow:      fc 
  Array cookie:            ac 
  Intra object redzone:    bb 
  ASan internal:           fe 
  Left alloca redzone:     ca 
  Right alloca redzone:    cb 
  Shadow gap:              cc 
==6708==ABORTING
```

**Comment by def-** [comment]
Thread T0 reads, but at the same time thread T1 overwrites the data structures. There needs to be a lock at least.

**Comment by Zwelf** [comment]
I actually didn't fix this issue yet. See discussion in #3382
