### ISSUE TITLE
Memory leak in sqlite3

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3381]
```
=================================================================
==18192==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 992 byte(s) in 1 object(s) allocated from:
    #0 0x4f3d02 in __sanitizer::InternalMmapVectorNoCtor<__asan::AllocationSite>::Realloc(unsigned long) (/home/teeworlds/servers/DDNet-Server-asan+0x4f3d02)
    #1 0x7f59e7c7dc08  (/lib/x86_64-linux-gnu/libsqlite3.so.0+0x49c08)

SUMMARY: AddressSanitizer: 992 byte(s) leaked in 1 allocation(s).
```

**Comment by Zwelf** [comment]
Btw I have no idea what caused this. Was it related to the #3380 crash?

**Comment by def-** [comment]
I don't think so, just saw it randomly. Haven't seen it for weeks, so let's assume it is fixed. If it happens again, I'll reopen.

**Comment by def-** [comment]
GER2 used sqlite again because of DoS:
```
==21681==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 1352 byte(s) in 1 object(s) allocated from:
    #0 0x4f3d12 in realloc (/home/teeworlds/servers/DDNet-Server-asan+0x4f3d12)
    #1 0x7fd0bad7cbe8  (/lib/x86_64-linux-gnu/libsqlite3.so.0+0x49be8)

SUMMARY: AddressSanitizer: 1352 byte(s) leaked in 1 allocation(s).
```
