### ISSUE TITLE
Infinite loop in editor

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3395]
> when you open editor and set Width to 500  and press right mouse Height it crashes

I can reproduce this:

```
0x00005555556593f2 in CTextRender::TextEx (this=0x7ffff7fa9010, pCursor=0x7fffffffb460, 
    pText=0x555555a65f60 <CEditor::UiDoValueSelector(void*, CUIRect*, char const*, int, int, int, int, float, char const*, bool, bool, int, ColorRGBA*)::s_NumStr> "50", Length=3) at src/engine/client/text.cpp:947
947					int Wlen = minimum(WordLength(pCurrent), (int)(pEnd - pCurrent));
(gdb) bt
#0  0x00005555556593f2 in CTextRender::TextEx(CTextCursor*, char const*, int)
    (this=0x7ffff7fa9010, pCursor=0x7fffffffb460, pText=0x555555a65f60 <CEditor::UiDoValueSelector(void*, CUIRect*, char const*, int, int, int, int, float, char const*, bool, bool, int, ColorRGBA*)::s_NumStr> "50", Length=3)
    at src/engine/client/text.cpp:947
#1  0x0000555555658a0f in CTextRender::TextWidth(void*, float, char const*, int, float, float*, float*)
    (this=0x7ffff7fa9010, pFontSetV=0x0, Size=10, pText=0x555555a65f60 <CEditor::UiDoValueSelector(void*, CUIRect*, char const*, int, int, int, int, float, char const*, bool, bool, int, ColorRGBA*)::s_NumStr> "50", StrLength=3, LineWidth=3.40282347e+38, pAlignedHeight=0x0, pMaxCharacterHeightInLine=0x0) at src/engine/client/text.cpp:803
#2  0x0000555555774a91 in CEditor::DoEditBox(void*, CUIRect const*, char*, unsigned int, float, float*, bool, int)
    (this=0x555555b09720, pID=0x555555a65fb8 <CEditor::UiDoValueSelector(void*, CUIRect*, char const*, int, int, int, int, float, char const*, bool, bool, int, ColorRGBA*)::s_NumberBoxID>, pRect=0x7fffffffb8c0, pStr=0x555555a65f60 <CEditor::UiDoValueSelector(void*, CUIRect*, char const*, int, int, int, int, float, char const*, bool, bool, int, ColorRGBA*)::s_NumStr> "50", StrSize=64, FontSize=10, Offset=0x555555a65fb8 <CEditor::UiDoValueSelector(void*, CUIRect*, char const*, int, int, int, int, float, char const*, bool, bool, int, ColorRGBA*)::s_NumberBoxID>, Hidden=false, Corners=15)
    at src/game/editor/editor.cpp:483
#3  0x0000555555776cdc in CEditor::UiDoValueSelector(void*, CUIRect*, char const*, int, int, int, int, float, char const*, bool, bool, int, ColorRGBA*)
    (this=0x555555b09720, pID=0x555555a662a4 <CLayerTiles::RenderProperties(CUIRect*)::s_aIds+4>, pRect=0x7fffffffb8c0, pLabel=0x5555557fb399 "", Current=50, Min=1, Max=100000, Step=1, Scale=1, pToolTip=0x5555557fb838 "Use left mouse button to drag and change the value. Hold shift to be more precise. Rightclick to edit as text.", IsDegree=false, IsHex=false, Corners=15, Color=0x0) at src/game/editor/editor.cpp:808
#4  0x0000555555782dbe in CEditor::DoProperties(CUIRect*, CProperty*, int*, int*, ColorRGBA)
    (this=0x555555b09720, pToolBox=0x7fffffffbb90, pProps=0x7fffffffba30, pIDs=0x555555a662a0 <CLayerTiles::RenderProperties(CUIRect*)::s_aIds>, pNewVal=0x7fffffffb9b0, Color=...) at src/game/editor/editor.cpp:3039
#5  0x00005555557b169f in CLayerTiles::RenderProperties(CUIRect*) (this=0x555555ba28d0, pToolBox=0x7fffffffbb90)
    at src/game/editor/layer_tiles.cpp:886
#6  0x00005555557a9510 in CLayerGame::RenderProperties(CUIRect*) (this=0x555555ba28d0, pToolbox=0x7fffffffbb90)
    at src/game/editor/layer_game.cpp:71
#7  0x00005555557bdc82 in CEditor::PopupLayer(CEditor*, CUIRect, void*)
    (pEditor=0x555555b09720, View=..., pContext=0x55555586ce80 <CEditor::RenderLayers(CUIRect, CUIRect)::s_LayerPopupContext>) at src/game/editor/popups.cpp:485
#8  0x00005555557bb541 in CEditor::UiDoPopupMenu() (this=0x555555b09720) at src/game/editor/popups.cpp:85
#9  0x00005555557944b5 in CEditor::Render() (this=0x555555b09720) at src/game/editor/editor.cpp:6053
#10 0x00005555557966fa in CEditor::UpdateAndRender() (this=0x555555b09720) at src/game/editor/editor.cpp:6502
#11 0x0000555555610601 in CClient::Run() (this=0x7fffef344010) at src/engine/client/client.cpp:3308
#12 0x00005555556169ff in main(int, char const**) (argc=1, argv=0x7fffffffe4d8) at src/engine/client/client.cpp:4387
```

Looks like another infinite loop. @TsFreddie Any idea how best to fix it?

**Comment by Banana090** [comment]
Call for @Jupeyy , we faced this one before

**Comment by Jupeyy** [comment]
Just merge with the menu implementation, then it doesn't require writing the same code on and on

**Comment by def-** [comment]
Another infinite loop when you write "verification/" and press shift-backspace in save menu in editor:
```
str_utf8_decode (ptr=0xe4e70fd6fab1a500) at src/base/system.c:3181
3181	{
(gdb) bt
#0  str_utf8_decode (ptr=0xe4e70fd6fab1a500) at src/base/system.c:3181
#1  0x00005555556e9dae in CTextRender::TextEx(CTextCursor*, char const*, int)
    (this=0x7ffff7fa9010, pCursor=0x7fffffffb2c0, pText=0x5555560f6680 "verification3", Length=14)
    at src/engine/client/text.cpp:990
#2  0x00005555556e9149 in CTextRender::TextWidth(void*, float, char const*, int, float, float*, float*)
    (this=0x7ffff7fa9010, pFontSetV=0x0, Size=10, pText=0x5555560f6680 "verification3", StrLength=14, LineWidth=3.40282347e+38, pAlignedHeight=0x0, pMaxCharacterHeightInLine=0x0) at src/engine/client/text.cpp:809
#3  0x000055555580a495 in CEditor::DoEditBox(void*, CUIRect const*, char*, unsigned int, float, float*, bool, int)
    (this=
    0x5555560f60a0, pID=0x555555edf718 <CEditor::RenderFileDialog()::s_FileBoxID>, pRect=0x7fffffffb5b0, pStr=0x5555560f6680 "verification3", StrSize=512, FontSize=10, Offset=0x555555edf718 <CEditor::RenderFileDialog()::s_FileBoxID>, Hidden=false, Corners=15) at src/game/editor/editor.cpp:483
#4  0x0000555555820822 in CEditor::RenderFileDialog() (this=0x5555560f60a0) at src/game/editor/editor.cpp:4370
#5  0x000055555582a013 in CEditor::Render() (this=0x5555560f60a0) at src/game/editor/editor.cpp:6060
#6  0x000055555582c324 in CEditor::UpdateAndRender() (this=0x5555560f60a0) at src/game/editor/editor.cpp:6520
#7  0x00005555556a0d97 in CClient::Run() (this=0x7ffff60e9010) at src/engine/client/client.cpp:3308
#8  0x00005555556a7195 in main(int, char const**) (argc=1, argv=0x7fffffffe478) at src/engine/client/client.cpp:4387
```
