### ISSUE TITLE
Memory leak in CMasterServer::SetDefault()

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3396]
```
==11404==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 832 byte(s) in 4 object(s) allocated from:
    #0 0x522b22 in operator new(unsigned long) (/home/teeworlds/servers/DDNet-Server-asan+0x522b22)
    #1 0x6e148b in __gnu_cxx::new_allocator<std::_Sp_counted_ptr_inplace<CHostLookup, std::allocator<CHostLookup>, (__gnu_cxx::_Lock_policy)2> >::allocate(unsigned long, void const*) /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/ext/new_allocator.h:111:27
    #2 0x6e148b in std::allocator_traits<std::allocator<std::_Sp_counted_ptr_inplace<CHostLookup, std::allocator<CHostLookup>, (__gnu_cxx::_Lock_policy)2> > >::allocate(std::allocator<std::_Sp_counted_ptr_inplace<CHostLookup, std::allocator<CHostLookup>, (__gnu_cxx::_Lock_policy)2> >&, unsigned long) /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/alloc_traits.h:436
    #3 0x6e148b in std::__allocated_ptr<std::allocator<std::_Sp_counted_ptr_inplace<CHostLookup, std::allocator<CHostLookup>, (__gnu_cxx::_Lock_policy)2> > > std::__allocate_guarded<std::allocator<std::_Sp_counted_ptr_inplace<CHostLookup, std::allocator<CHostLookup>, (__gnu_cxx::_Lock_policy)2> > >(std::allocator<std::_Sp_counted_ptr_inplace<CHostLookup, std::allocator<CHostLookup>, (__gnu_cxx::_Lock_policy)2> >&) /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/allocated_ptr.h:97
    #4 0x6e148b in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<CHostLookup, std::allocator<CHostLookup> >(CHostLookup*&, std::_Sp_alloc_shared_tag<std::allocator<CHostLookup> >) /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/shared_ptr_base.h:675
    #5 0x6db9bb in std::__shared_ptr<CHostLookup, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<CHostLookup> >(std::_Sp_alloc_shared_tag<std::allocator<CHostLookup> >) /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/shared_ptr_base.h:1342:14
    #6 0x6db9bb in std::shared_ptr<CHostLookup>::shared_ptr<std::allocator<CHostLookup> >(std::_Sp_alloc_shared_tag<std::allocator<CHostLookup> >) /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/shared_ptr.h:359
    #7 0x6db9bb in std::shared_ptr<CHostLookup> std::allocate_shared<CHostLookup, std::allocator<CHostLookup> >(std::allocator<CHostLookup> const&) /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/shared_ptr.h:705
    #8 0x6db9bb in std::shared_ptr<CHostLookup> std::make_shared<CHostLookup>() /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/shared_ptr.h:721
    #9 0x6db9bb in CMasterServer::SetDefault() /home/teeworlds/src/master/src/engine/shared/masterserver.cpp:142
    #10 0x6db9bb in CMasterServer::CMasterServer() /home/teeworlds/src/master/src/engine/shared/masterserver.cpp:41
    #11 0x6db5dc in CreateEngineMasterServer() /home/teeworlds/src/master/src/engine/shared/masterserver.cpp:231:62
    #12 0x56c218 in main /home/teeworlds/src/master/src/engine/server/server.cpp:3499:45
    #13 0x7f506239109a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)

SUMMARY: AddressSanitizer: 832 byte(s) leaked in 4 allocation(s).
```

**Comment by heinrich5991** [comment]
Class doesn't exist anymore since #5064.
