### ISSUE TITLE
Client crashing when changing name

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#3444]
![image](https://user-images.githubusercontent.com/20344300/103105900-2f8c5580-4631-11eb-832c-a7fdbcd1c835.png)

1. Go to Settings -> Player -> Name
2. Then enter as many characters as possible.
3. Paste your favorite poop emoji or something like ø
4. ???
5. profit

```
Thread 7 "SDLAudioP2" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe37fe640 (LWP 44222)]
0x00007ffff6df4cb4 in __gconv_alias_compare () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff6df4cb4 in __gconv_alias_compare () at /usr/lib/libc.so.6
#1  0x00007ffff6ec84fb in tfind () at /usr/lib/libc.so.6
#2  0x00007ffff6df5a6e in __gconv_find_transform () at /usr/lib/libc.so.6
#3  0x00007ffff6df4789 in __gconv_open () at /usr/lib/libc.so.6
#4  0x00007ffff6df4478 in iconv_open () at /usr/lib/libc.so.6
#5  0x00007fffec812538 in  () at /usr/lib/libpulse.so.0
#6  0x00007fffec78732e in pa_log_levelv_meta () at /usr/lib/pulseaudio/libpulsecommon-14.0.so
#7  0x00007fffec787946 in pa_log_level_meta () at /usr/lib/pulseaudio/libpulsecommon-14.0.so
#8  0x00007fffec80711d in pa_stream_writable_size () at /usr/lib/libpulse.so.0
#9  0x00007ffff7999a65 in  () at /usr/lib/libSDL2-2.0.so.0
#10 0x00007ffff78d9c06 in  () at /usr/lib/libSDL2-2.0.so.0
#11 0x00007ffff79368d1 in  () at /usr/lib/libSDL2-2.0.so.0
#12 0x00007ffff79d5caa in  () at /usr/lib/libSDL2-2.0.so.0
#13 0x00007ffff7c753e9 in start_thread () at /usr/lib/libpthread.so.0
#14 0x00007ffff6ecc293 in clone () at /usr/lib/libc.so.6
(gdb) info registers
rax            0x2                 2
rbx            0x555555d0ef40      93825000337216
rcx            0x7fffe37f98e0      140737010178272
rdx            0x7ffff6df4cb0      140737335217328
rsi            0x0                 0
rdi            0x7fffe37f9830      140737010178096
rbp            0x7fffe37f9830      0x7fffe37f9830
rsp            0x7fffe37f97e8      0x7fffe37f97e8
r8             0x0                 0
r9             0x7ffff6f413c0      140737336579008
r10            0x7ffff6f40ac0      140737336576704
r11            0x8000000004007     2251799813701639
r12            0x7ffff6df4cb0      140737335217328
r13            0x555555d0ef40      93825000337216
r14            0x0                 0
r15            0x7fffe37f98e0      140737010178272
rip            0x7ffff6df4cb4      0x7ffff6df4cb4 <__gconv_alias_compare+4>
eflags         0x210202            [ IF RF ID ]
cs             0x33                51
ss             0x2b                43
ds             0x0                 0
es             0x0                 0
fs             0x0                 0
gs             0x0                 0
```

**Comment by tyurderi** [comment]
easy fix
just dont do this

**Comment by def-** [comment]
```
=================================================================
==491687==ERROR: AddressSanitizer: negative-size-param: (size=-1)
[Detaching after fork from child process 491814]
    #0 0x555555db5b08 in strncpy (/media/ddnet/DDNet+0x861b08)
    #1 0x555556082c72 in str_copy /media/ddnet/src/base/system.c:2358:2
    #2 0x555556087dc3 in str_utf8_truncate /media/ddnet/src/base/system.c:2373:2
    #3 0x555556095521 in str_utf8_copy /media/ddnet/src/base/system.c:3275:2
    #4 0x555556800cfa in CMenus::DoEditBox(void*, CUIRect const*, char*, unsigned int, float, float*, bool, int, char const*) /media/ddnet/src/game/client/components/menus.cpp:636:5
    #5 0x555556969830 in CMenus::RenderSettingsPlayer(CUIRect) /media/ddnet/src/game/client/components/menus_settings.cpp:377:5
    #6 0x55555699b476 in CMenus::RenderSettings(CUIRect) /media/ddnet/src/game/client/components/menus_settings.cpp:1539:3
    #7 0x5555568401fc in CMenus::Render() /media/ddnet/src/game/client/components/menus.cpp:1804:5
    #8 0x555556869adb in CMenus::OnRender() /media/ddnet/src/game/client/components/menus.cpp:2909:2
    #9 0x555556b9d849 in CGameClient::OnRender() /media/ddnet/src/game/client/gameclient.cpp:684:28
    #10 0x5555562421c3 in CClient::Render() /media/ddnet/src/engine/client/client.cpp:1138:16
    #11 0x5555562980de in CClient::Run() /media/ddnet/src/engine/client/client.cpp:3309:7
    #12 0x5555562ca74f in main /media/ddnet/src/engine/client/client.cpp:4398:11
    #13 0x7ffff6de4151 in __libc_start_main (/usr/lib/libc.so.6+0x28151)
    #14 0x555555d98e3d in _start (/media/ddnet/DDNet+0x844e3d)

0x5555581038a3 is located 2403 bytes inside of global variable 'g_Config' defined in 'src/engine/shared/config.cpp:8:9' (0x555558102f40) of size 8668
SUMMARY: AddressSanitizer: negative-size-param (/media/ddnet/DDNet+0x861b08) in strncpy
```
