### ISSUE TITLE
Client crashes sometimes on player join

### ISSUE THREAD

**Issue by Zwelf** [ddnet/ddnet#3513]
Since a few days my ddnet client crashes sometimes when a player joins and it happened once in the Internet tab of the server browser.

OS: Debian 10
Version: 15.2.5

This email thread might help to resolve this issue: https://curl.se/mail/lib-2018-12/0070.html
Link to all emails in the thread: https://curl.se/mail/lib-2018-12/index.html#70

```
[2021-01-14 20:36:34][chat]: *** : 'AloneDeath' entered and joined the game

Thread 3 "DDNet" received signal SIGPIPE, Broken pipe.
[Switching to Thread 0x7fffea2e0700 (LWP 25512)]
__libc_write (nbytes=24, buf=0x7fffdc4c4ef3, fd=51)
    at ../sysdeps/unix/sysv/linux/write.c:26
26	../sysdeps/unix/sysv/linux/write.c: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  0x00007ffff7a854a7 in __libc_write (nbytes=24, buf=0x7fffdc4c4ef3, fd=51) at ../sysdeps/unix/sysv/linux/write.c:26
#1  0x00007ffff7a854a7 in __libc_write (fd=51, buf=0x7fffdc4c4ef3, nbytes=24) at ../sysdeps/unix/sysv/linux/write.c:24
#2  0x00007ffff7d80b15 in  () at /lib/x86_64-linux-gnu/libcrypto.so.1.1
#3  0x00007ffff7d7bd9a in  () at /lib/x86_64-linux-gnu/libcrypto.so.1.1
#4  0x00007ffff7d7adf3 in  () at /lib/x86_64-linux-gnu/libcrypto.so.1.1
#5  0x00007ffff7d7b293 in BIO_write () at /lib/x86_64-linux-gnu/libcrypto.so.1.1
#6  0x00007ffff47b8877 in  () at /lib/x86_64-linux-gnu/libssl.so.1.1
#7  0x00007ffff47b97b1 in  () at /lib/x86_64-linux-gnu/libssl.so.1.1
#8  0x00007ffff47c2f79 in  () at /lib/x86_64-linux-gnu/libssl.so.1.1
#9  0x00007ffff47c1095 in  () at /lib/x86_64-linux-gnu/libssl.so.1.1
#10 0x00007ffff47cc15f in SSL_shutdown () at /lib/x86_64-linux-gnu/libssl.so.1.1
#11 0x00007ffff7a4c2c5 in  () at /lib/x86_64-linux-gnu/libcurl.so.4
#12 0x00007ffff7a4c331 in  () at /lib/x86_64-linux-gnu/libcurl.so.4
#13 0x00007ffff7a05398 in  () at /lib/x86_64-linux-gnu/libcurl.so.4
#14 0x00007ffff7a19c96 in  () at /lib/x86_64-linux-gnu/libcurl.so.4
#15 0x00007ffff7a1b0f6 in  () at /lib/x86_64-linux-gnu/libcurl.so.4
#16 0x00007ffff7a1baa9 in curl_multi_perform () at /lib/x86_64-linux-gnu/libcurl.so.4
#17 0x00007ffff7a12642 in curl_easy_perform () at /lib/x86_64-linux-gnu/libcurl.so.4
#18 0x000055555563770c in CRequest::RunImpl(void*) (this=this@entry=0x55555766eb20, pHandle=pHandle@entry=0x7fffdc37e970)
    at /home/user/git/ddnet/src/engine/client/http.cpp:147
#19 0x0000555555637873 in CRequest::Run() (this=0x55555766eb20) at /home/user/git/ddnet/src/engine/client/http.cpp:99
#20 0x00005555555e26e6 in CJobPool::WorkerThread(void*) (pUser=pUser@entry=0x5555559dec60) at /home/user/git/ddnet/src/engine/shared/jobs.cpp:79
#21 0x00005555555f7817 in thread_run (user=<optimized out>) at /home/user/git/ddnet/src/base/system.c:694
#22 0x00007ffff7a7bfa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#23 0x00007ffff4bc64cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by def-** [comment]
I thought this would be an easy fix, but we set this already:
```
curl_easy_setopt(pHandle, CURLOPT_NOSIGNAL, 1L);
```

**Comment by Zwelf** [comment]
I think ignoring SIGPIPE in all threads is could resolve this issue

> Either way, a multi-threaded application that uses libcurl/openssl needs
> to have a signhandler for or ignore SIGPIPE on its own.
