### ISSUE TITLE
Server crashes if there's a MySQL error during initialization

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#3534]
```
[2021-01-23 00:02:50][sql]: MySQL Error: MySQL server has gone away
free(): invalid pointer

Thread 2 "DDNet-Server" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffff6743640 (LWP 2903048)]
0x00007ffff75e8615 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff75e8615 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff75d1862 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff762a5e8 in __libc_message () from /usr/lib/libc.so.6
#3  0x00007ffff763227a in malloc_printerr () from /usr/lib/libc.so.6
#4  0x00007ffff763364c in _int_free () from /usr/lib/libc.so.6
#5  0x00005555555e6043 in sql::SQLException::~SQLException (this=0x7ffff0021e80, 
    __in_chrg=<optimized out>) at ../ddnet-libs/mysql/include/cppconn/exception.h:112
#6  0x00007ffff799aff3 in __gxx_exception_cleanup (code=<optimized out>, exc=0x7ffff0021e60)
    at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_throw.cc:49
#7  __gxx_exception_cleanup (code=<optimized out>, exc=0x7ffff0021e60)
    at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_throw.cc:33
#8  0x00005555555e4ab8 in CMysqlConnection::Connect (this=0x55555586dde0)
    at ../src/engine/server/databases/mysql.cpp:158
#9  0x00005555555df8bc in CDbConnectionPool::ExecSqlFunc (this=0x555555825d20, 
    pConnection=0x55555586dde0, pData=0x55555586e450, Failure=false)
    at ../src/engine/server/databases/connection_pool.cpp:209
#10 0x00005555555df57b in CDbConnectionPool::Worker (this=0x555555825d20)
    at ../src/engine/server/databases/connection_pool.cpp:159
#11 0x00005555555df3f1 in CDbConnectionPool::Worker (pUser=0x555555825d20)
    at ../src/engine/server/databases/connection_pool.cpp:132
#12 0x00005555555c5f2e in thread_run (user=0x555555823ed0) at ../src/base/system.c:696
#13 0x00007ffff777d3e9 in start_thread () from /usr/lib/libpthread.so.0
#14 0x00007ffff76ab293 in clone () from /usr/lib/libc.so.6
```

**Comment by heinrich5991** [comment]
This might have been my broken MySQL installation, not sure.

**Comment by def-** [comment]
Broken MySQL server or broken library? A broken MySQL server should not result in a DDNet server crash.

**Comment by heinrich5991** [comment]
After I installed my own MySQL-C++ connector instead of using the bundled one, the issue went away. This might have been a library issue.

**Comment by def-** [comment]
We should probably stop bundling it, it doesn't seem to work well for most.
