### ISSUE TITLE
Client crash in UnpackPacket

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3545]
Can't reproduce unfortunately:
```
Core was generated by `./DDNet -f mine.cfg'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fd439b37b1e in __memmove_avx_unaligned_erms () from /usr/lib/libc.so.6
[Current thread is 1 (Thread 0x7fd4344bdb40 (LWP 220066))]
(gdb) bt
#0  0x00007fd439b37b1e in __memmove_avx_unaligned_erms () at /usr/lib/libc.so.6
#1  0x0000561d5224931f in CNetBase::UnpackPacket(unsigned char*, int, CNetPacketConstruct*, bool&, int*, int*)
    (pBuffer=0x7fd433dc73d8 "\004", Size=<optimized out>, pPacket=pPacket@entry=0x7fd433dc40c0, Sixup=@0x7ffcd68f1517: true, 
    Sixup@entry=@0x7ffcd68f1517: false, pSecurityToken=pSecurityToken@entry=0x0, pResponseToken=pResponseToken@entry=0x0) at src/engine/shared/network.cpp:267
#2  0x0000561d52249f03 in CNetClient::Recv(CNetChunk*)
    (this=this@entry=0x7fd433dbb970, pChunk=pChunk@entry=0x7ffcd68f1580) at src/engine/shared/network_client.cpp:76
#3  0x0000561d52286b53 in CClient::PumpNetwork() (this=this@entry=0x7fd433d44010) at src/engine/client/client.cpp:2577
#4  0x0000561d52287802 in CClient::Update() (this=0x7fd433d44010) at src/engine/client/client.cpp:2862
#5  0x0000561d52288919 in CClient::Run() (this=this@entry=0x7fd433d44010) at src/engine/client/client.cpp:3248
#6  0x0000561d5221bf19 in main(int, char const**) (argc=3, argv=0x7ffcd68f5808) at src/engine/client/client.cpp:4398
```

**Comment by Learath2** [comment]
Do you have the core for this?

**Comment by def-** [comment]
Yes, will send you privately, since it contains my ddnet admin pw

**Comment by def-** [comment]
Probably fixed by #6068
