### ISSUE TITLE
Crash in video recorder

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3547]
Happend one time when starting a recording with the attached file, couldn't reproduce.
[unfinished_dummy_map.demo.zip](https://github.com/ddnet/ddnet/files/5872801/unfinished_dummy_map.demo.zip)

```
Core was generated by `./DDNet -f mine.cfg'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055e64d4e2c24 in CVideo::NextVideoFrameThread (this=0x55e64f0ac2b0) at src/engine/client/video.cpp:225
225				m_VideoStream.pFrame->pts = (int64)m_VideoStream.pEnc->frame_number;
[Current thread is 1 (Thread 0x7f00173ff640 (LWP 69451))]
(gdb) bt
#0  0x000055e64d4e2c24 in CVideo::NextVideoFrameThread() (this=0x55e64f0ac2b0) at src/engine/client/video.cpp:225
#1  CVideo::NextVideoFrameThread() (this=0x55e64f0ac2b0) at src/engine/client/video.cpp:214
#2  0x000055e64d499e66 in CGraphicsBackend_Threaded::ThreadFunc(void*) (pUser=pUser@entry=0x55e64de87d20)
    at src/engine/client/backend_sdl.cpp:88
#3  0x000055e64d488da7 in thread_run (user=<optimized out>) at src/base/system.c:696
#4  0x00007f004213e3e9 in start_thread () at /usr/lib/libpthread.so.0
#5  0x00007f004206a293 in clone () at /usr/lib/libc.so.6
```

@sirius1242 any idea?

**Comment by sirius1242** [comment]
Couldn't reproduce with version 15.2.5-1, either. Did anyone else met the same problem?
