### ISSUE TITLE
Set height of second layer to exactly 500 => crash

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3632]
Can reproduce but don't understand:

```
(gdb) bt
#0  0x000055555577c1f2 in CLayerGroup::Render() (this=0x7fffc4ed48c0) at src/game/editor/editor.cpp:191
#1  0x0000555555787eaf in CEditor::DoMapEditor(CUIRect) (this=0x555555b0a000, View=...)
    at src/game/editor/editor.cpp:2325
#2  0x000055555579c193 in CEditor::Render() (this=0x555555b0a000) at src/game/editor/editor.cpp:5825
#3  0x000055555579f8f2 in CEditor::UpdateAndRender() (this=0x555555b0a000) at src/game/editor/editor.cpp:6521
#4  0x0000555555613131 in CClient::Run() (this=0x7fffef284010) at src/engine/client/client.cpp:3329
#5  0x00005555556196e8 in main(int, char const**) (argc=1, argv=0x7fffffffe478) at src/engine/client/client.cpp:4417
(gdb) print i
$12 = 1
(gdb) print *m_lLayers[i]
$11 = {_vptr.CLayer = 0x555002c77925, m_pEditor = 0x555555a70010, m_aName = '\000' <repeats 11 times>, m_Type = 2, 
  m_Flags = 0, m_Readonly = false, m_Visible = true, m_BrushRefCount = 0}
(gdb) print *m_lLayers[0]
$13 = {_vptr.CLayer = 0x555555870a40 <vtable for CLayerGame+16>, m_pEditor = 0x555555b0a000, 
  m_aName = "Game\000\000\000\000\000\000\000", m_Type = 2, m_Flags = 0, m_Readonly = false, m_Visible = true, 
  m_BrushRefCount = 0}
```
As reported by Anoian
[Bug.zip](https://github.com/ddnet/ddnet/files/6011174/Bug.zip)
Seems like the m_lLayers[1] object has been deleted?

**Comment by Chairn** [comment]
Could not reproduce on master.
