### ISSUE TITLE
Memory leak in CMasterServer::SetDefault()

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3689]
```
=================================================================
==27444==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 64 byte(s) in 64 object(s) allocated from:
    #0 0x4f36b3 in __interceptor_malloc (/home/teeworlds/servers/DDNet-Server-asan+0x4f36b3)
    #1 0x5536a7 in CServer::Run() /home/teeworlds/src/master/src/engine/server/server.cpp:2362:31
    #2 0x562408 in main /home/teeworlds/src/master/src/engine/server/server.cpp:3594:21
    #3 0x7fe37871c09a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)

Indirect leak of 832 byte(s) in 4 object(s) allocated from:
    #0 0x5228f2 in operator new(unsigned long) (/home/teeworlds/servers/DDNet-Server-asan+0x5228f2)
    #1 0x6d590b in __gnu_cxx::new_allocator<std::_Sp_counted_ptr_inplace<CHostLookup, std::allocator<CHostLookup>, (__gnu_cxx::_Lock_policy)2> >::allocate(unsigned long, void const*) /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/ext/new_allocator.h:111:27
    #2 0x6d590b in std::allocator_traits<std::allocator<std::_Sp_counted_ptr_inplace<CHostLookup, std::allocator<CHostLookup>, (__gnu_cxx::_Lock_policy)2> > >::allocate(std::allocator<std::_Sp_counted_ptr_inplace<CHostLookup, std::allocator<CHostLookup>, (__gnu_cxx::_Lock_policy)2> >&, unsigned long) /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/alloc_traits.h:436
    #3 0x6d590b in std::__allocated_ptr<std::allocator<std::_Sp_counted_ptr_inplace<CHostLookup, std::allocator<CHostLookup>, (__gnu_cxx::_Lock_policy)2> > > std::__allocate_guarded<std::allocator<std::_Sp_counted_ptr_inplace<CHostLookup, std::allocator<CHostLookup>, (__gnu_cxx::_Lock_policy)2> > >(std::allocator<std::_Sp_counted_ptr_inplace<CHostLookup, std::allocator<CHostLookup>, (__gnu_cxx::_Lock_policy)2> >&) /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/allocated_ptr.h:97
    #4 0x6d590b in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<CHostLookup, std::allocator<CHostLookup> >(CHostLookup*&, std::_Sp_alloc_shared_tag<std::allocator<CHostLookup> >) /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/shared_ptr_base.h:675
    #5 0x6d1418 in std::__shared_ptr<CHostLookup, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<CHostLookup> >(std::_Sp_alloc_shared_tag<std::allocator<CHostLookup> >) /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/shared_ptr_base.h:1342:14
    #6 0x6d1418 in std::shared_ptr<CHostLookup>::shared_ptr<std::allocator<CHostLookup> >(std::_Sp_alloc_shared_tag<std::allocator<CHostLookup> >) /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/shared_ptr.h:359
    #7 0x6d1418 in std::shared_ptr<CHostLookup> std::allocate_shared<CHostLookup, std::allocator<CHostLookup> >(std::allocator<CHostLookup> const&) /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/shared_ptr.h:705
    #8 0x6d1418 in std::shared_ptr<CHostLookup> std::make_shared<CHostLookup>() /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/shared_ptr.h:721
    #9 0x6d1418 in CMasterServer::SetDefault() /home/teeworlds/src/master/src/engine/shared/masterserver.cpp:142
    #10 0x6d1418 in CMasterServer::CMasterServer() /home/teeworlds/src/master/src/engine/shared/masterserver.cpp:41
    #11 0x6d1017 in CreateEngineMasterServer() /home/teeworlds/src/master/src/engine/shared/masterserver.cpp:231:62
    #12 0x561be6 in main /home/teeworlds/src/master/src/engine/server/server.cpp:3532:45
    #13 0x7fe37871c09a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)

SUMMARY: AddressSanitizer: 896 byte(s) leaked in 68 allocation(s).
```

**Comment by gerdoe-jr** [comment]
Duplicate of #3396. Also I can't reproduce it. How does it appear?
