### ISSUE TITLE
Crash in client prediction on Avoid map

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#3934]
```
Core was generated by `./DDNet -f mine.cfg'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055f577985d7b in CProjectile::Tick (this=0x55f5788f53b0)
    at src/game/client/prediction/entities/projectile.cpp:108
108			else if(pTargetChr && m_Freeze && ((m_Layer == LAYER_SWITCH && m_Number > 0 && Collision()->m_pSwitchers[m_Number].m_Status[pTargetChr->Team()]) || m_Layer != LAYER_SWITCH))
[Current thread is 1 (Thread 0x7f6db6ecc000 (LWP 353790))]
(gdb) bt
#0  0x000055f577985d7b in CProjectile::Tick() (this=0x55f5788f53b0)
    at src/game/client/prediction/entities/projectile.cpp:108
#1  0x000055f57798726e in CGameWorld::Tick() (this=0x55f577b7ac70 <g_GameClient+295504>)
    at src/game/client/prediction/gameworld.cpp:189
#2  0x000055f57796b29c in CGameClient::OnPredict() (this=0x55f577b32a20 <g_GameClient>)
    at src/game/client/gameclient.cpp:1782
#3  0x000055f577811269 in CClient::Update() (this=0x7f6db6751010) at src/engine/client/client.cpp:2800
#4  0x000055f577812f95 in CClient::Run() (this=0x7f6db6751010) at src/engine/client/client.cpp:3254
#5  0x000055f57781a0a7 in main(int, char const**) (argc=3, argv=0x7ffeccde1c28) at src/engine/client/client.cpp:4429
(gdb) print m_Number
$2 = 2004515717
```

**Comment by trml** [comment]
Since switch isn't predicted, all references to switch should perhaps be removed.
Except freeze tiles with modified delay maybe, since those are often permanently active.

**Comment by def-** [comment]
Could you fix that?

**Comment by trml** [comment]
Yes, will take a look.

**Comment by Chairn** [comment]
Fixed by https://github.com/ddnet/ddnet/pull/3935
