### ISSUE TITLE
DDNet client crashes

### ISSUE THREAD

**Issue by fokkonaut** [ddnet/ddnet#4113]
It seems that ddnet client doesnt like my server, as it sometimes crashes there. Just like https://github.com/ddnet/ddnet/issues/3695 there is another crash, someone told me the program showed "free(): invalid size" and then "Aborted" before the crash.
Also there is anothet problem where the client hangs and if you dont wait for a few seconds and press nothing, it would crash aswell. I cant reproduce this myself, so I have no idea where these crashes could come from. If anyone here could try to debug this, it would be very cool.
(Only happens with DDNet client)

**Comment by Robyt3** [comment]
Is this related to the map on your server? The client crashes with a bunch of my maps and demos I created with 0.7 master.

**Comment by fokkonaut** [comment]
No, this is probably related to my mod sending "weird" packets. 0.7 clients dont crash and there is a lot going on in my mod, but I never get one of these crashes so I have no info about it. I told my community to try and debug this, not sure when or if the issue will be found yet.

**Comment by Jupeyy** [comment]
Next time ask them where in the map it crashes, and what they did, else it doesn't really help, except somebody wants to read all code paths for all packets again

**Comment by fokkonaut** [comment]
I think it crashes due to a feature called atom, i have another opened issue already, but not sure. If you would like, I can give you access to check.

**Comment by Jupeyy** [comment]
I'd prefer to talk about opensource stuff, else it just makes it hard to communicate with ppl who have more knowledge about the network implementation, so not interested, sry

**Comment by fokkonaut** [comment]
So, I found out: It crashes when atom gets activated while cl_antiping is on.

**Comment by fokkonaut** [comment]
Think its a server issue

**Comment by Jupeyy** [comment]
It should still not crash the client.
Would be nice if you post a backtrace

**Comment by fokkonaut** [comment]
It was because I sent uninitialized data, it was just garbage. No need/way to fix this.

**Comment by Jupeyy** [comment]
Would be nice if you could do it, i cannot reproduce it because my local server sets x and y to zero even if uninitialized :D

**Comment by fokkonaut** [comment]
I can try later dunno how to save bt in visual studio tho. Also, it crashed in CalcPos, in IntersectLine

**Comment by Robyt3** [comment]
I can't reproduce the crash with ASAN, but I can get the client to freeze by sending a random start tick.

Change both `pProj->m_StartTick = m_StartTick;` ([here](https://github.com/ddnet/ddnet/blob/56088cb4b090e2354206e6239cfd63727a97686d/src/game/server/entities/projectile.cpp#L300) and [here](https://github.com/ddnet/ddnet/blob/56088cb4b090e2354206e6239cfd63727a97686d/src/game/server/entities/projectile.cpp#L405)) to `pProj->m_StartTick = secure_rand();`. Enable all antiping options in a client, join the server and start shooting grenades. I also used `tune grenade_fire_delay 50` to test faster, but the freeze happens with just a single projectile as well.

Here are the stack frames during the freeze:

```
(gdb) bt full
#0  0x00005581e1622fb7 in std::clamp<int>(int const&, int const&, int const&)
    (__val=@0x7ffce49502c0: -67108864, __lo=@0x7ffce49502d0: 0, __hi=@0x7ffce49502e0: 49)
    at /usr/include/c++/11/bits/stl_algo.h:3659
#1  0x00005581e2b0e4e2 in CCollision::GetTile(int, int) const (this=0x7f8082eef868, x=-624290048, y=-2147483648)
    at src/game/collision.cpp:283
        Nx = 0
        Ny = 0
        pos = 0
#2  0x00005581e2b13895 in CCollision::IsSolid(int, int) const (this=0x7f8082eef868, x=-624290048, y=-2147483648)
    at src/game/collision.cpp:565
        index = 0
#3  0x00005581e1dd42f6 in CCollision::CheckPoint(float, float) const (this=0x7f8082eef868, x=-624290048, y=-2.14748365e+09)
    at src/game/collision.h:36
#4  0x00005581e2b0eca6 in CCollision::IntersectLine(vector2_base<float>, vector2_base<float>, vector2_base<float>*, vector2_base<float>*) const (this=0x7f8082eef868, Pos0=..., Pos1=..., pOutCollision=0x7ffce49505d0, pOutBeforeCollision=0x7ffce49505f0)
    at src/game/collision.cpp:305
        a = 0.160863325
        Pos = {{x = -624290048, u = -624290048}, {y = 1.04802886e+15, v = 1.04802886e+15}}
        i = 32386065
        Distance = 201326592
        End = 201326592
        Last = {{x = -624290048, u = -624290048}, {y = 1.04802886e+15, v = 1.04802886e+15}}
        ix = -624290048
        iy = -2147483648
#5  0x00005581e2499d8b in CProjectile::Tick() (this=0x60d0001c7110)
    at src/game/client/prediction/entities/projectile.cpp:82
        Pt = -1223594.12
        Ct = -1223594
        PrevPos = {{x = -624290048, u = -624290048}, {y = 1.04802886e+15, v = 1.04802886e+15}}
        CurPos = {{x = -624289984, u = -624289984}, {y = 1.04802866e+15, v = 1.04802866e+15}}
        ColPos = {{x = 0, u = 0}, {y = 0, v = 0}}
        NewPos = {{x = 0, u = 0}, {y = 0, v = 0}}
        Collide = 17711488
        pOwnerChar = 0x4d96b1286dfd2b00
        pTargetChr = 0x7ffce4950740
        isWeaponCollide = 228
#6  0x00005581e24afdbb in CGameWorld::Tick() (this=0x7f8082f413c8)
    at src/game/client/prediction/gameworld.cpp:206
        pEnt = 0x60d0001c7110
        __for_range = @0x7f8082f418e0: {0x60d0001c7110, 0x0, 0x60c000234c40, 0x0, 0x6190010e4180}
        __for_begin = 0x7f8082f418e0
        __for_end = 0x7f8082f41908
#7  0x00005581e235807d in CGameClient::OnPredict() (this=0x7f8082bc4800)
    at src/game/client/gameclient.cpp:1822
        pInputData = 0x7f80843c63e8
        pDummyInputData = 0x0
        DummyFirst = false
        Tick = 506
        BeforePrevChar = {m_pWorld = 0x7f8082f413c8, m_pCollision = 0x7f8082eef868, m_pTeleOuts = 0x0, m_Pos = {{x = 106, u = 106}, {y = 177, v = 177}}, m_Vel = {{x = 0.00390625, u = 0.00390625}, {y = 0, v = 0}}, m_HookPos = {{x = 106, u = 106}, {y = 177, v = 177}}, m_HookDir = {{x = 0, u = 0}, {y = 0, v = 0}}, m_HookTeleBase = {{x = 0, u = 0}, {y = 0, v = 0}}, m_HookTick = 0, m_HookState = 0, m_HookedPlayer = -1, m_AttachedPlayers = std::set with 0 elements, m_ActiveWeapon = 3, m_aWeapons = {{m_AmmoRegenStart = 0, m_Ammo = -1, m_Ammocost = 0, m_Got = true}, {m_AmmoRegenStart = 0, m_Ammo = -1, m_Ammocost = 0, m_Got = true}, {m_AmmoRegenStart = 0, m_Ammo = -1, m_Ammocost = 0, m_Got = true}, {m_AmmoRegenStart = 0, m_Ammo = -1, m_Ammocost = 0, m_Got = true}, {m_AmmoRegenStart = 0, m_Ammo = -1, m_Ammocost = 0, m_Got = true}, {m_AmmoRegenStart = 0, m_Ammo = -1, m_Ammocost = 0, m_Got = false}}, m_Ninja = {m_ActivationDir = {{x = 0, u = 0}, {y = 0, v = 0}}, m_ActivationTick = 0, m_CurrentMoveTime = 0, m_OldVelAmount = 0}, m_NewHook = false, m_Jumped = 0, m_JumpedTotal = 0, m_Jumps = 2, m_Direction = 0, m_Angle = -326, m_Input = {m_Direction = 0, m_TargetX = 83, m_TargetY = -272, m_Jump = 0, m_Fire = 52, m_Hook = 0, m_PlayerFlags = 1, m_WantedWeapon = 0, m_NextWeapon = 8, m_PrevWeapon = 0}, m_TriggeredEvents = 0, m_Id = 0, m_Reset = false, m_LastVel = {{x = 0, u = 0}, {y = 0, v = 0}}, m_Colliding = 0, m_LeftWall = true, m_Solo = false, m_Jetpack = false, m_CollisionDisabled = false, m_EndlessHook = false, m_EndlessJump = false, m_HammerHitDisabled = false, m_GrenadeHitDisabled = false, m_LaserHitDisabled = false, m_ShotgunHitDisabled = false, m_HookHitDisabled = false, m_Super = false, m_HasTelegunGun = false, m_HasTelegunGrenade = false, m_HasTelegunLaser = false, m_FreezeStart = 0, m_FreezeEnd = 0, m_IsInFreeze = false, m_DeepFrozen = false, m_LiveFrozen = false, m_Tuning = {m_GroundControlSpeed = {m_Value = 1000}, m_GroundControlAccel = {m_Value = 200}, m_GroundFriction = {m_Value = 50}, m_GroundJumpImpulse = {m_Value = 1320}, m_AirJumpImpulse = {m_Value = 1200}, m_AirControlSpeed = {m_Value = 500}, m_AirControlAccel = {m_Value = 150}, m_AirFriction = {m_Value = 95}, m_HookLength = {m_Value = 38000}, m_HookFireSpeed = {m_Value = 8000}, m_HookDragAccel = {m_Value = 300}, m_HookDragSpeed = {m_Value = 1500}, m_Gravity = {m_Value = 50}, m_VelrampStart = {m_Value = 55000}, m_VelrampRange = {m_Value = 200000}, m_VelrampCurvature = {m_Value = 140}, m_GunCurvature = {m_Value = 0}, m_GunSpeed = {m_Value = 140000}, m_GunLifetime = {m_Value = 200}, m_ShotgunCurvature = {m_Value = 0}, m_ShotgunSpeed = {m_Value = 50000}, m_ShotgunSpeeddiff = {m_Value = 0}, m_ShotgunLifetime = {m_Value = 20}, m_GrenadeCurvature = {m_Value = 700}, m_GrenadeSpeed = {m_Value = 100000}, m_GrenadeLifetime = {m_Value = 200}, m_LaserReach = {m_Value = 80000}, m_LaserBounceDelay = {m_Value = 15000}, m_LaserBounceNum = {m_Value = 100000}, m_LaserBounceCost = {m_Value = 0}, m_LaserDamage = {m_Value = 500}, m_PlayerCollision = {m_Value = 100}, m_PlayerHooking = {m_Value = 100}, m_JetpackStrength = {m_Value = 0}, m_ShotgunStrength = {m_Value = 1000}, m_ExplosionStrength = {m_Value = 600}, m_HammerStrength = {m_Value = 100}, m_HookDuration = {m_Value = 125}, m_HammerFireDelay = {m_Value = 12500}, m_GunFireDelay = {m_Value = 12500}, m_ShotgunFireDelay = {m_Value = 50000}, m_GrenadeFireDelay = {m_Value = 50000}, m_LaserFireDelay = {m_Value = 80000}, m_NinjaFireDelay = {m_Value = 80000}, m_HammerHitFireDelay = {m_Value = 32000}}, m_pTeams = 0x7f8082f41750, m_MoveRestrictions = 0}
        BeforeChar = {m_pWorld = 0x7f8082f413c8, m_pCollision = 0x7f8082eef868, m_pTeleOuts = 0x0, m_Pos = {{x = 106, u = 106}, {y = 177, v = 177}}, m_Vel = {{x = 0.00390625, u = 0.00390625}, {y = 0, v = 0}}, m_HookPos = {{x = 106, u = 106}, {y = 177, v = 177}}, m_HookDir = {{x = 0, u = 0}, {y = 0, v = 0}}, m_HookTeleBase = {{x = 0, u = 0}, {y = 0, v = 0}}, m_HookTick = 0, m_HookState = 0, m_HookedPlayer = -1, m_AttachedPlayers = std::set with 0 elements, m_ActiveWeapon = 3, m_aWeapons = {{m_AmmoRegenStart = 0, m_Ammo = -1, m_Ammocost = 0, m_Got = true}, {m_AmmoRegenStart = 0, m_Ammo = -1, m_Ammocost = 0, m_Got = true}, {m_AmmoRegenStart = 0, m_Ammo = -1, m_Ammocost = 0, m_Got = true}, {m_AmmoRegenStart = 0, m_Ammo = -1, m_Ammocost = 0, m_Got = true}, {m_AmmoRegenStart = 0, m_Ammo = -1, m_Ammocost = 0, m_Got = true}, {m_AmmoRegenStart = 0, m_Ammo = -1, m_Ammocost = 0, m_Got = false}}, m_Ninja = {m_ActivationDir = {{x = 0, u = 0}, {y = 0, v = 0}}, m_ActivationTick = 0, m_CurrentMoveTime = 0, m_OldVelAmount = 0}, m_NewHook = false, m_Jumped = 0, m_JumpedTotal = 0, m_Jumps = 2, m_Direction = 0, m_Angle = -326, m_Input = {m_Direction = 0, m_TargetX = 83, m_TargetY = -272, m_Jump = 0, m_Fire = 52, m_Hook = 0, m_PlayerFlags = 1, m_WantedWeapon = 0, m_NextWeapon = 8, m_PrevWeapon = 0}, m_TriggeredEvents = 0, m_Id = 0, m_Reset = false, m_LastVel = {{x = 0, u = 0}, {y = 0, v = 0}}, m_Colliding = 0, m_LeftWall = true, m_Solo = false, m_Jetpack = false, m_CollisionDisabled = false, m_EndlessHook = false, m_EndlessJump = false, m_HammerHitDisabled = false, m_GrenadeHitDisabled = false, m_LaserHitDisabled = false, m_ShotgunHitDisabled = false, m_HookHitDisabled = false, m_Super = false, m_HasTelegunGun = false, m_HasTelegunGrenade = false, m_HasTelegunLaser = false, m_FreezeStart = 0, m_FreezeEnd = 0, m_IsInFreeze = false, m_DeepFrozen = false, m_LiveFrozen = false, m_Tuning = {m_GroundControlSpeed = {m_Value = 1000}, m_GroundControlAccel = {m_Value = 200}, m_GroundFriction = {m_Value = 50}, m_GroundJumpImpulse = {m_Value = 1320}, m_AirJumpImpulse = {m_Value = 1200}, m_AirControlSpeed = {m_Value = 500}, m_AirControlAccel = {m_Value = 150}, m_AirFriction = {m_Value = 95}, m_HookLength = {m_Value = 38000}, m_HookFireSpeed = {m_Value = 8000}, m_HookDragAccel = {m_Value = 300}, m_HookDragSpeed = {m_Value = 1500}, m_Gravity = {m_Value = 50}, m_VelrampStart = {m_Value = 55000}, m_VelrampRange = {m_Value = 200000}, m_VelrampCurvature = {m_Value = 140}, m_GunCurvature = {m_Value = 0}, m_GunSpeed = {m_Value = 140000}, m_GunLifetime = {m_Value = 200}, m_ShotgunCurvature = {m_Value = 0}, m_ShotgunSpeed = {m_Value = 50000}, m_ShotgunSpeeddiff = {m_Value = 0}, m_ShotgunLifetime = {m_Value = 20}, m_GrenadeCurvature = {m_Value = 700}, m_GrenadeSpeed = {m_Value = 100000}, m_GrenadeLifetime = {m_Value = 200}, m_LaserReach = {m_Value = 80000}, m_LaserBounceDelay = {m_Value = 15000}, m_LaserBounceNum = {m_Value = 100000}, m_LaserBounceCost = {m_Value = 0}, m_LaserDamage = {m_Value = 500}, m_PlayerCollision = {m_Value = 100}, m_PlayerHooking = {m_Value = 100}, m_JetpackStrength = {m_Value = 0}, m_ShotgunStrength = {m_Value = 1000}, m_ExplosionStrength = {m_Value = 600}, m_HammerStrength = {m_Value = 100}, m_HookDuration = {m_Value = 125}, m_HammerFireDelay = {m_Value = 12500}, m_GunFireDelay = {m_Value = 12500}, m_ShotgunFireDelay = {m_Value = 50000}, m_GrenadeFireDelay = {m_Value = 50000}, m_LaserFireDelay = {m_Value = 80000}, m_NinjaFireDelay = {m_Value = 80000}, m_HammerHitFireDelay = {m_Value = 32000}}, m_pTeams = 0x7f8082f41750, m_MoveRestrictions = 0}
        aBeforeRender = {{{x = 106, u = 106}, {y = 177, v = 177}}, {{x = 0, u = 0}, {y = 0, v = 0}} <repeats 63 times>}
        Dummy = false
        pProjNext = 0x0
        pLocalChar = 0x6190010e4180
        pDummyChar = 0x0
        s_aLastPos = {{{x = 106, u = 106}, {y = 177, v = 177}}, {{x = 0, u = 0}, {y = 0, v = 0}} <repeats 63 times>}
        s_aLastActive = {true, false <repeats 63 times>}
#8  0x00005581e184a843 in CClient::Update() (this=0x7f8083fa1800) at src/engine/client/client.cpp:2767
        Repredict = true
        Now = 10080760724
        PredNow = 10100033572
```

The start and end positions for `IntersectLine` are very far apart, so the function loops very long for every projectile that's predicted with antiping.

This can also happen when the projectile speed is very high. For example `tune grenade_speed 1000000` makes the server unresponsive when shooting a grenade (CC #1192).

Changing the other projectile snap members to random values does not cause any crashes or freezes.

**Comment by Robyt3** [comment]
This is still a relevant issue.
