### ISSUE TITLE
Crash when pasting with cursor in specific position

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#4230]
As reported by murpi on Discord
![WcItxpb](https://user-images.githubusercontent.com/2335377/137902617-d9617068-c7f8-4443-8766-6440bf5b0770.png)
Can reproduce on Linux:
```
Thread 1 "DDNet" received signal SIGABRT, Aborted.
0x00007ffff6da4d22 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff6da4d22 in raise () at /usr/lib/libc.so.6
#1  0x00007ffff6d8e862 in abort () at /usr/lib/libc.so.6
#2  0x00007ffff714d802 in __gnu_cxx::__verbose_terminate_handler() () at /build/gcc/src/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007ffff7159c8a in __cxxabiv1::__terminate(void (*)()) (handler=<optimized out>) at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:48
#4  0x00007ffff7159cf7 in std::terminate() () at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:58
#5  0x00007ffff7159f8e in __cxxabiv1::__cxa_throw(void*, std::type_info*, void (*)(void*)) (obj=<optimized out>, tinfo=0x7ffff72bc1f0 <typeinfo for std::length_error>, dest=0x7ffff716ffd0 <std::length_error::~length_error()>)
    at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_throw.cc:95
#6  0x00007ffff7150486 in std::__throw_length_error(char const*) (__s=__s@entry=0x7ffff7254d89 "basic_string::_M_create") at /build/gcc/src/gcc/libstdc++-v3/src/c++11/functexcept.cc:82
#7  0x00007ffff71f6c9e in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long) (
    this=this@entry=0x7fffffffa2a0, __capacity=@0x7fffffffa0b0: 18446744073709551615, __old_capacity=__old_capacity@entry=0) at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.tcc:138
#8  0x00007ffff71f9dee in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char const*>(char const*, char const*, std::forward_iterator_tag)
    (this=0x7fffffffa2a0, __beg=0x5555558dab18 <g_Config+2904> "", __end=<optimized out>) at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.tcc:219
#9  0x00005555557bc6da in CUIEx::DoEditBox(void*, CUIRect const*, char*, unsigned int, float, float*, bool, int, char const*)
    (this=0x7ffff41888e0, pID=0x5555558dab18 <g_Config+2904>, pRect=0x7fffffffa600, pStr=0x5555558dab18 <g_Config+2904> "", StrSize=25, FontSize=12, Offset=0x555555932688 <CMenus::RenderServerbrowserServerList(CUIRect)::Offset>, Hidden=false, Corners=5, pEmptyText=0x55555584ae7c "") at /media/ddnet/src/game/client/ui_ex.cpp:71
#10 0x000055555570c780 in CMenus::DoEditBox(void*, CUIRect const*, char*, unsigned int, float, float*, bool, int, char const*) (this=
    0x7ffff41884d0, pID=0x5555558dab18 <g_Config+2904>, pRect=0x7fffffffa600, pStr=0x5555558dab18 <g_Config+2904> "", StrSize=25, FontSize=12, Offset=0x555555932688 <CMenus::RenderServerbrowserServerList(CUIRect)::Offset>, Hidden=false, Corners=5, pEmptyText=0x55555584ae7c "") at /media/ddnet/src/game/client/components/menus.cpp:613
#11 0x000055555570c887 in CMenus::DoClearableEditBox(void*, void*, CUIRect const*, char*, unsigned int, float, float*, bool, int, char const*)
    (this=0x7ffff41884d0, pID=0x5555558dab18 <g_Config+2904>, pClearID=0x55555593268c <CMenus::RenderServerbrowserServerList(CUIRect)::s_ClearButton>, pRect=0x7fffffffa810, pStr=0x5555558dab18 <g_Config+2904> "", StrSize=25, FontSize=12, Offset=0x555555932688 <CMenus::RenderServerbrowserServerList(CUIRect)::Offset>, Hidden=false, Corners=15, pEmptyText=0x55555584ae7c "") at /media/ddnet/src/game/client/components/menus.cpp:622
#12 0x0000555555720ae2 in CMenus::RenderServerbrowserServerList(CUIRect) (this=0x7ffff41884d0, View=...) at /media/ddnet/src/game/client/components/menus_browser.cpp:536
#13 0x00005555557263ff in CMenus::RenderServerbrowser(CUIRect) (this=0x7ffff41884d0, MainView=...) at /media/ddnet/src/game/client/components/menus_browser.cpp:1418
#14 0x000055555571196f in CMenus::Render() (this=0x7ffff41884d0) at /media/ddnet/src/game/client/components/menus.cpp:1586
#15 0x000055555571866e in CMenus::OnRender() (this=0x7ffff41884d0) at /media/ddnet/src/game/client/components/menus.cpp:2772
#16 0x0000555555784d07 in CGameClient::OnRender() (this=0x7ffff4081010) at /media/ddnet/src/game/client/gameclient.cpp:629
#17 0x000055555562aedb in CClient::Render() (this=0x7ffff5a04010) at /media/ddnet/src/engine/client/client.cpp:1171
#18 0x00005555556342bc in CClient::Run() (this=0x7ffff5a04010) at /media/ddnet/src/engine/client/client.cpp:3335
#19 0x000055555563a80f in main(int, char const**) (argc=1, argv=0x7fffffffe388) at /media/ddnet/src/engine/client/client.cpp:4463
```

**Comment by def-** [comment]
```
(gdb) up
#9  0x00005555557bc6da in CUIEx::DoEditBox (this=0x7ffff41888e0, pID=0x5555558dab18 <g_Config+2904>, pRect=0x7fffffffa600, pStr=0x5555558dab18 <g_Config+2904> "", StrSize=25, FontSize=12, 
    Offset=0x555555932688 <CMenus::RenderServerbrowserServerList(CUIRect)::Offset>, Hidden=false, Corners=5, pEmptyText=0x55555584ae7c "") at /media/ddnet/src/game/client/ui_ex.cpp:71
71					std::string NewStr(pStr, OffsetL);
(gdb) print pStr
$1 = 0x5555558dab18 <g_Config+2904> ""
(gdb) print OffsetL
$2 = -1
```
