### ISSUE TITLE
Undefined behavior in CCharacter

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#4310]
```
/home/teeworlds/src/master/src/game/server/entities/character.cpp:1439:17: runtime error: -nan is outside the range of representable values of type 'int'
    #0 0x51bfe8 in CCharacter::HandleSkippableTiles(int) /home/teeworlds/src/master/src/game/server/entities/character.cpp:1439:17
    #1 0x50de53 in CCharacter::DDRacePostCoreTick() /home/teeworlds/src/master/src/game/server/entities/character.cpp:2142:2
    #2 0x50aeb3 in CCharacter::Tick() /home/teeworlds/src/master/src/game/server/entities/character.cpp:803:2
    #3 0x5d7df3 in CGameWorld::Tick() /home/teeworlds/src/master/src/game/server/gameworld.cpp:272:11
    #4 0x5777d1 in CGameContext::OnTick() /home/teeworlds/src/master/src/game/server/gamecontext.cpp
    #5 0x4acf38 in CServer::Run() /home/teeworlds/src/master/src/engine/server/server.cpp:2625:19
    #6 0x4be872 in main /home/teeworlds/src/master/src/engine/server/server.cpp:3636:21
    #7 0x7f221b3ffd09 in __libc_start_main csu/../csu/libc-start.c:308:16
    #8 0x4529f9 in _start (/home/teeworlds/servers/DDNet-Server-ubsan+0x4529f9)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/teeworlds/src/master/src/game/server/entities/character.cpp:1439:17 in 
/home/teeworlds/src/master/src/game/server/entities/character.cpp:1441:22: runtime error: -nan is outside the range of representable values of type 'int'
    #0 0x51c0b2 in CCharacter::HandleSkippableTiles(int) /home/teeworlds/src/master/src/game/server/entities/character.cpp:1441:22
    #1 0x50de53 in CCharacter::DDRacePostCoreTick() /home/teeworlds/src/master/src/game/server/entities/character.cpp:2142:2
    #2 0x50aeb3 in CCharacter::Tick() /home/teeworlds/src/master/src/game/server/entities/character.cpp:803:2
    #3 0x5d7df3 in CGameWorld::Tick() /home/teeworlds/src/master/src/game/server/gameworld.cpp:272:11
    #4 0x5777d1 in CGameContext::OnTick() /home/teeworlds/src/master/src/game/server/gamecontext.cpp
    #5 0x4acf38 in CServer::Run() /home/teeworlds/src/master/src/engine/server/server.cpp:2625:19
    #6 0x4be872 in main /home/teeworlds/src/master/src/engine/server/server.cpp:3636:21
    #7 0x7f221b3ffd09 in __libc_start_main csu/../csu/libc-start.c:308:16
    #8 0x4529f9 in _start (/home/teeworlds/servers/DDNet-Server-ubsan+0x4529f9)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/teeworlds/src/master/src/game/server/entities/character.cpp:1441:22 in 
/home/teeworlds/src/master/src/game/collision.cpp:504:17: runtime error: -nan is outside the range of representable values of type 'int'
    #0 0x6e7878 in CCollision::MoveBox(vector2_base<float>*, vector2_base<float>*, vector2_base<float>, float) const /home/teeworlds/src/master/src/game/collision.cpp
    #1 0x6f2048 in CCharacterCore::Move() /home/teeworlds/src/master/src/game/gamecore.cpp
    #2 0x50f88f in CCharacter::TickDefered() /home/teeworlds/src/master/src/game/server/entities/character.cpp:838:9
    #3 0x5d8053 in CGameWorld::Tick() /home/teeworlds/src/master/src/game/server/gameworld.cpp:280:11
    #4 0x5777d1 in CGameContext::OnTick() /home/teeworlds/src/master/src/game/server/gamecontext.cpp
    #5 0x4acf38 in CServer::Run() /home/teeworlds/src/master/src/engine/server/server.cpp:2625:19
    #6 0x4be872 in main /home/teeworlds/src/master/src/engine/server/server.cpp:3636:21
    #7 0x7f221b3ffd09 in __libc_start_main csu/../csu/libc-start.c:308:16
    #8 0x4529f9 in _start (/home/teeworlds/servers/DDNet-Server-ubsan+0x4529f9)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/teeworlds/src/master/src/game/collision.cpp:504:17 in 
/home/teeworlds/src/master/src/base/math.h:22:40: runtime error: -nan is outside the range of representable values of type 'int'
    #0 0x6f2b9e in round_to_int(float) /home/teeworlds/src/master/src/base/math.h
    #1 0x6f2b9e in CCharacterCore::Write(CNetObj_CharacterCore*) /home/teeworlds/src/master/src/game/gamecore.cpp:508:18
    #2 0x6f328e in CCharacterCore::Quantize() /home/teeworlds/src/master/src/game/gamecore.cpp:575
    #3 0x50fa4d in CCharacter::TickDefered() /home/teeworlds/src/master/src/game/server/entities/character.cpp:840:9
    #4 0x5d8053 in CGameWorld::Tick() /home/teeworlds/src/master/src/game/server/gameworld.cpp:280:11
    #5 0x5777d1 in CGameContext::OnTick() /home/teeworlds/src/master/src/game/server/gamecontext.cpp
    #6 0x4acf38 in CServer::Run() /home/teeworlds/src/master/src/engine/server/server.cpp:2625:19
    #7 0x4be872 in main /home/teeworlds/src/master/src/engine/server/server.cpp:3636:21
    #8 0x7f221b3ffd09 in __libc_start_main csu/../csu/libc-start.c:308:16
    #9 0x4529f9 in _start (/home/teeworlds/servers/DDNet-Server-ubsan+0x4529f9)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/teeworlds/src/master/src/base/math.h:22:40 in 
```

**Comment by def-** [comment]
It seems like the `SpeedLeft = MaxSpeed / 5.0f - cos(DiffAngle) * TeeSpeed;` is -nan. Changing this in any way might change physics, so I'm hesitant to touch this.

**Comment by def-** [comment]
Another occurrence:
```
/home/teeworlds/src/master/src/game/server/entities/character.cpp:1373:22: runtime error: -nan is outside the range of representable values of type 'int'
    #0 0x56297e87bdd9 in CCharacter::HandleSkippableTiles(int) /home/teeworlds/src/master/src/game/server/entities/character.cpp:1373:22
    #1 0x56297e86d5cf in CCharacter::DDRacePostCoreTick() /home/teeworlds/src/master/src/game/server/entities/character.cpp:2092:2
    #2 0x56297e86c3ee in CCharacter::Tick() /home/teeworlds/src/master/src/game/server/entities/character.cpp:760:2
    #3 0x56297e951a3a in CGameWorld::Tick() /home/teeworlds/src/master/src/game/server/gameworld.cpp:287:11
    #4 0x56297e8dfcf9 in CGameContext::OnTick() /home/teeworlds/src/master/src/game/server/gamecontext.cpp:947:10
    #5 0x56297e7f90fd in CServer::Run() /home/teeworlds/src/master/src/engine/server/server.cpp:2839:19
    #6 0x56297e7bd7c4 in main /home/teeworlds/src/master/src/engine/server/main.cpp:191:21
    #7 0x7fbe3d05e189 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #8 0x7fbe3d05e244 in __libc_start_main csu/../csu/libc-start.c:381:3
    #9 0x56297e77e550 in _start (/home/teeworlds/servers/DDNet-Server-ubsan+0x285550) (BuildId: 4dd9c570d72b237e02c0e986a7f986fcd8008bcd)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/teeworlds/src/master/src/game/server/entities/character.cpp:1373:22 in
/home/teeworlds/src/master/src/base/math.h:128:20: runtime error: negation of -2147483648 cannot be represented in type 'int'; cast to an unsigned type to negate this value to itself
    #0 0x56297e87c051 in int absolute<int>(int) /home/teeworlds/src/master/src/base/math.h:128:20
    #1 0x56297e87c051 in CCharacter::HandleSkippableTiles(int) /home/teeworlds/src/master/src/game/server/entities/character.cpp:1373:8
    #2 0x56297e86d5cf in CCharacter::DDRacePostCoreTick() /home/teeworlds/src/master/src/game/server/entities/character.cpp:2092:2
    #3 0x56297e86c3ee in CCharacter::Tick() /home/teeworlds/src/master/src/game/server/entities/character.cpp:760:2
    #4 0x56297e951a3a in CGameWorld::Tick() /home/teeworlds/src/master/src/game/server/gameworld.cpp:287:11
    #5 0x56297e8dfcf9 in CGameContext::OnTick() /home/teeworlds/src/master/src/game/server/gamecontext.cpp:947:10
    #6 0x56297e7f90fd in CServer::Run() /home/teeworlds/src/master/src/engine/server/server.cpp:2839:19
    #7 0x56297e7bd7c4 in main /home/teeworlds/src/master/src/engine/server/main.cpp:191:21
    #8 0x7fbe3d05e189 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #9 0x7fbe3d05e244 in __libc_start_main csu/../csu/libc-start.c:381:3
    #10 0x56297e77e550 in _start (/home/teeworlds/servers/DDNet-Server-ubsan+0x285550) (BuildId: 4dd9c570d72b237e02c0e986a7f986fcd8008bcd)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/teeworlds/src/master/src/base/math.h:128:20 in
/home/teeworlds/src/master/src/game/server/entities/character.cpp:1375:27: runtime error: -nan is outside the range of representable values of type 'int'
    #0 0x56297e87bf06 in CCharacter::HandleSkippableTiles(int) /home/teeworlds/src/master/src/game/server/entities/character.cpp:1375:27
    #1 0x56297e86d5cf in CCharacter::DDRacePostCoreTick() /home/teeworlds/src/master/src/game/server/entities/character.cpp:2092:2
    #2 0x56297e86c3ee in CCharacter::Tick() /home/teeworlds/src/master/src/game/server/entities/character.cpp:760:2
    #3 0x56297e951a3a in CGameWorld::Tick() /home/teeworlds/src/master/src/game/server/gameworld.cpp:287:11
    #4 0x56297e8dfcf9 in CGameContext::OnTick() /home/teeworlds/src/master/src/game/server/gamecontext.cpp:947:10
    #5 0x56297e7f90fd in CServer::Run() /home/teeworlds/src/master/src/engine/server/server.cpp:2839:19
    #6 0x56297e7bd7c4 in main /home/teeworlds/src/master/src/engine/server/main.cpp:191:21
    #7 0x7fbe3d05e189 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #8 0x7fbe3d05e244 in __libc_start_main csu/../csu/libc-start.c:381:3
    #9 0x56297e77e550 in _start (/home/teeworlds/servers/DDNet-Server-ubsan+0x285550) (BuildId: 4dd9c570d72b237e02c0e986a7f986fcd8008bcd)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/teeworlds/src/master/src/game/server/entities/character.cpp:1375:27 in
/home/teeworlds/src/master/src/game/collision.cpp:485:17: runtime error: -nan is outside the range of representable values of type 'int'
    #0 0x56297ea7ebbb in CCollision::MoveBox(vector2_base<float>*, vector2_base<float>*, vector2_base<float>, float) const /home/teeworlds/src/master/src/game/collision.cpp:485:17
    #1 0x56297ea89305 in CCharacterCore::Move() /home/teeworlds/src/master/src/game/gamecore.cpp:494:16
    #2 0x56297e86f1f3 in CCharacter::TickDeferred() /home/teeworlds/src/master/src/game/server/entities/character.cpp:794:9
    #3 0x56297e951cba in CGameWorld::Tick() /home/teeworlds/src/master/src/game/server/gameworld.cpp:296:11
    #4 0x56297e8dfcf9 in CGameContext::OnTick() /home/teeworlds/src/master/src/game/server/gamecontext.cpp:947:10
    #5 0x56297e7f90fd in CServer::Run() /home/teeworlds/src/master/src/engine/server/server.cpp:2839:19
    #6 0x56297e7bd7c4 in main /home/teeworlds/src/master/src/engine/server/main.cpp:191:21
    #7 0x7fbe3d05e189 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #8 0x7fbe3d05e244 in __libc_start_main csu/../csu/libc-start.c:381:3
    #9 0x56297e77e550 in _start (/home/teeworlds/servers/DDNet-Server-ubsan+0x285550) (BuildId: 4dd9c570d72b237e02c0e986a7f986fcd8008bcd)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/teeworlds/src/master/src/game/collision.cpp:485:17 in
/home/teeworlds/src/master/src/base/math.h:16:40: runtime error: -nan is outside the range of representable values of type 'int'
    #0 0x56297ea89e19 in round_to_int(float) /home/teeworlds/src/master/src/game/gamecore.cpp
    #1 0x56297ea89e19 in CCharacterCore::Write(CNetObj_CharacterCore*) /home/teeworlds/src/master/src/game/gamecore.cpp:551:21
    #2 0x56297ea8a806 in CCharacterCore::Quantize() /home/teeworlds/src/master/src/game/gamecore.cpp:641:2
    #3 0x56297e86f32a in CCharacter::TickDeferred() /home/teeworlds/src/master/src/game/server/entities/character.cpp:796:9
    #4 0x56297e951cba in CGameWorld::Tick() /home/teeworlds/src/master/src/game/server/gameworld.cpp:296:11
    #5 0x56297e8dfcf9 in CGameContext::OnTick() /home/teeworlds/src/master/src/game/server/gamecontext.cpp:947:10
    #6 0x56297e7f90fd in CServer::Run() /home/teeworlds/src/master/src/engine/server/server.cpp:2839:19
    #7 0x56297e7bd7c4 in main /home/teeworlds/src/master/src/engine/server/main.cpp:191:21
    #8 0x7fbe3d05e189 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #9 0x7fbe3d05e244 in __libc_start_main csu/../csu/libc-start.c:381:3
    #10 0x56297e77e550 in _start (/home/teeworlds/servers/DDNet-Server-ubsan+0x285550) (BuildId: 4dd9c570d72b237e02c0e986a7f986fcd8008bcd)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/teeworlds/src/master/src/base/math.h:16:40 in
```

**Comment by AssassinTee** [comment]
This is actually the same issue, but one if the cause of the the other
