### ISSUE TITLE
Built-in Update mechanism causing SIGABORT 

### ISSUE THREAD

**Issue by godwhoa** [ddnet/ddnet#4342]
Repro:
1) Download DDnet 5.6 Linux tarball
2) Extract and run
3) Click on "Update Now."
4) You get SIGABORT due to an assertion failure in nghttp2

Version: 5.6
OS: Ubuntu 19.10
Install Type: Linux Tarballs from ddnet.tw
libnghttp2 version: 1.39.2

I can reproduce this issue consistently, so let me know if any additional info is needed to debug this. 
```sh
[2021-11-09 14:05:24][client]: version 0.6 626fce9a778df4d4
[2021-11-09 14:05:24][http]: fetching https://info2.ddnet.tw/info?name=godwhoa
[2021-11-09 14:05:24][http]: https://master3.ddnet.tw/ddnet/15/servers.json failed. libcurl error: Could not resolve host: master3.ddnet.tw
[2021-11-09 14:05:24][http]: https://master4.ddnet.tw/ddnet/15/servers.json failed. libcurl error: Could not resolve host: master4.ddnet.tw
[2021-11-09 14:05:25][serverbrowse_http]: found master, url='https://master2.ddnet.tw/ddnet/15/servers.json' time=249ms
[2021-11-09 14:05:25][http]: task done https://info2.ddnet.tw/info?name=godwhoa
[2021-11-09 14:05:25][http]: fetching https://master2.ddnet.tw/ddnet/15/servers.json
[2021-11-09 14:05:25][http]: task done https://master2.ddnet.tw/ddnet/15/servers.json
[2021-11-09 14:05:26][serverbrowse_http]: found master, url='https://master1.ddnet.tw/ddnet/15/servers.json' time=858ms
[2021-11-09 14:05:26][serverbrowse_http]: determined best master, url='https://master2.ddnet.tw/ddnet/15/servers.json' time=249ms
[2021-11-09 14:05:27][http]: fetching https://update6.ddnet.tw/update.json
[2021-11-09 14:05:28][http]: task done https://update6.ddnet.tw/update.json
[2021-11-09 14:05:28][updater]: parsing update.json
[2021-11-09 14:05:28][http]: fetching https://update6.ddnet.tw/DDNet-Server-linux-x86_64
[2021-11-09 14:05:28][http]: fetching https://update6.ddnet.tw/DDNet-linux-x86_64
DDNet: nghttp2_session.c:2161: session_prep_frame: Assertion `session->last_sent_stream_id < frame->hd.stream_id' failed.
fish: Job 2, “./DDNet” terminated by signal SIGABRT (Abort)
```

Initially, I suspected the outdated version of libnghttp2 to be the culprit, but curl can download without any issues using the same shared library.
```sh
pacninja@pop-os:/tmp$ curl -O https://update6.ddnet.tw/DDNet-linux-x86_64
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 8495k  100 8495k    0     0  3328k      0  0:00:02  0:00:02 --:--:-- 3327k

pacninja@pop-os:/tmp$ ldd `which curl` | grep http2
	libnghttp2.so.14 => /lib/x86_64-linux-gnu/libnghttp2.so.14 (0x00007fe60c134000)

pacninja@pop-os:~/Apps/DDNet-15.6-linux_x86_64$ ldd DDNet | grep http2
	libnghttp2.so.14 => /lib/x86_64-linux-gnu/libnghttp2.so.14 (0x00007fa646337000)
```

**Comment by def-** [comment]
Works for me, even though I'm also using libnghttp2 on LInux, weird. What curl version do you have?

**Comment by godwhoa** [comment]
Here's my curl version
```
$ curl --version
curl 7.65.3 (x86_64-pc-linux-gnu) libcurl/7.65.3 OpenSSL/1.1.1c zlib/1.2.11 libidn2/2.2.0 libpsl/0.20.2 (+libidn2/2.0.5) libssh/0.9.0/openssl/zlib nghttp2/1.39.2 librtmp/2.3
Release-Date: 2019-07-19
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
```

**Comment by def-** [comment]
Can't reproduce with curl 7.60 and curl 7.79.

**Comment by godwhoa** [comment]
Now I'm getting "double free or corruption" when I hit update...
```
[2021-11-10 22:01:23][client]: version 0.6 626fce9a778df4d4
[2021-11-10 22:01:23][http]: fetching https://info2.ddnet.tw/info?name=godwhoa
[2021-11-10 22:01:23][http]: https://master4.ddnet.tw/ddnet/15/servers.json failed. libcurl error: Could not resolve host: master4.ddnet.tw
[2021-11-10 22:01:23][http]: task done https://info2.ddnet.tw/info?name=godwhoa
[2021-11-10 22:01:23][http]: fetching https://master2.ddnet.tw/ddnet/15/servers.json
[2021-11-10 22:01:23][serverbrowse_http]: found master, url='https://master1.ddnet.tw/ddnet/15/servers.json' time=432ms
[2021-11-10 22:01:24][http]: task done https://master2.ddnet.tw/ddnet/15/servers.json
[2021-11-10 22:01:24][serverbrowse_http]: found master, url='https://master2.ddnet.tw/ddnet/15/servers.json' time=255ms
[2021-11-10 22:01:24][http]: https://master3.ddnet.tw/ddnet/15/servers.json failed. libcurl error: Could not resolve host: master3.ddnet.tw
[2021-11-10 22:01:24][serverbrowse_http]: determined best master, url='https://master2.ddnet.tw/ddnet/15/servers.json' time=255ms
[2021-11-10 22:01:26][http]: fetching https://update6.ddnet.tw/update.json
[2021-11-10 22:01:26][http]: task done https://update6.ddnet.tw/update.json
[2021-11-10 22:01:26][updater]: parsing update.json
[2021-11-10 22:01:26][http]: fetching https://update6.ddnet.tw/DDNet-Server-linux-x86_64
[2021-11-10 22:01:26][http]: fetching https://update6.ddnet.tw/DDNet-linux-x86_64
double free or corruption (fasttop)
fish: Job 2, “./DDNet” terminated by signal SIGABRT (Abort)
```

**Comment by def-** [comment]
I'm not sure what to do with this since I can't reproduce it. Can you (or someone else that can reproduce this) build your own Debug client and run it with gdb (and backtrace after crash) to figure out? See https://github.com/ddnet/ddnet/#building-on-linux-and-macos

**Comment by godwhoa** [comment]
Here's the back trace after crash
```bash
[2021-11-26 20:15:29][serverbrowse_http]: determined best master, url='https://master2.ddnet.tw/ddnet/15/servers.json' time=254ms
[2021-11-26 20:15:31][http]: fetching https://update6.ddnet.tw/update.json
[New Thread 0x7fffe244f700 (LWP 2240)]
[Thread 0x7fffe244f700 (LWP 2240) exited]
[2021-11-26 20:15:32][http]: task done https://update6.ddnet.tw/update.json
[2021-11-26 20:15:32][updater]: parsing update.json
[2021-11-26 20:15:32][http]: fetching https://update6.ddnet.tw/data/languages/bulgarian.txt
[2021-11-26 20:15:32][http]: fetching https://update6.ddnet.tw/data/languages/belarusian.txt
double free or corruption (fasttop)

Thread 3 "DDNet" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffff3b12700 (LWP 2219)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt 100
#0  0x00007ffff6dfd3eb in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff6ddc899 in __GI_abort () at abort.c:79
#2  0x00007ffff6e4738e in __libc_message
    (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff6f703a5 "%s\n")
    at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff6e4f4dc in malloc_printerr
    (str=str@entry=0x7ffff6f72058 "double free or corruption (fasttop)")
    at malloc.c:5332
#4  0x00007ffff6e50e35 in _int_free (av=0x7fffe8000020, p=0x7fffe803ff40, have_lock=0)
    at malloc.c:4266
#5  0x00007ffff7b17380 in  () at /lib/x86_64-linux-gnu/libcurl.so.4
#6  0x00007ffff7b366e6 in  () at /lib/x86_64-linux-gnu/libcurl.so.4
#7  0x00007ffff7b37321 in curl_multi_perform () at /lib/x86_64-linux-gnu/libcurl.so.4
#8  0x00007ffff7b2ded4 in curl_easy_perform () at /lib/x86_64-linux-gnu/libcurl.so.4
#9  0x00005555555fe3c4 in CRequest::RunImpl(void*)
    (this=0x555557dee2d0, pHandle=0x7fffe4000d10)
    at /home/pacninja/Apps/ddnet/src/engine/client/http.cpp:163
#10 0x00005555555fe014 in CRequest::Run() (this=0x555557dee2d0)
    at /home/pacninja/Apps/ddnet/src/engine/client/http.cpp:110
#11 0x00005555557e1fad in CJobPool::RunBlocking(IJob*) (pJob=0x555557dee2d0)
    at /home/pacninja/Apps/ddnet/src/engine/shared/jobs.cpp:109
#12 0x00005555557e1da8 in CJobPool::WorkerThread(void*) (pUser=0x555555998700)
    at /home/pacninja/Apps/ddnet/src/engine/shared/jobs.cpp:78
#13 0x0000555555803802 in thread_run(void*) (user=0x55555596ca70)
    at /home/pacninja/Apps/ddnet/src/base/system.cpp:772
#14 0x00007ffff6fb1669 in start_thread (arg=<optimized out>) at pthread_create.c:479
#15 0x00007ffff6ed92b3 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

```

**Comment by godwhoa** [comment]
Here's the backtrace for assertion failure:
```bash
* Connection #5 to host master1.ddnet.tw left intact
[2021-11-26 23:16:36][serverbrowse_http]: found master, url='https://master1.ddnet.tw/ddnet/15/servers.json' time=492ms
[2021-11-26 23:16:36][serverbrowse_http]: determined best master, url='https://master2.ddnet.tw/ddnet/15/servers.json' time=251ms
[2021-11-26 23:16:36][http]: fetching https://update6.ddnet.tw/update.json
[New Thread 0x7fffe1a1e700 (LWP 19881)]
*   Trying 104.21.78.207:443...
* TCP_NODELAY set
[Thread 0x7fffe1a1e700 (LWP 19881) exited]
* Connected to update6.ddnet.tw (104.21.78.207) port 443 (#6)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Cloudflare, Inc.; CN=sni.cloudflaressl.com
*  start date: Jul 19 00:00:00 2021 GMT
*  expire date: Jul 18 23:59:59 2022 GMT
*  subjectAltName: host "update6.ddnet.tw" matched cert's "*.ddnet.tw"
*  issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fffe8033100)
> GET /update.json HTTP/2
Host: update6.ddnet.tw
User-Agent: DDNet 15.6 (linux; amd64)
Accept: */*
Accept-Encoding: deflate, gzip

* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 256)!
< HTTP/2 200 
< date: Fri, 26 Nov 2021 17:46:37 GMT
< content-type: application/json
< last-modified: Thu, 25 Nov 2021 23:23:42 GMT
< vary: Accept-Encoding
< etag: W/"61a01afe-8f03"
< strict-transport-security: max-age=15768000
< content-encoding: gzip
< cf-cache-status: DYNAMIC
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=BtROvqTQOdTNXwFpWnydtgpsDJjHfxGyQsIkdLPA4wrtSihWbG8qvEFr7mACmLJsSEYzTajFpZq7XqMOt2sPFs4uNuHIGBTG7lOCoI2K8g4%2FFTdmjhYIWMR8yVE8tjLSpWB9"}],"group":"cf-nel","max_age":604800}
< nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< server: cloudflare
< cf-ray: 6b44efed5aefc928-HYD
< 
* Connection cache is full, closing the oldest one.
* Closing connection 0
* Connection #6 to host update6.ddnet.tw left intact
[2021-11-26 23:16:37][http]: task done https://update6.ddnet.tw/update.json
[2021-11-26 23:16:37][updater]: parsing update.json
[2021-11-26 23:16:37][http]: fetching https://update6.ddnet.tw/data/languages/bulgarian.txt
[2021-11-26 23:16:37][http]: fetching https://update6.ddnet.tw/data/languages/belarusian.txt
* Found bundle for host update6.ddnet.tw: 0x7fffe8026d50 [can multiplex]
* Re-using existing connection! (#6) with host update6.ddnet.tw
* Found bundle for host update6.ddnet.tw: 0x7fffe8026d50 [can multiplex]
* Connected to ��� (104.21.78.207) port 443 (#6)
* Re-using existing connection! (#6) with host update6.ddnet.tw
* Using Stream ID: 3 (easy handle 0x7fffe8006850)
* Using Stream ID: 5 (easy handle 0x7fffe8006850)
DDNet: nghttp2_session.c:2161: session_prep_frame: Assertion `session->last_sent_stream_id < frame->hd.stream_id' failed.
> GET /data/languages/belarusian.txt HTTP/2
Host: update6.ddnet.tw
User-Agent: DDNet 15.6 (linux; amd64)
Accept: */*
Accept-Encoding: deflate, gzip

* Connection died, retrying a fresh connect
* Issue another request to this URL: 'https://update6.ddnet.tw/data/languages/belarusian.txt'
* Found bundle for host update6.ddnet.tw: 0x7fffe8026d50 [can multiplex]
* Hostname update6.ddnet.tw was found in DNS cache
*   Trying 104.21.78.207:443...
* TCP_NODELAY set
* Connected to update6.ddnet.tw (104.21.78.207) port 443 (#7)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSL re-using session ID

Thread 4 "DDNet" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffff3311700 (LWP 19847)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt 1000
#0  0x00007ffff6dfd3eb in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff6ddc899 in __GI_abort () at abort.c:79
#2  0x00007ffff6ddc769 in __assert_fail_base
    (fmt=0x7ffff6f70fb8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x7ffff6da0568 "session->last_sent_stream_id < frame->hd.stream_id", file=0x7ffff6d9fc9d "nghttp2_session.c", line=2161, function=<optimized out>) at assert.c:92
#3  0x00007ffff6dee006 in __GI___assert_fail
    (assertion=0x7ffff6da0568 "session->last_sent_stream_id < frame->hd.stream_id", file=0x7ffff6d9fc9d "nghttp2_session.c", line=2161, function=0x7ffff6d9fb10 "session_prep_frame") at assert.c:101
#4  0x00007ffff6d95ac7 in  () at /lib/x86_64-linux-gnu/libnghttp2.so.14
#5  0x00007ffff6d95c99 in nghttp2_session_send ()
    at /lib/x86_64-linux-gnu/libnghttp2.so.14
#6  0x00007ffff7b525e6 in  () at /lib/x86_64-linux-gnu/libcurl.so.4
#7  0x00007ffff7b19c8e in  () at /lib/x86_64-linux-gnu/libcurl.so.4
#8  0x00007ffff7b155ed in  () at /lib/x86_64-linux-gnu/libcurl.so.4
#9  0x00007ffff7b17ed5 in  () at /lib/x86_64-linux-gnu/libcurl.so.4
#10 0x00007ffff7b366e6 in  () at /lib/x86_64-linux-gnu/libcurl.so.4
#11 0x00007ffff7b37321 in curl_multi_perform () at /lib/x86_64-linux-gnu/libcurl.so.4
#12 0x00007ffff7b2ded4 in curl_easy_perform () at /lib/x86_64-linux-gnu/libcurl.so.4
#13 0x00005555555fe3ba in CRequest::RunImpl(void*)
    (this=0x555557cf7a60, pHandle=0x7fffe8006850)
    at /home/pacninja/Apps/ddnet/src/engine/client/http.cpp:161
#14 0x00005555555fe014 in CRequest::Run() (this=0x555557cf7a60)
    at /home/pacninja/Apps/ddnet/src/engine/client/http.cpp:110
#15 0x00005555557e1fa3 in CJobPool::RunBlocking(IJob*) (pJob=0x555557cf7a60)
    at /home/pacninja/Apps/ddnet/src/engine/shared/jobs.cpp:109
#16 0x00005555557e1d9e in CJobPool::WorkerThread(void*) (pUser=0x555555998700)
    at /home/pacninja/Apps/ddnet/src/engine/shared/jobs.cpp:78
#17 0x00005555558037f8 in thread_run(void*) (user=0x55555596c9b0)
    at /home/pacninja/Apps/ddnet/src/base/system.cpp:772
#18 0x00007ffff6fb1669 in start_thread (arg=<optimized out>) at pthread_create.c:479
#19 0x00007ffff6ed92b3 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
This bug isn't as reproducible as I initially thought, might have something to do with my network being flaky.
Was able to replicate the issue on all runs when I initially reported this issue.
Right now it's like 1 in every 5 runs and then it varies between a double free and an assertion failure.

**Comment by godwhoa** [comment]
Ok, I think I tracked it down, it's a bug in libcurl.
https://github.com/curl/curl/commit/ee263de7a378e701f15e58879f36fdcfe8742006

From libcurl's docs:

>CURL_LOCK_DATA_CONNECT
>
>Put the connection cache in the share object and make all easy handles using this share object share the connection cache.
>Note that due to a known bug, it is not safe to share connections this way between multiple concurrent threads.
>Connections that are used for HTTP/1.1 Pipelining or HTTP/2 multiplexing only get additional transfers added to them if the existing connection is held by the same multi or easy handle. libcurl does not support doing HTTP/2 streams in different threads using a shared connection.
>Support for CURL_LOCK_DATA_CONNECT was added in 7.57.0, but the symbol existed before this.
>Note that when you use the multi interface, all easy handles added to the same multi handle will share connection cache by default without using this option.

**libcurl does not support doing HTTP/2 streams in different threads using a shared connection.**

@def- any thoughts on how to fix this? I'm thinking maybe disabling connection reuse would be an easy fix.

**Comment by def-** [comment]
@Learath2 any idea? ^

**Comment by Learath2** [comment]
Well an easy way to check your hypothesis would be to disable connection reuse indeed. I'll try to reproduce in the meanwhile.

**Comment by godwhoa** [comment]
With connection resuse: 5/10 runs resulted in a crash.
Without connection reuse: 0/10 runs resulted in a crash.
