### ISSUE TITLE
Crash in CSaveTeam::Load(int, bool) 

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#4386]
```
=================================================================
==2383146==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x619000baeeb8 at pc 0x000000600813 bp 0x7ffdeb6424d0 sp 0x7ffdeb6424c8
READ of size 4 at 0x619000baeeb8 thread T0
    #0 0x600812 in CSaveTeam::Load(int, bool) /home/teeworlds/src/master/src/game/server/save.cpp:533:95
    #1 0x62d1a7 in CGameTeams::ProcessSaveTeam() /home/teeworlds/src/master/src/game/server/teams.cpp:949:42
    #2 0x5da171 in CGameControllerDDRace::Tick() /home/teeworlds/src/master/src/game/server/gamemodes/DDRace.cpp:163:10
    #3 0x59f76f in CGameContext::OnTick() /home/teeworlds/src/master/src/game/server/gamecontext.cpp:813:17
    #4 0x529ad2 in CServer::Run() /home/teeworlds/src/master/src/engine/server/server.cpp:2625:19
    #5 0x535e90 in main /home/teeworlds/src/master/src/engine/server/server.cpp:3636:21
    #6 0x7f1d3ca04d09 in __libc_start_main csu/../csu/libc-start.c:308:16
    #7 0x44cb79 in _start (/home/teeworlds/servers/DDNet-Server-asan+0x44cb79)

0x619000baeeb8 is located 0 bytes to the right of 1080-byte region [0x619000baea80,0x619000baeeb8)
allocated by thread T1 here:
    #0 0x4f699d in operator new[](unsigned long) (/home/teeworlds/servers/DDNet-Server-asan+0x4f699d)
    #1 0x601a4a in CSaveTeam::FromString(char const*) /home/teeworlds/src/master/src/game/server/save.cpp:682:18
    #2 0x61af73 in CScore::LoadTeamThread(IDbConnection*, ISqlData const*, bool, char*, int) /home/teeworlds/src/master/src/game/server/score.cpp:1861:33
    #3 0x4ff9e0 in CDbConnectionPool::ExecSqlFunc(IDbConnection*, CSqlExecData*, bool) /home/teeworlds/src/master/src/engine/server/databases/connection_pool.cpp:218:14
    #4 0x4ff10c in CDbConnectionPool::Worker() /home/teeworlds/src/master/src/engine/server/databases/connection_pool.cpp:170:8
    #5 0x4fe199 in CDbConnectionPool::Worker(void*) /home/teeworlds/src/master/src/engine/server/databases/connection_pool.cpp:128:9
    #6 0x6f4a5f in thread_run(void*) /home/teeworlds/src/master/src/base/system.cpp:746:2
    #7 0x7f1d3cbcdea6 in start_thread nptl/pthread_create.c:477:8

Thread T1 created by T0 here:
    #0 0x4b161a in pthread_create (/home/teeworlds/servers/DDNet-Server-asan+0x4b161a)
    #1 0x6f4c91 in thread_init /home/teeworlds/src/master/src/base/system.cpp:758:16
    #2 0x6f4c91 in thread_init_and_detach /home/teeworlds/src/master/src/base/system.cpp:829:17
    #3 0x4fe15c in CDbConnectionPool::CDbConnectionPool() /home/teeworlds/src/master/src/engine/server/databases/connection_pool.cpp:61:2
    #4 0x510452 in CServer::CServer() /home/teeworlds/src/master/src/engine/server/server.cpp:323:26
    #5 0x53560b in CreateServer() /home/teeworlds/src/master/src/engine/server/server.cpp:3537:45
    #6 0x53560b in main /home/teeworlds/src/master/src/engine/server/server.cpp:3566:21
    #7 0x7f1d3ca04d09 in __libc_start_main csu/../csu/libc-start.c:308:16

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/teeworlds/src/master/src/game/server/save.cpp:533:95 in CSaveTeam::Load(int, bool)
Shadow bytes around the buggy address:
  0x0c328016dd80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c328016dd90: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c328016dda0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c328016ddb0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c328016ddc0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c328016ddd0: 00 00 00 00 00 00 00[fa]fa fa fa fa fa fa fa fa
  0x0c328016dde0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c328016ddf0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c328016de00: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c328016de10: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c328016de20: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==2383146==ABORTING
```

**Comment by def-** [comment]
```
[2021-11-23 09:23:57][console]: executing 'maps/Jao Shooter.map.cfg'
[2021-11-23 09:23:57][censorlist]: failed to open 'censorlist.txt'
[2021-11-23 09:23:57][teehistorian]: recording to 'teehistorian/bc35b428-5780-4b3d-a304-b1aa540282d9.teehistorian'
[2021-11-23 09:23:57][sql]: load best time done on read database 0
[2021-11-23 09:23:57][git-revision]: f0ab52bf4c7c07f0
[2021-11-23 09:23:57][server]: player is ready. ClientID=0 addr=<{XXX:14444}> secure=yes
[2021-11-23 09:23:58][server]: player has entered the game. ClientID=0 addr=<{XXX:14444}> sixup=0
[2021-11-23 09:23:58][sql]: load player data done on read database 0
[2021-11-23 09:23:59][ddnet]: cid=0 version=15062
[2021-11-23 09:24:02][chat-command]: 0 used /timeout XXX
[2021-11-23 09:24:03][chat-command]: 0 used /pause
[2021-11-23 09:24:05][chat-command]: 0 used /pause
[2021-11-23 09:24:08][server]: player is ready. ClientID=1 addr=<{XXX:14440}> secure=yes
[2021-11-23 09:24:08][server]: player has entered the game. ClientID=1 addr=<{XXX:14440}> sixup=0
[2021-11-23 09:24:08][game]: team_join player='1:314' team=0
[2021-11-23 09:24:08][chat]: *** '314' entered and joined the game
[2021-11-23 09:24:08][ddnet]: cid=1 version=15062
[2021-11-23 09:24:08][host_lookup]: host='XXX.blocklist' port=0 1
[2021-11-23 09:24:08][sql]: load player data done on read database 0
[2021-11-23 09:24:10][chat]: *** 314 joined team 29
[2021-11-23 09:24:10][chat-command]: 1 used /team 29
[2021-11-23 09:24:10][join]: You can't change teams that fast!
[2021-11-23 09:24:10][chat-command]: 1 used /team 29
[2021-11-23 09:24:11][chat-command]: 0 used /timeout XXX
[2021-11-23 09:24:11][chat]: *** тυx joined team 29
[2021-11-23 09:24:11][chat-command]: 0 used /team 29
[2021-11-23 09:24:12][chat-command]: 0 used /lock
[2021-11-23 09:24:14][chat-command]: 0 used /load XXX
[2021-11-23 09:24:14][sql]: load team done on write database 0
```

**Comment by def-** [comment]
The save is too old, so I can't get it from DB anymore.
