### ISSUE TITLE
Crash with: "error getting int: NULL"

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#4500]
```
Program terminated with signal SIGILL, Illegal instruction.
#0  dbg_break () at /home/teeworlds/src/master/src/base/system.cpp:124
124		__builtin_trap();
[Current thread is 1 (Thread 0x7f26a34a7700 (LWP 14685))]
(gdb) bt
#0  dbg_break () at /home/teeworlds/src/master/src/base/system.cpp:124
#1  dbg_assert_imp (filename=<optimized out>, line=<optimized out>,
    msg=msg@entry=0x55a6ac660ade "error getting int: NULL", test=0)
    at /home/teeworlds/src/master/src/base/system.cpp:117
#2  0x000055a6ac5a4e67 in dbg_assert_imp (
    filename=filename@entry=0x55a6ac660cc0 "/home/teeworlds/src/master/src/engine/server/databases/mysql.cpp",
    line=line@entry=569, test=test@entry=0, msg=msg@entry=0x55a6ac660ade "error getting int: NULL")
    at /home/teeworlds/src/master/src/base/system.cpp:119
#3  0x000055a6ac5a9e79 in CMysqlConnection::GetInt (this=0x55a6ad654510, Col=<optimized out>)
    at /home/teeworlds/src/master/src/engine/server/databases/mysql.cpp:569
#4  0x000055a6ac5fd3a2 in CScoreWorker::GetSaves (pSqlServer=0x7f26a34a6620, pGameData=<optimized out>,
    pError=0x7f26a34a6d30 "error message not initialized", ErrorSize=256)
    at /home/teeworlds/src/master/src/game/server/scoreworker.cpp:1644
#5  0x000055a6ac5a8afa in CDbConnectionPool::ExecSqlFunc (this=this@entry=0x55a6ad60afd0, pConnection=0x55a6ad654510,
    pData=pData@entry=0x55a6ad863a70, Failure=Failure@entry=false) at /usr/include/c++/10/bits/unique_ptr.h:173
#6  0x000055a6ac5a8d5a in CDbConnectionPool::Worker (this=0x55a6ad60afd0) at /usr/include/c++/10/bits/unique_ptr.h:173
#7  0x000055a6ac64de27 in thread_run (user=<optimized out>) at /home/teeworlds/src/master/src/base/system.cpp:763
#8  0x00007f26a450dea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#9  0x00007f26a443ddef in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by def-** [comment]
```
[2021-12-20 23:36:29][chat]: *** 'felp' has left the game
[2021-12-20 23:36:29][game]: leave player='0:felp'
[2021-12-20 23:36:29][sql]: Waiting for score-threads to complete (0s)
[2021-12-20 23:36:29][mysql]: can't deinitialize, connections remaining: 2
```
