### ISSUE TITLE
Crash on startup with desktop fullscreen on macOS

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#4532]
```
=================================================================
==11701==ERROR: AddressSanitizer: global-buffer-overflow on address 0x000101b17218 at pc 0x000100a91478 bp 0x00016fbc4310 sp 0x00016fbc4308
READ of size 8 at 0x000101b17218 thread T0
    #0 0x100a91474 in CKillMessages::OnInit() killmessages.cpp:62
    #1 0x100e4506c in CGameClient::OnInit() gameclient.cpp:249
    #2 0x10061bff8 in CClient::Run() client.cpp:3142
    #3 0x10064e31c in TWMain client.cpp:4489
    #4 0x1008e65dc in main client.m:22
    #5 0x1020550f0 in start+0x204 (dyld:arm64e+0x50f0)

0x000101b17218 is located 8 bytes to the right of global variable 'x1887' defined in '/Users/deen/git/ddnet/src/game/generated/client_data.cpp:502:24' (0x101b17000) of size 528
SUMMARY: AddressSanitizer: global-buffer-overflow killmessages.cpp:62 in CKillMessages::OnInit()
Shadow bytes around the buggy address:
  0x007020382df0: 00 00 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x007020382e00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x007020382e10: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x007020382e20: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x007020382e30: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x007020382e40: 00 00 f9[f9]f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9 f9
  0x007020382e50: f9 f9 f9 f9 00 f9 f9 f9 f9 f9 f9 f9 00 f9 f9 f9
  0x007020382e60: f9 f9 f9 f9 00 f9 f9 f9 f9 f9 f9 f9 00 f9 f9 f9
  0x007020382e70: f9 f9 f9 f9 00 f9 f9 f9 f9 f9 f9 f9 00 f9 f9 f9
  0x007020382e80: f9 f9 f9 f9 00 f9 f9 f9 f9 f9 f9 f9 00 f9 f9 f9
  0x007020382e90: f9 f9 f9 f9 00 f9 f9 f9 f9 f9 f9 f9 00 f9 f9 f9
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==11701==ABORTING
```

**Comment by def-** [comment]
My bad, had some WIP code around :D
