### ISSUE TITLE
double free or corruption (!prev)

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#4785]
```
Core was generated by `./DDRace64-Server_sql -f servers/8311.cfg'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f6657d22b80 (LWP 2466233))]
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f6657dfe537 in __GI_abort () at abort.c:79
#2  0x00007f6657e57768 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7f6657f65e2d "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007f6657e5ea5a in malloc_printerr (str=str@entry=0x7f6657f68230 "double free or corruption (!prev)") at malloc.c:5347
#4  0x00007f6657e6009c in _int_free (av=0x7f6657f97b80 <main_arena>, p=0x55b8dc283610, have_lock=<optimized out>) at malloc.c:4317
#5  0x000055b8db80f151 in __gnu_cxx::new_allocator<std::_List_node<CServer::CCache::CCacheChunk> >::deallocate (__t=1, __p=<optimized out>, this=0x7f6657d0b4d8) at /usr/include/c++/10/ext/new_allocator.h:120
#6  std::allocator_traits<std::allocator<std::_List_node<CServer::CCache::CCacheChunk> > >::deallocate (__n=1, __p=<optimized out>, __a=...) at /usr/include/c++/10/bits/alloc_traits.h:492
#7  std::__cxx11::_List_base<CServer::CCache::CCacheChunk, std::allocator<CServer::CCache::CCacheChunk> >::_M_put_node (__p=<optimized out>, this=0x7f6657d0b4d8) at /usr/include/c++/10/bits/stl_list.h:446
#8  std::__cxx11::_List_base<CServer::CCache::CCacheChunk, std::allocator<CServer::CCache::CCacheChunk> >::_M_clear (this=0x7f6657d0b4d8) at /usr/include/c++/10/bits/list.tcc:81
#9  std::__cxx11::list<CServer::CCache::CCacheChunk, std::allocator<CServer::CCache::CCacheChunk> >::clear (this=0x7f6657d0b4d8) at /usr/include/c++/10/bits/stl_list.h:1500
#10 CServer::CCache::Clear (this=0x7f6657d0b4d8) at /home/teeworlds/src/master/src/engine/server/server.cpp:1811
#11 CServer::CacheServerInfoSixup (this=this@entry=0x7f6656f81010, pCache=pCache@entry=0x7f6657d0b4d8, SendClients=SendClients@entry=true) at /home/teeworlds/src/master/src/engine/server/server.cpp:2012
#12 0x000055b8db80f826 in CServer::UpdateServerInfo (this=this@entry=0x7f6656f81010, Resend=Resend@entry=false) at /home/teeworlds/src/master/src/engine/server/server.cpp:2156
#13 0x000055b8db81365d in CServer::UpdateServerInfo (Resend=false, this=0x7f6656f81010) at /home/teeworlds/src/master/src/engine/server/server.cpp:2148
#14 CServer::Run (this=this@entry=0x7f6656f81010) at /home/teeworlds/src/master/src/engine/server/server.cpp:2679
#15 0x000055b8db7fe5fd in main (argc=<optimized out>, argv=<optimized out>) at /home/teeworlds/src/master/src/engine/server/server.cpp:3732
```
happened on official server. @Learath2 UpdateServerInfo sounds like something you added a while ago, any idea?

**Comment by def-** [comment]
Similar one on another official server:
```
Core was generated by `./DDRace64-Server_sql -f servers/8311.cfg'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f6657d22b80 (LWP 2466233))]
(gdb) bt
#0  __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f6657dfe537 in __GI_abort () at abort.c:79
#2  0x00007f6657e57768 in __libc_message (
    action=action@entry=do_abort, 
    fmt=fmt@entry=0x7f6657f65e2d "%s\n")
    at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007f6657e5ea5a in malloc_printerr (
    str=str@entry=0x7f6657f68230 "double free or corruption (!prev)") at malloc.c:5347
#4  0x00007f6657e6009c in _int_free (
    av=0x7f6657f97b80 <main_arena>, p=0x55b8dc283610, 
    have_lock=<optimized out>) at malloc.c:4317
#5  0x000055b8db80f151 in __gnu_cxx::new_allocator<std::_List_node<CServer::CCache::CCacheChunk> >::deallocate (__t=1, 
    __p=<optimized out>, this=0x7f6657d0b4d8)
    at /usr/include/c++/10/ext/new_allocator.h:120
--Type <RET> for more, q to quit, c to continue without paging--
CCache::CCacheChunk> > >::deallocate (__n=1, __p=<optimized out>, __a=...) at /usr/include/c++/10/bits/alloc_traits.h:492
#7  std::__cxx11::_List_base<CServer::CCache::CCacheChunk, std::allocator<CServer::CCache::CCacheChunk> >::_M_put_node (__p=<optimized out>, this=0x7f6657d0b4d8) at /usr/include/c++/10/bits/stl_list.h:446
#8  std::__cxx11::_List_base<CServer::CCache::CCacheChunk, std::allocator<CServer::CCache::CCacheChunk> >::_M_clear (this=0x7f6657d0b4d8) at /usr/include/c++/10/bits/list.tcc:81
#9  std::__cxx11::list<CServer::CCache::CCacheChunk, std::allocator<CServer::CCache::CCacheChunk> >::clear (this=0x7f6657d0b4d8) at /usr/include/c++/10/bits/stl_list.h:1500
#10 CServer::CCache::Clear (this=0x7f6657d0b4d8) at /home/teeworlds/src/master/src/engine/server/server.cpp:1811
#11 CServer::CacheServerInfoSixup (this=this@entry=0x7f6656f81010, pCache=pCache@entry=0x7f6657d0b4d8, SendClients=SendClients@entry=true) at /home/teeworlds/src/master/src/engine/server/server.cpp:2012
#12 0x000055b8db80f826 in CServer::UpdateServerInfo (this=this@entry=0x7f6656f81010, Resend=Resend@entry=false) at /home/teeworlds/src/master/src/engine/server/server.cpp:2156
#13 0x000055b8db81365d in CServer::UpdateServerInfo (Resend=false, this=0x7f6656f81010) at /home/teeworlds/src/master/src/engine/server/server.cpp:2148
#14 CServer::Run (this=this@entry=0x7f6656f81010) at /home/teeworlds/src/master/src/engine/server/server.cpp:2679
#15 0x000055b8db7fe5fd in main (argc=<optimized out>, argv=<optimized out>) at /home/teeworlds/src/master/src/engine/server/server.cpp:3732
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f6657dfe537 in __GI_abort () at abort.c:79
#2  0x00007f6657e57768 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7f6657f65e2d "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007f6657e5ea5a in malloc_printerr (str=str@entry=0x7f6657f68230 "double free or corruption (!prev)") at malloc.c:5347
#4  0x00007f6657e6009c in _int_free (av=0x7f6657f97b80 <main_arena>, p=0x55b8dc283610, have_lock=<optimized out>) at malloc.c:4317
#5  0x000055b8db80f151 in __gnu_cxx::new_allocator<std::_List_node<CServer::CCache::CCacheChunk> >::deallocate (__t=1, __p=<optimized out>, this=0x7f6657d0b4d8) at /usr/include/c++/10/ext/new_allocator.h:120
#6  std::allocator_traits<std::allocator<std::_List_node<CServer::CCache::CCacheChunk> > >::deallocate (__n=1, __p=<optimized out>, __a=...) at /usr/include/c++/10/bits/alloc_traits.h:492
#7  std::__cxx11::_List_base<CServer::CCache::CCacheChunk, std::allocator<CServer::CCache::CCacheChunk> >::_M_put_node (__p=<optimized out>, this=0x7f6657d0b4d8) at /usr/include/c++/10/bits/stl_list.h:446
#8  std::__cxx11::_List_base<CServer::CCache::CCacheChunk, std::allocator<CServer::CCache::CCacheChunk> >::_M_clear (this=0x7f6657d0b4d8) at /usr/include/c++/10/bits/list.tcc:81
#9  std::__cxx11::list<CServer::CCache::CCacheChunk, std::allocator<CServer::CCache::CCacheChunk> >::clear (this=0x7f6657d0b4d8) at /usr/include/c++/10/bits/stl_list.h:1500
#10 CServer::CCache::Clear (this=0x7f6657d0b4d8) at /home/teeworlds/src/master/src/engine/server/server.cpp:1811
#11 CServer::CacheServerInfoSixup (this=this@entry=0x7f6656f81010, pCache=pCache@entry=0x7f6657d0b4d8, SendClients=SendClients@entry=true) at /home/teeworlds/src/master/src/engine/server/server.cpp:2012
#12 0x000055b8db80f826 in CServer::UpdateServerInfo (this=this@entry=0x7f6656f81010, Resend=Resend@entry=false) at /home/teeworlds/src/master/src/engine/server/server.cpp:2156
#13 0x000055b8db81365d in CServer::UpdateServerInfo (Resend=false, this=0x7f6656f81010) at /home/teeworlds/src/master/src/engine/server/server.cpp:2148
#14 CServer::Run (this=this@entry=0x7f6656f81010) at /home/teeworlds/src/master/src/engine/server/server.cpp:2679
#15 0x000055b8db7fe5fd in main (argc=<optimized out>, argv=<optimized out>) at /home/teeworlds/src/master/src/engine/server/server.cpp:3732
```

**Comment by def-** [comment]
```
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffb244ed537 in __GI_abort () at abort.c:79
#2  0x00007ffb24546768 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffb24654e2d "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007ffb2454da5a in malloc_printerr (str=str@entry=0x7ffb24657230 "double free or corruption (!prev)") at malloc.c:5347
#4  0x00007ffb2454f09c in _int_free (av=0x7ffb24686b80 <main_arena>, p=0x555c19f8a600, have_lock=<optimized out>) at malloc.c:4317
#5  0x0000555c192451e1 in __gnu_cxx::new_allocator<std::_List_node<CServer::CCache::CCacheChunk> >::deallocate (__t=1, __p=<optimized out>, this=0x7ffb243faeb0) at /usr/include/c++/10/ext/new_allocator.h:120
#6  std::allocator_traits<std::allocator<std::_List_node<CServer::CCache::CCacheChunk> > >::deallocate (__n=1, __p=<optimized out>, __a=...) at /usr/include/c++/10/bits/alloc_traits.h:492
#7  std::__cxx11::_List_base<CServer::CCache::CCacheChunk, std::allocator<CServer::CCache::CCacheChunk> >::_M_put_node (__p=<optimized out>, this=0x7ffb243faeb0) at /usr/include/c++/10/bits/stl_list.h:446
#8  std::__cxx11::_List_base<CServer::CCache::CCacheChunk, std::allocator<CServer::CCache::CCacheChunk> >::_M_clear (this=0x7ffb243faeb0) at /usr/include/c++/10/bits/list.tcc:81
#9  std::__cxx11::list<CServer::CCache::CCacheChunk, std::allocator<CServer::CCache::CCacheChunk> >::clear (this=0x7ffb243faeb0) at /usr/include/c++/10/bits/stl_list.h:1500
#10 CServer::CCache::Clear (this=0x7ffb243faeb0) at /home/teeworlds/src/master/src/engine/server/server.cpp:1807
#11 CServer::CacheServerInfoSixup (this=this@entry=0x7ffb236a3010, pCache=pCache@entry=0x7ffb243faeb0, SendClients=SendClients@entry=true) at /home/teeworlds/src/master/src/engine/server/server.cpp:2008
#12 0x0000555c192458b7 in CServer::UpdateServerInfo (this=this@entry=0x7ffb236a3010, Resend=Resend@entry=false) at /home/teeworlds/src/master/src/engine/server/server.cpp:2152
#13 0x0000555c19249704 in CServer::UpdateServerInfo (Resend=false, this=0x7ffb236a3010) at /home/teeworlds/src/master/src/engine/server/server.cpp:2144
#14 CServer::Run (this=this@entry=0x7ffb236a3010) at /home/teeworlds/src/master/src/engine/server/server.cpp:2671
#15 0x0000555c1923464d in main (argc=<optimized out>, argv=<optimized out>) at /home/teeworlds/src/master/src/engine/server/server.cpp:3724
```
