### ISSUE TITLE
Switching to vulkan and restarting will crash

### ISSUE THREAD

**Issue by Chairn** [ddnet/ddnet#4891]
As the game crash on start, once people switched, they can't change the renderer option back without twiddling in the cfg file. It should at least revert back to a base graphic renderer.

```shell
[2022-03-24 19:48:31][client]: starting...
[2022-03-24 19:48:31][sdl]: SDL version 2.0.8 (compiled = 2.0.8)
[2022-03-24 19:48:31][gfx]: Created Vulkan 1.0 context.
[2022-03-24 19:48:32][vulkan]: vulkan error: No vulkan compatible devices found.
[2022-03-24 19:48:32][assert]: ../src/engine/client/backend/vulkan/backend_vulkan.cpp(1094): No vulkan compatible devices found.
Illegal instruction (core dumped)
#0  0x00005555555deea6 in dbg_break() () at ../src/base/system.cpp:207
#1  0x00005555555dee7c in dbg_assert_imp(char const*, int, int, char const*) (filename=0x555555908208 "../src/engine/client/backend/vulkan/backend_vulkan.cpp", line=1094, test=0, msg=0x7fffffff7f50 "No vulkan compatible devices found.") at ../src/base/system.cpp:200
#2  0x00005555556302ed in CCommandProcessorFragment_Vulkan::SetError(char const*, char const*) (this=0x5555560dd550, pErr=0x5555559088c8 "No vulkan compatible devices found.", pErrStrExtra=0x0) at ../src/engine/client/backend/vulkan/backend_vulkan.cpp:1094
#3  0x000055555563cd29 in CCommandProcessorFragment_Vulkan::SelectGPU(char*, char*, char*) (this=0x5555560dd550, pRendererName=0x555555d80914 "", pVendorName=0x555555d80714 "", pVersionName=0x555555d80814 "") at ../src/engine/client/backend/vulkan/backend_vulkan.cpp:3438
#4  0x00005555556432c3 in CCommandProcessorFragment_Vulkan::InitVulkanSDL(SDL_Window*, unsigned int, unsigned int, char*, char*, char*) (this=0x5555560dd550, pWindow=0x555555dec1c0, CanvasWidth=1366, CanvasHeight=768, pRendererString=0x555555d80914 "", pVendorString=0x555555d80714 "", pVersionString=0x555555d80814 "")
    at ../src/engine/client/backend/vulkan/backend_vulkan.cpp:5239
#5  0x000055555564a77e in CCommandProcessorFragment_Vulkan::Cmd_PreInit(CCommandProcessorFragment_GLBase::SCommand_PreInit const*) (this=0x5555560dd550, pCommand=0x555555dbf050)
    at ../src/engine/client/backend/vulkan/backend_vulkan.cpp:6947
#6  0x0000555555646279 in CCommandProcessorFragment_Vulkan::RunCommand(CCommandBuffer::SCommand const*) (this=0x5555560dd550, pBaseCommand=0x555555dbf050)
    at ../src/engine/client/backend/vulkan/backend_vulkan.cpp:6074
#7  0x00005555556c946f in CCommandProcessor_SDL_GL::RunBuffer(CCommandBuffer*) (this=0x5555560d0950, pBuffer=0x7fffffff8940) at ../src/engine/client/backend_sdl.cpp:245
#8  0x00005555556c8ecb in CGraphicsBackend_Threaded::RunBufferSingleThreadedUnsafe(CCommandBuffer*) (this=0x555555d80500, pBuffer=0x7fffffff8940) at ../src/engine/client/backend_sdl.cpp:135
#9  0x00005555556cb890 in CGraphicsBackend_SDL_GL::Init(char const*, int*, int*, int*, int*, int, int, int*, int*, int*, int*, IStorage*) (this=0x555555d80500, pName=0x55555590fbd4 "DDNet Client", pScreen=0x555555c1fab0 <g_Config+4144>, pWidth=0x555555c1fab4 <g_Config+4148>, pHeight=0x555555c1fab8 <g_Config+4152>, pRefreshRate=0x555555c1fabc <g_Config+4156>, FsaaSamples=0, Flags=21, pDesktopWidth=0x555555c1fac0 <g_Config+4160>, pDesktopHeight=0x555555c1fac4 <g_Config+4164>, pCurrentWidth=0x7fffd9869020, pCurrentHeight=0x7fffd9869024, pStorage=0x555555d28aa0)
    at ../src/engine/client/backend_sdl.cpp:1106
#10 0x00005555556fead4 in CGraphics_Threaded::IssueInit() (this=0x7fffd9869010)
    at ../src/engine/client/graphics_threaded.cpp:2247
#11 0x00005555556fee81 in CGraphics_Threaded::InitWindow() (this=0x7fffd9869010)
    at ../src/engine/client/graphics_threaded.cpp:2304
#12 0x00005555556ff38f in CGraphics_Threaded::Init() (this=0x7fffd9869010)
    at ../src/engine/client/graphics_threaded.cpp:2443
#13 0x00005555556dcc36 in CClient::Run() (this=0x7fffdb53d010)
    at ../src/engine/client/client.cpp:2872
#14 0x00005555556e609d in main(int, char const**) (argc=1, argv=0x7fffffffd5e8)
    at ../src/engine/client/client.cpp:4458
```

**Comment by Jupeyy** [comment]
Btw i tested this on win7 VM, which obviously has no vulkan driver and at least there it also failed cleanly as documented
