### ISSUE TITLE
move_sqlite.py: UnicodeEncodeError: 'latin-1' codec can't encode characters in position 43-46: ordinal not in range(256)

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#4902]
```
Traceback (most recent call last):
  File "/home/teeworlds/servers/scripts/move_sqlite.py", line 105, in <module>
    main()
  File "/home/teeworlds/servers/scripts/move_sqlite.py", line 102, in main
    transfer(args.f, args.to)
  File "/home/teeworlds/servers/scripts/move_sqlite.py", line 40, in transfer
    print(line)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 43-46: ordinal not in range(256)
```
Happens with scripts/move_sqlite.py on CHN1 and is blocking ranks from being inserted. I'll check later. sqlite file: 
[ddnet-server.sqlite.zip](https://github.com/ddnet/ddnet/files/8357548/ddnet-server.sqlite.zip)

**Comment by def-** [comment]
Can't reproduce locally with Python 3.10.3, happens on server with Python 3.9.2
