### ISSUE TITLE
Memory leak in network server/client, and UDP sockets are never closed

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#4983]
The leak was introduced by #4783, as creating a socket with `net_udp_create` now allocates memory but the memory is never freed, as `net_udp_close` ~~does not free the buffer and~~ is not called in any case.

I'll fix this issue and port some of the relevant code/refactoring from upstream: d716201687fce903613fcadc3f2f75e77e0df4c0 and f6abc9433a0f559dec7c5011686ec3afe4ce832b.

See https://github.com/ddnet/ddnet/runs/5961245894?check_suite_focus=true#step:5:570

```
Direct leak of 617544 byte(s) in 3 object(s) allocated from:
    #0 0x4b6f6d in malloc (/home/runner/work/ddnet/ddnet/san/DDNet+0x4b6f6d)
    #1 0x1dfe63f in net_udp_create /home/runner/work/ddnet/ddnet/src/base/system.cpp:1640:41
    #2 0x1d5f3a7 in CNetClient::Open(NETADDR) /home/runner/work/ddnet/ddnet/src/engine/shared/network_client.cpp:10:11
    #3 0xa8dc4e in CClient::Run() /home/runner/work/ddnet/ddnet/src/engine/client/client.cpp:2902:48
    #4 0xaf6726 in main /home/runner/work/ddnet/ddnet/src/engine/client/client.cpp:4458:11
    #5 0x7fadd9e610b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x240b2)

Direct leak of 205848 byte(s) in 1 object(s) allocated from:
    #0 0x4a200d in malloc (/home/runner/work/ddnet/ddnet/san/DDNet-Server+0x4a200d)
    #1 0xc7fe3f in net_udp_create /home/runner/work/ddnet/ddnet/src/base/system.cpp:1640:41
    #2 0xbf2d0b in CNetServer::Open(NETADDR, CNetBan*, int, int) /home/runner/work/ddnet/ddnet/src/engine/shared/network_server.cpp:55:13
    #3 0x568cdc in CServer::Run() /home/runner/work/ddnet/ddnet/src/engine/server/server.cpp:2448:60
    #4 0x5a922b in main /home/runner/work/ddnet/ddnet/src/engine/server/server.cpp:3718:21
    #5 0x7ff75f52c0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x240b2)
```

**Comment by Robyt3** [comment]
#4985
