### ISSUE TITLE
Server heap-buffer-overflow

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#5084]
```
=================================================================
==124544==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61b0002c9f08 at pc 0x0000004a643a bp 0x7ffd37c3e4b0 sp 0x7ffd37c3dc78
WRITE of size 1404 at 0x61b0002c9f08 thread T0
    #0 0x4a6439 in __asan_memcpy (/home/chiller/Desktop/git/ddnet/asan/DDNet-Server+0x4a6439)
    #1 0xc9b61b in mem_copy /home/chiller/Desktop/git/ddnet/src/base/system.cpp:213:2
    #2 0x55aecb in CServer::CCache::CCacheChunk::CCacheChunk(void const*, int) /home/chiller/Desktop/git/ddnet/src/engine/server/server.cpp:1878:2
    #3 0x5de244 in void __gnu_cxx::new_allocator<std::_List_node<CServer::CCache::CCacheChunk> >::construct<CServer::CCache::CCacheChunk, void const*&, int&>(CServer::CCache::CCacheChunk*, void const*&, int&) /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/ext/new_allocator.h:150:23
    #4 0x5ddb97 in void std::allocator_traits<std::allocator<std::_List_node<CServer::CCache::CCacheChunk> > >::construct<CServer::CCache::CCacheChunk, void const*&, int&>(std::allocator<std::_List_node<CServer::CCache::CCacheChunk> >&, CServer::CCache::CCacheChunk*, void const*&, int&) /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/alloc_traits.h:512:8
    #5 0x5dd61a in std::_List_node<CServer::CCache::CCacheChunk>* std::__cxx11::list<CServer::CCache::CCacheChunk, std::allocator<CServer::CCache::CCacheChunk> >::_M_create_node<void const*&, int&>(void const*&, int&) /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/stl_list.h:637:4
    #6 0x5dcda8 in void std::__cxx11::list<CServer::CCache::CCacheChunk, std::allocator<CServer::CCache::CCacheChunk> >::_M_insert<void const*&, int&>(std::_List_iterator<CServer::CCache::CCacheChunk>, void const*&, int&) /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/stl_list.h:1911:18
    #7 0x5c34ae in CServer::CCache::CCacheChunk& std::__cxx11::list<CServer::CCache::CCacheChunk, std::allocator<CServer::CCache::CCacheChunk> >::emplace_back<void const*&, int&>(void const*&, int&) /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/stl_list.h:1227:10
    #8 0x55b14d in CServer::CCache::AddChunk(void const*, int) /home/chiller/Desktop/git/ddnet/src/engine/server/server.cpp:1884:10
    #9 0x56132c in CServer::CacheServerInfoSixup(CServer::CCache*, bool) /home/chiller/Desktop/git/ddnet/src/engine/server/server.cpp:2147:10
    #10 0x561f68 in CServer::UpdateServerInfo(bool) /home/chiller/Desktop/git/ddnet/src/engine/server/server.cpp:2234:3
    #11 0x5799eb in CServer::Run() /home/chiller/Desktop/git/ddnet/src/engine/server/server.cpp:2751:5
    #12 0x5af989 in main /home/chiller/Desktop/git/ddnet/src/engine/server/server.cpp:3825:21
    #13 0x7f51c8daad09 in __libc_start_main csu/../csu/libc-start.c:308:16
    #14 0x42ceb9 in _start (/home/chiller/Desktop/git/ddnet/asan/DDNet-Server+0x42ceb9)

0x61b0002c9f08 is located 0 bytes to the right of 1416-byte region [0x61b0002c9980,0x61b0002c9f08)
allocated by thread T0 here:
    #0 0x4d6bcd in operator new(unsigned long) (/home/chiller/Desktop/git/ddnet/asan/DDNet-Server+0x4d6bcd)
    #1 0x5ddf2c in __gnu_cxx::new_allocator<std::_List_node<CServer::CCache::CCacheChunk> >::allocate(unsigned long, void const*) /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/ext/new_allocator.h:115:27
    #2 0x5dde5d in std::allocator_traits<std::allocator<std::_List_node<CServer::CCache::CCacheChunk> > >::allocate(std::allocator<std::_List_node<CServer::CCache::CCacheChunk> >&, unsigned long) /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/alloc_traits.h:460:20
    #3 0x5dd8bb in std::__cxx11::_List_base<CServer::CCache::CCacheChunk, std::allocator<CServer::CCache::CCacheChunk> >::_M_get_node() /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/stl_list.h:442:16
    #4 0x5dd3b6 in std::_List_node<CServer::CCache::CCacheChunk>* std::__cxx11::list<CServer::CCache::CCacheChunk, std::allocator<CServer::CCache::CCacheChunk> >::_M_create_node<void const*&, int&>(void const*&, int&) /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/stl_list.h:634:21
    #5 0x5dcda8 in void std::__cxx11::list<CServer::CCache::CCacheChunk, std::allocator<CServer::CCache::CCacheChunk> >::_M_insert<void const*&, int&>(std::_List_iterator<CServer::CCache::CCacheChunk>, void const*&, int&) /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/stl_list.h:1911:18
    #6 0x5c34ae in CServer::CCache::CCacheChunk& std::__cxx11::list<CServer::CCache::CCacheChunk, std::allocator<CServer::CCache::CCacheChunk> >::emplace_back<void const*&, int&>(void const*&, int&) /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/stl_list.h:1227:10
    #7 0x55b14d in CServer::CCache::AddChunk(void const*, int) /home/chiller/Desktop/git/ddnet/src/engine/server/server.cpp:1884:10
    #8 0x56132c in CServer::CacheServerInfoSixup(CServer::CCache*, bool) /home/chiller/Desktop/git/ddnet/src/engine/server/server.cpp:2147:10
    #9 0x561f68 in CServer::UpdateServerInfo(bool) /home/chiller/Desktop/git/ddnet/src/engine/server/server.cpp:2234:3
    #10 0x5799eb in CServer::Run() /home/chiller/Desktop/git/ddnet/src/engine/server/server.cpp:2751:5
    #11 0x5af989 in main /home/chiller/Desktop/git/ddnet/src/engine/server/server.cpp:3825:21
    #12 0x7f51c8daad09 in __libc_start_main csu/../csu/libc-start.c:308:16

SUMMARY: AddressSanitizer: heap-buffer-overflow (/home/chiller/Desktop/git/ddnet/asan/DDNet-Server+0x4a6439) in __asan_memcpy
Shadow bytes around the buggy address:
  0x0c3680051390: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c36800513a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c36800513b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c36800513c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c36800513d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c36800513e0: 00[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c36800513f0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3680051400: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3680051410: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3680051420: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3680051430: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==124544==ABORTING
```

Code is current master (490704b54344089bd1fb28d859d7398b4e8a0c0f) compiled with asan.

I can reproduce this on local server when connecting 52 clients using [chillerbot-ng](https://github.com/chillerbot/chillerbot-ng) ``./start_pentest.sh 52`` for example.

**Comment by def-** [comment]
Might be related to #4785

**Comment by ChillerDragon** [comment]
> Might be related to #4785 

Yes that is a duplicate. My bad. Sorry for not checking. If you need further information on reproducing it tell me.
