### ISSUE TITLE
Occasionally empty teehistorian files

### ISSUE THREAD

**Issue by Zwelf** [ddnet/ddnet#5121]
Found while investigating bugs in #5032, but this also applies to master. I didn't find out why it is happening though.

The teehistorian file look like this

```
{header}\0
Eos
```

Steps to reproduce (very inconsistent,  maybe one in 10-30 times):

1. start server
2. join server
3. f2 -> auth -> shutdown
4. `less uuid.teehistorian` -> observe if it only has `^@@` behind the header (there should always be more recorded)

* Last good commit: a39af83a421f8e1b
* First bad commit (known to me): 625ce302dd97981a (2021-12-16)
* Commit range in Github: [a39af83a..625ce302](https://github.com/ddnet/ddnet/compare/a39af83a421f8e1b26725dbbe04dfe131f8fc848...625ce302dd97981aa82b20a4f43a088332e65b1b)

It might have also happened before 15.0.5 284c287c9983e7d2, 2020-10-16 (which also produces files like this)

**Comment by Zwelf** [comment]
OnShutdown is called sometimes on start (but not always). Now I can look into fixing this :)

```
#0  CTeeHistorian::Finish (this=0x7ffff478edf8) at /home/user/dev/ddnet/src/game/server/teehistorian.cpp:757
#1  0x00005555556433e1 in CGameContext::OnShutdown (this=0x7ffff4783010) at /home/user/dev/ddnet/src/game/server/gamecontext.cpp:3633
#2  0x00005555555f9fff in CServer::Run (this=0x7ffff5fba010) at /home/user/dev/ddnet/src/engine/server/server.cpp:2621
#3  0x000055555560046c in main (argc=1, argv=0x7fffffffe808) at /home/user/dev/ddnet/src/engine/server/server.cpp:3839
```

**Comment by Zwelf** [comment]
Phew! I think this is a non-issue. Yes the teehistorian file is empty, but another is started immediately with the data. I just missed it in the log (copied the first teehistorian file outputted). And then sometimes the second, without noticing.

I'll still fix this, because the reload isn't necessary, but no data was lost (probably)!
