### ISSUE TITLE
Crash in curl_easy_init

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#5195]
On official servers:
```
Core was generated by `./DDRace64-Server_sql -f servers/8319.cfg'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f3d59204700 (LWP 1347467))]
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f3d5c2ac537 in __GI_abort () at abort.c:79
#2  0x00007f3d5bab2a18 in ?? () from /lib/x86_64-linux-gnu/libgcrypt.so.20
#3  0x00007f3d5bab33c6 in ?? () from /lib/x86_64-linux-gnu/libgcrypt.so.20
#4  0x00007f3d5baab95a in ?? () from /lib/x86_64-linux-gnu/libgcrypt.so.20
#5  0x00007f3d5baacbe1 in ?? () from /lib/x86_64-linux-gnu/libgcrypt.so.20
#6  0x00007f3d5baa8789 in gcry_control () from /lib/x86_64-linux-gnu/libgcrypt.so.20
#7  0x00007f3d5c201f74 in libssh2_init () from /lib/x86_64-linux-gnu/libssh2.so.1
#8  0x00007f3d5c9bb28b in ?? () from /lib/x86_64-linux-gnu/libcurl.so.4
#9  0x00007f3d5c962535 in ?? () from /lib/x86_64-linux-gnu/libcurl.so.4
#10 0x00007f3d5c962768 in curl_easy_init () from /lib/x86_64-linux-gnu/libcurl.so.4
#11 0x000055d349391d9d in CHttpRequest::Run (this=0x55d349af5a00)
    at /home/teeworlds/src/master/src/engine/shared/http.cpp:151
#12 0x000055d349395895 in CJobPool::RunBlocking (pJob=0x55d349af5a00)
    at /home/teeworlds/src/master/src/engine/shared/jobs.cpp:115
#13 0x000055d34938fb6d in IEngine::RunJobBlocking (pJob=<optimized out>)
    at /home/teeworlds/src/master/src/engine/shared/engine.cpp:120
#14 0x000055d3492fdac4 in CRegister::CProtocol::CJob::Run (this=0x55d349af60f0)
    at /usr/include/c++/10/bits/unique_ptr.h:173
#15 0x000055d3493948d3 in CJobPool::RunBlocking (pJob=0x55d349af60f0)
    at /home/teeworlds/src/master/src/engine/shared/jobs.cpp:115
#16 CJobPool::WorkerThread (pUser=pUser@entry=0x55d349a8dd10)
    at /home/teeworlds/src/master/src/engine/shared/jobs.cpp:70
#17 0x000055d3493acbf7 in thread_run (user=<optimized out>)
    at /home/teeworlds/src/master/src/base/system.cpp:689
#18 0x00007f3d5c454ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#19 0x00007f3d5c384def in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by def-** [comment]
@heinrich5991 might be related to master server registration
