### ISSUE TITLE
Crash in swap with teehistorian

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#5215]
Reported by murpi:
```
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00005572dc8c911b in CTeeHistorian::Write (DataSize=<optimized out>, pData=0x7ffc265d0840, this=0x7ff86447bdf8) at /home/teeworlds/src/master/src/game/server/teehistorian.cpp:367
#2  CTeeHistorian::WriteTick (this=0x7ff86447bdf8) at /home/teeworlds/src/master/src/game/server/teehistorian.cpp:390
#3  0x00005572dc8ca1a5 in CTeeHistorian::EnsureTickWritten (this=0x7ff86447bdf8) at /home/teeworlds/src/master/src/game/server/teehistorian.cpp:374
#4  CTeeHistorian::RecordPlayerSwap (this=0x7ff86447bdf8, ClientID1=0, ClientID2=1) at /home/teeworlds/src/master/src/game/server/teehistorian.cpp:581
#5  0x00005572dc8ba9fa in CGameTeams::SwapTeamCharacters (this=0x5572dcfdb7c0, pPlayer=0x5572dca0d460 <gs_PoolDataCPlayer>, pTargetPlayer=0x5572dca0d838 <gs_PoolDataCPlayer+984>, Team=15)
    at /home/teeworlds/src/master/src/game/server/teams.cpp:911
#6  0x00005572dc8ed774 in CConsole::ExecuteLineStroked (this=this@entry=0x5572dcf710e0, Stroke=Stroke@entry=1, pStr=<optimized out>, pStr@entry=0x7ff865dae3c6 "swap murpo", ClientID=ClientID@entry=0,
    InterpretSemicolons=InterpretSemicolons@entry=false) at /home/teeworlds/src/master/src/engine/shared/console.cpp:529
#7  0x00005572dc8ed9e8 in CConsole::ExecuteLine (this=0x5572dcf710e0, pStr=0x7ff865dae3c6 "swap murpo", ClientID=0, InterpretSemicolons=false) at /home/teeworlds/src/master/src/engine/shared/console.cpp:583
#8  0x00005572dc8a0844 in CGameContext::OnMessage (this=0x7ff864470010, MsgID=<optimized out>, pUnpacker=<optimized out>, ClientID=0) at /home/teeworlds/src/master/src/game/server/gamecontext.cpp:1909
#9  0x00005572dc86e349 in CServer::ProcessClientPacket (this=this@entry=0x7ff8654a6010, pPacket=pPacket@entry=0x7ffc265dfe00) at /home/teeworlds/src/master/src/engine/server/server.cpp:1826
#10 0x00005572dc86f760 in CServer::PumpNetwork (this=this@entry=0x7ff8654a6010, PacketWaiting=PacketWaiting@entry=true) at /home/teeworlds/src/master/src/engine/server/server.cpp:2418
#11 0x00005572dc8705c2 in CServer::Run (this=this@entry=0x7ff8654a6010) at /home/teeworlds/src/master/src/engine/server/server.cpp:2846
#12 0x00005572dc858d31 in main (argc=<optimized out>, argv=<optimized out>) at /home/teeworlds/src/master/src/engine/server/server.cpp:3915
```
@Zwelf was there a recent teehistorian change?

**Comment by def-** [comment]
Should be something in 50de8d23..cc3ea78f
