### ISSUE TITLE
Crash in CDraggerBeam

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#5217]
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000056394101727e in CGameWorld::GameServer (this=<optimized out>) at /home/teeworlds/src/master/src/game/server/gameworld.h:45
45		class CGameContext *GameServer() { return m_pGameServer; }
[Current thread is 1 (Thread 0x7fd3da9e7e00 (LWP 3327556))]
(gdb) bt
#0  0x000056394101727e in CGameWorld::GameServer (this=<optimized out>) at /home/teeworlds/src/master/src/game/server/gameworld.h:45
#1  CEntity::GameServer (this=<optimized out>) at /home/teeworlds/src/master/src/game/server/entity.h:60
#2  CCharacter::CanSnapCharacter (this=this@entry=0x0, SnappingClient=SnappingClient@entry=1) at /home/teeworlds/src/master/src/game/server/entities/character.cpp:1172
#3  0x000056394101b212 in CCharacter::CanSnapCharacter (this=this@entry=0x0, SnappingClient=SnappingClient@entry=1) at /home/teeworlds/src/master/src/game/server/entities/character.cpp:1186
#4  0x0000563941023474 in CDraggerBeam::Snap (SnappingClient=1, this=0x563941d4c700) at /home/teeworlds/src/master/src/game/server/entities/dragger_beam.cpp:84
#5  CDraggerBeam::Snap (this=0x563941d4c700, SnappingClient=1) at /home/teeworlds/src/master/src/game/server/entities/dragger_beam.cpp:75
#6  0x0000563941041efc in CGameWorld::Snap (this=this@entry=0x7fd3d8432448, SnappingClient=SnappingClient@entry=1) at /home/teeworlds/src/master/src/game/server/gameworld.cpp:124
#7  0x000056394102df3d in CGameContext::OnSnap (this=0x7fd3d8422010, ClientID=1) at /home/teeworlds/src/master/src/game/server/gamecontext.cpp:3719
#8  0x0000563941004c1a in CServer::DoSnapshot (this=this@entry=0x7fd3d9458010) at /home/teeworlds/src/master/src/engine/server/server.cpp:964
#9  0x000056394100bf8b in CServer::Run (this=this@entry=0x7fd3d9458010) at /home/teeworlds/src/master/src/engine/server/server.cpp:2828
#10 0x0000563940ff4d31 in main (argc=<optimized out>, argv=<optimized out>) at /home/teeworlds/src/master/src/engine/server/server.cpp:3915
```
@C0D3D3V probably related to your change. this point is nullptr in CCharacter. I'll fix it

**Comment by C0D3D3V** [comment]
Thank you
Sorry I had not thought about that.
