### ISSUE TITLE
Initial map not found -> Server can't be killed

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#5227]
DDNet-Server "sv_map foasdsada"

**Comment by Robyt3** [comment]
For me the server just terminates immediately after not finding the initial map (73a099885b8cdeeb11feae1d16e3c235be592bdb on Windows 10).

**Comment by C0D3D3V** [comment]
For me it also just stops:
```
[2022-05-28 11:42:09][server]: starting...
[2022-05-28 11:42:09][datafile]: loading. filename='maps/foasdsada.map'
[2022-05-28 11:42:09][datafile]: could not open 'maps/foasdsada.map'
[2022-05-28 11:42:09][server]: failed to load map. mapname='foasdsada'

=================================================================
==12192==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 64 byte(s) in 64 object(s) allocated from:
    #0 0x55d8ab7e2439 in __interceptor_malloc (/home/daniel/Desktop/other_repos/ddnet_latest/build/DDNet-Server+0x4f6439)
    #1 0x55d8ab8c20d5 in CServer::Run() /home/daniel/Desktop/other_repos/ddnet_latest/src/engine/server/server.cpp:2572:31
    #2 0x55d8ab8fddcc in main /home/daniel/Desktop/other_repos/ddnet_latest/src/engine/server/server.cpp:3915:21
    #3 0x7fca1600228f  (/usr/lib/libc.so.6+0x2928f)

SUMMARY: AddressSanitizer: 64 byte(s) leaked in 64 allocation(s).
```

**Comment by def-** [comment]
Might be macOS specific, unfortunately it even hangs the debugger there.
