### ISSUE TITLE
Memory leak on server, if port is already in use:

### ISSUE THREAD

**Issue by C0D3D3V** [ddnet/ddnet#5498]
```
./DDNet-Server "sv_port 8305"
[2022-06-25 15:13:34][engine]: running on unix-linux-amd64
[2022-06-25 15:13:34][engine]: arch is little endian
[2022-06-25 15:13:34][storage]: couldn't open storage.cfg
[2022-06-25 15:13:34][storage]: using standard paths
[2022-06-25 15:13:34][storage]: added path '$USERDIR' ('/home/daniel/.teeworlds')
[2022-06-25 15:13:34][storage]: added path '$DATADIR' ('data')
[2022-06-25 15:13:34][storage]: added path '$CURRENTDIR' ('/home/daniel/Desktop/other_repos/ddnet_latest/build')
[2022-06-25 15:13:34][http]: libcurl version 7.83.1 (compiled = 7.83.1)
[2022-06-25 15:13:34][host_lookup]: host='localhost' port=0 1
[2022-06-25 15:13:34][host_lookup]: host='localhost' port=0 2
[2022-06-25 15:13:34][server]: starting...
[2022-06-25 15:13:34][datafile]: loading. filename='maps/Sunny Side Up.map'
[2022-06-25 15:13:34][datafile]: loading done. datafile='maps/Sunny Side Up.map'
[2022-06-25 15:13:34][net]: failed to bind socket with domain 2 and type 2 (98 'Address already in use')
[2022-06-25 15:13:34][net]: failed to bind socket with domain 10 and type 2 (98 'Address already in use')
[2022-06-25 15:13:34][server]: couldn't open socket. port 8305 might already be in use

=================================================================
==111766==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 64 byte(s) in 64 object(s) allocated from:
    #0 0x559a54869f59 in __interceptor_malloc (/home/daniel/Desktop/other_repos/ddnet_latest/build/DDNet-Server+0x51af59)
    #1 0x559a549579a5 in CServer::Run() /home/daniel/Desktop/other_repos/ddnet_latest/src/engine/server/server.cpp:2561:31
    #2 0x559a549941c0 in main /home/daniel/Desktop/other_repos/ddnet_latest/src/engine/server/server.cpp:3912:21
    #3 0x7f3ca6c2928f  (/usr/lib/libc.so.6+0x2928f)

SUMMARY: AddressSanitizer: 64 byte(s) leaked in 64 allocation(s).
```

**Comment by def-** [comment]
Can't reproduce it. What state of ddnet are you using?

**Comment by C0D3D3V** [comment]
Mh maybe it is already patched, I will test it tomorrow with latest master

**Comment by C0D3D3V** [comment]
I could not reproduce it anymore
