### ISSUE TITLE
sqlite failure: Tried connecting while the connection is in use

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#5606]
```
Program terminated with signal SIGILL, Illegal instruction.
#0  dbg_break () at /home/teeworlds/src/master/src/base/system.cpp:184
184     /home/teeworlds/src/master/src/base/system.cpp: No such file or directory.
[Current thread is 1 (Thread 0x7f0976798700 (LWP 706))]
(gdb) bt
#0  dbg_break () at /home/teeworlds/src/master/src/base/system.cpp:184
#1  dbg_assert_imp (filename=<optimized out>, line=<optimized out>, 
    msg=msg@entry=0x561741055540 "Tried connecting while the connection is in use", test=0)
    at /home/teeworlds/src/master/src/base/system.cpp:177
#2  0x0000561740f7e7b7 in dbg_assert_imp (
    filename=filename@entry=0x5617410556e0 "/home/teeworlds/src/master/src/engine/server/databases/sqlite.cpp", line=line@entry=117, test=test@entry=0, 
    msg=msg@entry=0x561741055540 "Tried connecting while the connection is in use")
    at /home/teeworlds/src/master/src/base/system.cpp:179
#3  0x0000561740f86b7a in CSqliteConnection::Connect (this=0x5617413ac5c0, 
    pError=0x7f0976797ad0 "error message not initialized", ErrorSize=256)
    at /home/teeworlds/src/master/src/engine/server/databases/sqlite.cpp:117
#4  0x0000561740f82948 in CDbConnectionPool::ExecSqlFunc (this=this@entry=0x56174139c850, 
    pConnection=0x5617413ac5c0, pData=pData@entry=0x561743706dc0, Failure=Failure@entry=false)
    at /home/teeworlds/src/master/src/engine/server/databases/connection_pool.cpp:239
#5  0x0000561740f82d2b in CDbConnectionPool::Worker (this=0x56174139c850)
    at /usr/include/c++/10/bits/unique_ptr.h:173
#6  0x0000561741039527 in thread_run (user=<optimized out>)
    at /home/teeworlds/src/master/src/base/system.cpp:721
#7  0x00007f0978c54ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#8  0x00007f0978b84def in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
CC @Zwelf

**Comment by C0D3D3V** [comment]
Same issue as here https://github.com/ddnet/ddnet/issues/5500

In the meantime I have a new theory. It could be that this happens if you deleted the build directory but your terminal still point to this, making it redirect to a temp directory that is not writeable. Then if you build again and run you get this error. Not completly sure about it, and I also have not reproduced it. But I think I got this at least twice that way.

**Comment by def-** [comment]
We don‘t have a build dir and don‘t remove anything on official servers, where this happened.

**Comment by def-** [comment]
Fixed by #7049 I think
