### ISSUE TITLE
Shift + Left click in editor crashes the game

### ISSUE THREAD

**Issue by murpii** [ddnet/ddnet#5626]
Reported by Seigneur on discord
Client version 16.2.2

**Comment by Chairn** [comment]
Can reproduce on latest master:
```
#0  0x00005555558ff436 in CEditor::DoMapEditor(CUIRect) (this=0x555555bbb0e0, View=...)
    at ../src/game/editor/editor.cpp:2639
#1  0x00005555559121ae in CEditor::Render() (this=0x555555bbb0e0)
    at ../src/game/editor/editor.cpp:5745
#2  0x0000555555915885 in CEditor::OnRender() (this=0x555555bbb0e0)
    at ../src/game/editor/editor.cpp:6435
#3  0x00005555556fc24e in CClient::Run() (this=0x7fffdaea5010)
    at ../src/engine/client/client.cpp:3370
#4  0x00005555557052d4 in main(int, char const**) (argc=1, argv=0x7fffffffd5e8)
    at ../src/engine/client/client.cpp:4752
```

**Comment by def-** [comment]
Will bisect:
```
DDNet was compiled with optimization - stepping may behave oddly; variables may not be available.
Process 61704 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x000000010017a3c4 DDNet`CEditor::DoMapEditor(this=0x0000000104816600, View=(x = 100, y = 69, w = 886.489074, h = 515)) at editor.cpp:2639:58 [opt]
   2636								size_t BrushIndex = k;
   2637								if(m_Brush.m_vpLayers.size() != NumEditLayers)
   2638									BrushIndex = 0;
-> 2639								apEditLayers[k]->FillSelection(m_Brush.IsEmpty(), m_Brush.m_vpLayers[BrushIndex], r);
   2640							}
   2641						}
   2642						else
Target 0: (DDNet) stopped.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
  * frame #0: 0x000000010017a3c4 DDNet`CEditor::DoMapEditor(this=0x0000000104816600, View=(x = 100, y = 69, w = 886.489074, h = 515)) at editor.cpp:2639:58 [opt]
    frame #1: 0x000000010018520c DDNet`CEditor::Render(this=0x0000000104816600) at editor.cpp:5745:3 [opt]
    frame #2: 0x0000000100187790 DDNet`CEditor::OnRender(this=0x0000000104816600) at editor.cpp:6435:2 [opt]
    frame #3: 0x0000000100086aa4 DDNet`CClient::Run(this=0x0000000108020000) at client.cpp:3370:18 [opt]
    frame #4: 0x000000010008d324 DDNet`::TWMain(argc=<unavailable>, argv=<unavailable>) at client.cpp:4752:11 [opt]
    frame #5: 0x000000010039d08c dyld`start + 520
```

**Comment by def-** [comment]
```
0c69495522877ff44b60ebb6cdad14067c1c70c3 is the first bad commit
commit 0c69495522877ff44b60ebb6cdad14067c1c70c3
Author: Robert Müller <robytemueller@gmail.com>
Date:   Tue May 24 11:24:33 2022 +0200

    Use std::vector instead of array in editor

 src/game/editor/auto_map.cpp     |  92 ++++---
 src/game/editor/auto_map.h       |  12 +-
 src/game/editor/editor.cpp       | 579 +++++++++++++++++++++------------------
 src/game/editor/editor.h         |  81 +++---
 src/game/editor/io.cpp           | 189 +++++++------
 src/game/editor/layer_quads.cpp  |  61 ++---
 src/game/editor/layer_sounds.cpp |  69 +++--
 src/game/editor/layer_tiles.cpp  |  24 +-
 src/game/editor/popups.cpp       | 179 ++++++------
 9 files changed, 653 insertions(+), 633 deletions(-)
```

**Comment by Robyt3** [comment]
That's kinda what I expected. I think I found the fix already.
