### ISSUE TITLE
Crash in AntibotOnPlayerDestroy

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#5668]
```
Core was generated by `./DDRace64-Server_sql -f servers/block2.cfg'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f6a9bcf0980 (LWP 1012))]
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f6a9ca76537 in __GI_abort () at abort.c:79
#2  0x00007f6a9cacf768 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7f6a9cbdde2d "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007f6a9cad6a5a in malloc_printerr (str=str@entry=0x7f6a9cbdc072 "free(): invalid size") at malloc.c:5347
#4  0x00007f6a9cad7c24 in _int_free (av=<optimized out>, p=0x5602587950d0, have_lock=0) at malloc.c:4177
#5  0x00007f6a9cf4ee1d in anti_bot::rc_end3 (ra=0x56025878da00, this=0x5602587a7540) at /home/hein/git/ddnet-antibot/antibot.h:1299
#6  anti_bot::~anti_bot (this=0x5602587a7540, __in_chrg=<optimized out>) at /home/hein/git/ddnet-antibot/antibot.h:110
#7  0x00007f6a9cf4deac in AntibotOnPlayerDestroy (ClientID=2) at antibot_lib.cpp:219
#8  0x000056025767eec0 in CPlayer::~CPlayer (this=0x5602577ea100 <gs_PoolDataCPlayer+1984>, __in_chrg=<optimized out>) at /home/teeworlds/src/master/src/game/server/player.cpp:36
#9  0x0000560257672965 in CGameContext::OnClientDrop (this=0x7f6a98f2c010, ClientID=2, pReason=0x7f6a9ae67748 "") at /home/teeworlds/src/master/src/game/server/gamecontext.cpp:1529
#10 0x000056025763bb67 in CServer::DelClientCallback (ClientID=2, pReason=0x7f6a9ae67748 "", pUser=0x7f6a9a763010) at /home/teeworlds/src/master/src/engine/server/server.cpp:1192
#11 0x00005602576d897b in CNetServer::Drop (pReason=0x7f6a9ae67748 "", ClientID=2, this=0x7f6a9ae4e878) at /home/teeworlds/src/master/src/engine/shared/network_server.cpp:106
#12 CNetServer::Update (this=this@entry=0x7f6a9ae4e878) at /home/teeworlds/src/master/src/engine/shared/network_server.cpp:122
#13 0x0000560257644cb8 in CServer::PumpNetwork (this=this@entry=0x7f6a9a763010, PacketWaiting=PacketWaiting@entry=true) at /home/teeworlds/src/master/src/engine/server/server.cpp:2345
#14 0x0000560257645dfe in CServer::Run (this=this@entry=0x7f6a9a763010) at /home/teeworlds/src/master/src/engine/server/server.cpp:2839
#15 0x000056025762e03a in main (argc=<optimized out>, argv=<optimized out>) at /home/teeworlds/src/master/src/engine/server/server.cpp:3907
```
CC @headshot2017 @heinrich5991

**Comment by def-** [comment]
Still crashing all the time...

**Comment by Learath2** [comment]
Can you save a core for me on a server?

**Comment by def-** [comment]
Wait a day and you'll have a few on RUS2

**Comment by Learath2** [comment]
@def- if this is still happening (I didn't find a core on RUS2 (I did have to delete all the cores because I kinda crashed all the servers earlier)) save me a core
