### ISSUE TITLE
Crash in CHttpRequest on ipv6-only server

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#6011]
Seen on GER6, don't have logs:
```
Core was generated by `./DDRace64-Server_sql -f servers/8308.cfg'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f990902b0a4 in ?? () from /lib/x86_64-linux-gnu/libcurl.so.4
[Current thread is 1 (Thread 0x7f99060c0700 (LWP 1145086))]
(gdb) bt
#0  0x00007f990902b0a4 in ?? () from /lib/x86_64-linux-gnu/libcurl.so.4
#1  0x00007f990902b9b2 in ?? () from /lib/x86_64-linux-gnu/libcurl.so.4
#2  0x00007f990903de76 in ?? () from /lib/x86_64-linux-gnu/libcurl.so.4
#3  0x00007f9909044dee in ?? () from /lib/x86_64-linux-gnu/libcurl.so.4
#4  0x00007f990905c23b in ?? () from /lib/x86_64-linux-gnu/libcurl.so.4
#5  0x00007f990905d226 in curl_multi_perform () from /lib/x86_64-linux-gnu/libcurl.so.4
#6  0x00007f9909033aa3 in curl_easy_perform () from /lib/x86_64-linux-gnu/libcurl.so.4
#7  0x0000564d9bd1fd34 in CHttpRequest::RunImpl (this=this@entry=0x564d9df19c70, pUser=pUser@entry=0x7f98f0034af0) at /home/teeworlds/src/master/src/engine/shared/http.cpp:277
#8  0x0000564d9bd1ff1b in CHttpRequest::Run (this=0x564d9df19c70) at /home/teeworlds/src/master/src/engine/shared/http.cpp:161
#9  0x0000564d9bd22bf5 in CJobPool::RunBlocking (pJob=0x564d9df19c70) at /home/teeworlds/src/master/src/engine/shared/jobs.cpp:118
#10 0x0000564d9bd1dc5d in IEngine::RunJobBlocking (pJob=<optimized out>) at /home/teeworlds/src/master/src/engine/shared/engine.cpp:124
#11 0x0000564d9bc884b6 in CRegister::CProtocol::CJob::Run (this=0x564d9df19a00) at /usr/include/c++/10/bits/unique_ptr.h:173
#12 0x0000564d9bd21c02 in CJobPool::RunBlocking (pJob=0x564d9df19a00) at /home/teeworlds/src/master/src/engine/shared/jobs.cpp:118
#13 CJobPool::WorkerThread (pUser=pUser@entry=0x564d9cae74d0) at /home/teeworlds/src/master/src/engine/shared/jobs.cpp:73
#14 0x0000564d9bd3aa77 in thread_run (user=<optimized out>) at /home/teeworlds/src/master/src/base/system.cpp:730
#15 0x00007f9908b24ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#16 0x00007f9908a44aef in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) thread apply all bt

Thread 7 (Thread 0x7f98eef7a700 (LWP 1145094)):
#0  futex_abstimed_wait_cancelable (private=0, abstime=0x0, clockid=0, expected=0, futex_word=0x564d9df14d70) at ../sysdeps/nptl/futex-internal.h:323
#1  do_futex_wait (sem=sem@entry=0x564d9df14d70, abstime=0x0, clockid=0) at sem_waitcommon.c:112
#2  0x00007f9908b2e278 in __new_sem_wait_slow (sem=sem@entry=0x564d9df14d70, abstime=0x0, clockid=0) at sem_waitcommon.c:184
#3  0x00007f9908b2e2f1 in __new_sem_wait (sem=sem@entry=0x564d9df14d70) at sem_wait.c:42
#4  0x0000564d9bd3b496 in sphore_wait (sem=0x564d9df14d70) at /home/teeworlds/src/master/src/base/system.cpp:937
#5  aio_thread (user=user@entry=0x564d9df14d60) at /home/teeworlds/src/master/src/base/system.cpp:487
#6  0x0000564d9bd3aa77 in thread_run (user=<optimized out>) at /home/teeworlds/src/master/src/base/system.cpp:730
#7  0x00007f9908b24ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#8  0x00007f9908a44aef in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 6 (Thread 0x7f9904d21700 (LWP 1145091)):
#0  futex_abstimed_wait_cancelable (private=0, abstime=0x0, clockid=0, expected=0, futex_word=0x564d9caf6830) at ../sysdeps/nptl/futex-internal.h:323
#1  do_futex_wait (sem=sem@entry=0x564d9caf6830, abstime=0x0, clockid=0) at sem_waitcommon.c:112
#2  0x00007f9908b2e278 in __new_sem_wait_slow (sem=sem@entry=0x564d9caf6830, abstime=0x0, clockid=0) at sem_waitcommon.c:184
#3  0x00007f9908b2e2f1 in __new_sem_wait (sem=sem@entry=0x564d9caf6830) at sem_wait.c:42
#4  0x0000564d9bd3b496 in sphore_wait (sem=0x564d9caf6830) at /home/teeworlds/src/master/src/base/system.cpp:937
#5  aio_thread (user=user@entry=0x564d9caf6820) at /home/teeworlds/src/master/src/base/system.cpp:487
#6  0x0000564d9bd3aa77 in thread_run (user=<optimized out>) at /home/teeworlds/src/master/src/base/system.cpp:730
#7  0x00007f9908b24ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#8  0x00007f9908a44aef in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 5 (Thread 0x7f99058bf700 (LWP 1145087)):
#0  0x00007f9909154ab4 in ASN1_mbstring_ncopy () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
#1  0x00007f9909154f1e in ASN1_mbstring_copy () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
#2  0x00007f99091576e8 in ASN1_STRING_to_UTF8 () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
#3  0x00007f99092c9799 in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
#4  0x00007f99092c9ec7 in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
#5  0x00007f990916414c in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
#6  0x00007f9909164b16 in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
#7  0x00007f9909164d81 in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
#8  0x00007f9909164428 in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
#9  0x00007f9909164b16 in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
#10 0x00007f9909164d81 in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
#11 0x00007f9909164428 in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
#12 0x00007f9909164eae in ASN1_item_ex_d2i () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
#13 0x00007f9909164f2b in ASN1_item_d2i () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
#14 0x00007f9909258bac in PEM_X509_INFO_read_bio () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
#15 0x00007f99092ba093 in X509_load_cert_crl_file () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
#16 0x00007f99092ba1e2 in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
#17 0x00007f99092bcfaf in X509_STORE_load_locations () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
#18 0x00007f9909084873 in ?? () from /lib/x86_64-linux-gnu/libcurl.so.4
#19 0x00007f9909085dbf in ?? () from /lib/x86_64-linux-gnu/libcurl.so.4
#20 0x00007f9909086e81 in ?? () from /lib/x86_64-linux-gnu/libcurl.so.4
#21 0x00007f99090467d5 in ?? () from /lib/x86_64-linux-gnu/libcurl.so.4
#22 0x00007f990905c059 in ?? () from /lib/x86_64-linux-gnu/libcurl.so.4
#23 0x00007f990905d226 in curl_multi_perform () from /lib/x86_64-linux-gnu/libcurl.so.4
#24 0x00007f9909033aa3 in curl_easy_perform () from /lib/x86_64-linux-gnu/libcurl.so.4
#25 0x0000564d9bd1fd34 in CHttpRequest::RunImpl (this=this@entry=0x564d9df14df0, pUser=pUser@entry=0x7f98fc0afd30) at /home/teeworlds/src/master/src/engine/shared/http.cpp:277
#26 0x0000564d9bd1ff1b in CHttpRequest::Run (this=0x564d9df14df0) at /home/teeworlds/src/master/src/engine/shared/http.cpp:161
#27 0x0000564d9bd22bf5 in CJobPool::RunBlocking (pJob=0x564d9df14df0) at /home/teeworlds/src/master/src/engine/shared/jobs.cpp:118
#28 0x0000564d9bd1dc5d in IEngine::RunJobBlocking (pJob=<optimized out>) at /home/teeworlds/src/master/src/engine/shared/engine.cpp:124
#29 0x0000564d9bc884b6 in CRegister::CProtocol::CJob::Run (this=0x564d9df1aa30) at /usr/include/c++/10/bits/unique_ptr.h:173
#30 0x0000564d9bd21c02 in CJobPool::RunBlocking (pJob=0x564d9df1aa30) at /home/teeworlds/src/master/src/engine/shared/jobs.cpp:118
#31 CJobPool::WorkerThread (pUser=pUser@entry=0x564d9cae74d0) at /home/teeworlds/src/master/src/engine/shared/jobs.cpp:73
#32 0x0000564d9bd3aa77 in thread_run (user=<optimized out>) at /home/teeworlds/src/master/src/base/system.cpp:730
#33 0x00007f9908b24ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#34 0x00007f9908a44aef in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 4 (Thread 0x7f99068c1700 (LWP 1145084)):
#0  futex_abstimed_wait_cancelable (private=0, abstime=0x0, clockid=0, expected=0, futex_word=0x564d9cae48a0) at ../sysdeps/nptl/futex-internal.h:323
#1  do_futex_wait (sem=sem@entry=0x564d9cae48a0, abstime=0x0, clockid=0) at sem_waitcommon.c:112
#2  0x00007f9908b2e278 in __new_sem_wait_slow (sem=sem@entry=0x564d9cae48a0, abstime=0x0, clockid=0) at sem_waitcommon.c:184
#3  0x00007f9908b2e2f1 in __new_sem_wait (sem=sem@entry=0x564d9cae48a0) at sem_wait.c:42
#4  0x0000564d9bd3cb09 in sphore_wait (sem=sem@entry=0x564d9cae48a0) at /home/teeworlds/src/master/src/base/system.cpp:937
#5  0x0000564d9bc832ca in CSemaphore::Wait (this=0x564d9cae48a0) at /home/teeworlds/src/master/src/base/tl/threading.h:21
#6  CDbConnectionPool::Worker (this=0x564d9cae4850) at /home/teeworlds/src/master/src/engine/server/databases/connection_pool.cpp:146
#7  0x0000564d9bd3aa77 in thread_run (user=<optimized out>) at /home/teeworlds/src/master/src/base/system.cpp:730
#8  0x00007f9908b24ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#9  0x00007f9908a44aef in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7f9907e57e00 (LWP 1145077)):
#0  0x00007f9908a3b2a3 in __GI___select (nfds=nfds@entry=8, readfds=readfds@entry=0x7ffd44129090, writefds=writefds@entry=0x0, exceptfds=exceptfds@entry=0x0, timeout=timeout@entry=0x7ffd44129080) at ../sysdeps/unix/sysv/linux/select.c:41
#1  0x0000564d9bd3eb96 in net_socket_read_wait (sock=0x564d9de55310, time=time@entry=1000000) at /home/teeworlds/src/master/src/base/system.cpp:2531
#2  0x0000564d9bc97cd9 in CServer::Run (this=this@entry=0x7f99068c2010) at /home/teeworlds/src/master/src/engine/shared/network.h:421
#3  0x0000564d9bc7f7ea in main (argc=<optimized out>, argv=<optimized out>) at /home/teeworlds/src/master/src/engine/server/main.cpp:191

Thread 2 (Thread 0x7f9907e54700 (LWP 1145082)):
#0  futex_abstimed_wait_cancelable (private=0, abstime=0x0, clockid=0, expected=0, futex_word=0x564d9cab6f40) at ../sysdeps/nptl/futex-internal.h:323
#1  do_futex_wait (sem=sem@entry=0x564d9cab6f40, abstime=0x0, clockid=0) at sem_waitcommon.c:112
#2  0x00007f9908b2e278 in __new_sem_wait_slow (sem=sem@entry=0x564d9cab6f40, abstime=0x0, clockid=0) at sem_waitcommon.c:184
#3  0x00007f9908b2e2f1 in __new_sem_wait (sem=sem@entry=0x564d9cab6f40) at sem_wait.c:42
#4  0x0000564d9bd3b496 in sphore_wait (sem=0x564d9cab6f40) at /home/teeworlds/src/master/src/base/system.cpp:937
#5  aio_thread (user=user@entry=0x564d9cab6f30) at /home/teeworlds/src/master/src/base/system.cpp:487
#6  0x0000564d9bd3aa77 in thread_run (user=<optimized out>) at /home/teeworlds/src/master/src/base/system.cpp:730
#7  0x00007f9908b24ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#8  0x00007f9908a44aef in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7f99060c0700 (LWP 1145086)):
#0  0x00007f990902b0a4 in ?? () from /lib/x86_64-linux-gnu/libcurl.so.4
#1  0x00007f990902b9b2 in ?? () from /lib/x86_64-linux-gnu/libcurl.so.4
#2  0x00007f990903de76 in ?? () from /lib/x86_64-linux-gnu/libcurl.so.4
#3  0x00007f9909044dee in ?? () from /lib/x86_64-linux-gnu/libcurl.so.4
#4  0x00007f990905c23b in ?? () from /lib/x86_64-linux-gnu/libcurl.so.4
#5  0x00007f990905d226 in curl_multi_perform () from /lib/x86_64-linux-gnu/libcurl.so.4
#6  0x00007f9909033aa3 in curl_easy_perform () from /lib/x86_64-linux-gnu/libcurl.so.4
#7  0x0000564d9bd1fd34 in CHttpRequest::RunImpl (this=this@entry=0x564d9df19c70, pUser=pUser@entry=0x7f98f0034af0) at /home/teeworlds/src/master/src/engine/shared/http.cpp:277
#8  0x0000564d9bd1ff1b in CHttpRequest::Run (this=0x564d9df19c70) at /home/teeworlds/src/master/src/engine/shared/http.cpp:161
#9  0x0000564d9bd22bf5 in CJobPool::RunBlocking (pJob=0x564d9df19c70) at /home/teeworlds/src/master/src/engine/shared/jobs.cpp:118
#10 0x0000564d9bd1dc5d in IEngine::RunJobBlocking (pJob=<optimized out>) at /home/teeworlds/src/master/src/engine/shared/engine.cpp:124
#11 0x0000564d9bc884b6 in CRegister::CProtocol::CJob::Run (this=0x564d9df19a00) at /usr/include/c++/10/bits/unique_ptr.h:173
#12 0x0000564d9bd21c02 in CJobPool::RunBlocking (pJob=0x564d9df19a00) at /home/teeworlds/src/master/src/engine/shared/jobs.cpp:118
#13 CJobPool::WorkerThread (pUser=pUser@entry=0x564d9cae74d0) at /home/teeworlds/src/master/src/engine/shared/jobs.cpp:73
#14 0x0000564d9bd3aa77 in thread_run (user=<optimized out>) at /home/teeworlds/src/master/src/base/system.cpp:730
#15 0x00007f9908b24ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#16 0x00007f9908a44aef in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
Thread 1 and Thread 5 are both running curl at once, is that ok?

**Comment by heinrich5991** [comment]
Yea, that's okay and intended.

**Comment by def-** [comment]
Fixed by #7683
