### ISSUE TITLE
Server crash when changing map on Linux x86-64 build

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#6023]
1. Start server
2. Connect to server with client
3. Change map to [Skill_Issue.zip](https://github.com/ddnet/ddnet/files/9970955/Skill_Issue.zip)
4. Linux x86-64 nightly build crashes, 16.5 too:
```
Thread 1 "DDNet-Server" received signal SIGSEGV, Segmentation fault.
0x00000000004c218d in ?? ()
(gdb) bt
#0  0x00000000004c218d in ?? ()
#1  0x00000000004ba7c1 in ?? ()
#2  0x00000000004eedd6 in ?? ()
#3  0x000000000040be14 in ?? ()
#4  0x00007ffff7c30290 in __libc_start_call_main (main=main@entry=0x409eb0, argc=argc@entry=1,
    argv=argv@entry=0x7fffffffe2d8) at ../sysdeps/nptl/libc_start_call_main.h:58
#5  0x00007ffff7c3034a in __libc_start_main_impl (main=0x409eb0, argc=1, argv=0x7fffffffe2d8,
    init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe2c8)
    at ../csu/libc-start.c:381
#6  0x000000000040c54a in ?? ()
```
With Asan or RelWithDebInfo (debug symbols without strip) no crash.

**Comment by heinrich5991** [comment]
How did you compile it? Usually there are at least function names if you don't strip. If you do strip, I think there's an option to leave the symbols next to the binary.

**Comment by def-** [comment]
I will try now with Release build, but no strip, maybe that works.

**Comment by def-** [comment]
That helps a bit:
```
Thread 1 "DDNet-Server" received signal SIGSEGV, Segmentation fault.
0x00000000004be70d in CGun::Fire() ()
(gdb) bt
#0  0x00000000004be70d in CGun::Fire() ()
#1  0x00000000004b6ae1 in CGameContext::OnTick() ()
#2  0x00000000004eb3c6 in CServer::Run() ()
#3  0x0000000000408eb4 in main ()
```
