### ISSUE TITLE
!xcb_xlib_threads_sequence_lost assertion failure

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#6157]
```
2022-12-18 00:13:31 I client: got pong from current server, latency=17ms
[xcb] Unknown sequence number while processing queue
[xcb] You called XInitThreads, this is not your fault
[xcb] Aborting, sorry about that.
DDNet: xcb_io.c:278: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
zsh: IOT instruction (core dumped)  ./DDNet
```
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `./DDNet -f mine.cfg'.
Program terminated with signal SIGABRT, Aborted.
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0)
    at pthread_kill.c:44
Downloading 0.00 MB source file /usr/src/debug/glibc/nptl/pthread_kill.c
44	      return INTERNAL_SYSCALL_ERROR_P (ret) ? INTERNAL_SYSCALL_ERRNO (ret) : 0;                   
[Current thread is 1 (Thread 0x7f14399a0000 (LWP 709279))]
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0)
    at pthread_kill.c:44
#1  0x00007f1448bb96b3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007f1448b69958 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007f1448b5353d in __GI_abort () at abort.c:79
#4  0x00007f1448b5345c in __assert_fail_base
    (fmt=0x7f1448ccda50 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x7f143c774d48 "!xcb_xlib_threads_sequence_lost", file=0x7f143c774974 "xcb_io.c", line=278, function=<optimized out>) at assert.c:92
#5  0x00007f1448b62486 in __GI___assert_fail
    (assertion=assertion@entry=0x7f143c774d48 "!xcb_xlib_threads_sequence_lost", file=file@entry=0x7f143c774974 "xcb_io.c", line=line@entry=278, function=function@entry=0x7f143c775338 <__PRETTY_FUNCTION__.7> "poll_for_event") at assert.c:101
#6  0x00007f143c6fea12 in poll_for_event (dpy=dpy@entry=0x560bc1794b80, queued_only=0)
    at /usr/src/debug/libx11/libX11-1.8.3/src/xcb_io.c:278
#7  0x00007f143c6fead6 in poll_for_response (dpy=dpy@entry=0x560bc1794b80)
    at /usr/src/debug/libx11/libX11-1.8.3/src/xcb_io.c:310
#8  0x00007f143c701752 in _XEventsQueued (dpy=0x560bc1794b80, mode=<optimized out>)
    at /usr/src/debug/libx11/libX11-1.8.3/src/xcb_io.c:441
#9  0x00007f143c6dee57 in XCheckIfEvent
     (dpy=0x560bc1794b80, event=0x7ffc7d864fd0, predicate=0x7f144bb158e0, arg=0x0) at /usr/src/debug/libx11/libX11-1.8.3/src/ChkIfEv.c:73
#10 0x00007f144bb1e2dd in  () at /usr/lib/libSDL2-2.0.so.0
#11 0x00007f144ba6b329 in  () at /usr/lib/libSDL2-2.0.so.0
#12 0x00007f144ba6b727 in  () at /usr/lib/libSDL2-2.0.so.0
#13 0x0000560bbf4e4958 in CInput::Update() (this=0x560bc16c27f0)
    at /media/ddnet/src/engine/client/input.cpp:559
#14 0x0000560bbf4cc4e8 in CClient::Run() (this=this@entry=0x7f1438c7d010)
    at /media/ddnet/src/engine/client/client.cpp:3171
#15 0x0000560bbf407c97 in main(int, char const**) (argc=<optimized out>, argv=<optimized out>)
    at /media/ddnet/src/engine/client/client.cpp:4710
```
New failure for me in `!xcb_xlib_threads_sequence_lost` assertion on Linux

**Comment by def-** [comment]
Seems to be the same issue as reported here: https://github.com/ppy/osu/discussions/21474
