### ISSUE TITLE
DDNet: xcb_io.c:278: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed

### ISSUE THREAD

**Issue by Zwelf** [ddnet/ddnet#6161]
```
2022-12-18 14:02:23 I client: starting...
2022-12-18 14:02:23 I sdl: SDL version 2.26.1 (compiled = 2.26.1)
2022-12-18 14:02:23 I gfx: Created OpenGL 3.0 context.
2022-12-18 14:02:23 I opengl: Vendor string: AMD
2022-12-18 14:02:23 I opengl: Version string: 4.6 (Compatibility Profile) Mesa 22.3.1
2022-12-18 14:02:23 I gfx: GPU vendor: AMD
2022-12-18 14:02:23 I gfx: GPU renderer: AMD Radeon Graphics (renoir, LLVM 14.0.6, DRM 3.48, 6.0.12-arch1-1)
2022-12-18 14:02:23 I gfx: GPU version: 4.6 (Compatibility Profile) Mesa 22.3.1
2022-12-18 14:02:24 I client/sound: sound init successful using audio driver 'pulseaudio'
2022-12-18 14:02:24 I freetype: freetype version 2.12.1 (compiled = 2.12.1)
2022-12-18 14:02:24 I textrender: loaded font from 'data/fonts/Icons.otf'
2022-12-18 14:02:24 I joystick: No joysticks found


[xcb] Unknown sequence number while processing queue
[xcb] You called XInitThreads, this is not your fault
[xcb] Aborting, sorry about that.
DDNet: xcb_io.c:278: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
```

```
(gdb) bt
#0  0x00007ffff4ca164c in  () at /usr/lib/libc.so.6
#1  0x00007ffff4c51958 in raise () at /usr/lib/libc.so.6
#2  0x00007ffff4c3b53d in abort () at /usr/lib/libc.so.6
#3  0x00007ffff4c3b45c in  () at /usr/lib/libc.so.6
#4  0x00007ffff4c4a486 in  () at /usr/lib/libc.so.6
#5  0x00007fffe88fea12 in  () at /usr/lib/libX11.so.6
#6  0x00007fffe88fead6 in  () at /usr/lib/libX11.so.6
#7  0x00007fffe8901752 in _XEventsQueued () at /usr/lib/libX11.so.6
#8  0x00007fffe88dee57 in XCheckIfEvent () at /usr/lib/libX11.so.6
#9  0x00007ffff7cba2dd in  () at /usr/lib/libSDL2-2.0.so.0
#10 0x00007ffff7c07329 in  () at /usr/lib/libSDL2-2.0.so.0
#11 0x00007ffff7c07727 in  () at /usr/lib/libSDL2-2.0.so.0
#12 0x0000555555767dea in CInput::Update() (this=0x555555d587f0) at /home/user/dev/ddnet/src/engine/client/input.cpp:553
#13 0x0000555555723623 in CClient::Run() (this=0x7fffe4ce0010) at /home/user/dev/ddnet/src/engine/client/client.cpp:3171
#14 0x000055555572cf5d in main(int, char const**) (argc=1, argv=0x7fffffffe718) at /home/user/dev/ddnet/src/engine/client/client.cpp:4710
```
I'm using Arch Linux with Gnome as desktop environment. It started today. Yesterday I could play normally (but I'm only using this device since yesterday). The crash happens on master, 16.6 and 16.5. So probably a library update that caused it?

**Comment by Jupeyy** [comment]
https://github.com/ddnet/ddnet/issues/6157#issuecomment-1356497078

**Comment by Zwelf** [comment]
Oh, thanks. Didn't see that issue.

**Comment by Zwelf** [comment]
Closing as duplicate of #6157 and it is most likely not a problem in this repository
