### ISSUE TITLE
Master info sometimes missing skins

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#6366]
![Screenshot_2023-02-26_at_12 38 28](https://user-images.githubusercontent.com/2335377/221408363-6d85ae97-8e8a-46f1-b12c-f68471bbc134.png)
@heinrich5991 any idea? Is this a master server issue or server not reporting skins to master server?

**Comment by heinrich5991** [comment]
Check the map info. If it includes a sha256, then this is the backward compatibility server info and the normal registering process failed. If it does not, there's something even weirder going on.

The master server does not inspect the server info JSON, it just passes it through.

**Comment by def-** [comment]
Ok, then that means we have official servers failing to register via https, strange.

**Comment by def-** [comment]
Indeed, this is a master registration problem, ger2.ddnet.org:8298 right now:
```
2023-03-05 14:26:56 I http: https://master1.ddnet.org/ddnet/15/register failed. libcurl error (22): The requested URL returned error: 400
2023-03-05 14:26:56 E register/6/ipv4: error response from master
```

**Comment by def-** [comment]
@heinrich5991 There seems to be no failure in cloudflare and none in nginx. Is there any way to log the errors in httpmaster?

**Comment by def-** [comment]
I have now printed out the requests in nginx and there seems to be corrupt data at the end of the json:
```
{"max_clients":63,"max_players":63,"passworded":false,"game_type":"DDraceNetwork","name":"DDNet CHN2 \xE7\xA7\xA6\xE7\x9A\x87\xE5\xB2\x9B - Brutal \xE9\xAB\x98\xE9\x98\xB6","map":{"name":"Yeyou 6","sha256":"8af189cf6f05b16c9ff8b6416031e440cc9d8182b1939d4f75500cf46f1d228d","size":556185},"version":"0.6.4, 16.7.2","clients":[{"name":"(connecting)","clan":"","country":156,"score":0,"is_player":false\xE5\x97\x8E\xE6\xAF\x94}]}
```
Feels like I'm getting closer.

**Comment by def-** [comment]
Second issue, contains garbage unicode inside of strings, which can't be decoded:
```
{"max_clients":63,"max_players":63,"passworded":false,"game_type":"DDraceNetwork","name":"DDNet RUS - Novice","map":{"name":"Multeasymap","sha256":"5c80d1f6832fb4440962f8d0c9eeb8f670cdb7edee97bec8a10618955d1b914c","size":445478},"version":"0.6.4, 16.7.2","clients":[{"name":"Goldv3","clan":"","country":-1,"score":-9999,"is_player":true,"skin":{"name":"nersif"},"afk":false,"team":0},{"name":"noah.quignon","clan":"","country":-1,"score":-1507,"is_player":true,"skin":{"name":"glowdarkerfox4ahl"},"afk":false,"team":0},{"name":"nezna1o","clan":"","country":-1,"score":-9999,"is_player":true,"skin":{"name":"blacktee","color_body":12386048,"color_feet":13107199},"afk":false,"team":0},{"name":"SW:M1ku","clan":"","country":-1,"score":-9999,"is_player":true,"skin":{"name":"tkitty"},"afk":false,"team":0},{"name":"mjek642","clan":"","country":-1,"score":-1476,"is_player":true,"skin":{"name":"cutekitty"},"afk":false,"team":0},{"name":"\xD0\xB1\xD0\xB0\xD1\x80\xD0\xB0\xD1\x88\xD0\xB5\xD0\xBA","clan":"\xD0\xBF\xD0\xB5\xD1\x82\xD1\x83\xD1\x85","country":376,"score":-633,"is_player":true,"skin":{"name":"blacktee","color_body":11271936,"color_feet":10682193},"afk":false,"team":0},{"name":"axolotli","clan":"","country":-1,"score":-9999,"is_player":true,"skin":{"name":"axolotl"},"afk":false,"team":0},{"name":"anka1812008","clan":"","country":-1,"score":-9999,"is_player":true,"skin":{"name":"default"},"afk":false,"team":0},{"name":"\xE3\x81\x82\xE3\x81\xAA\xE3\x81\x9F\xE3\x81\xAF\xE7\xB5\x82","clan":"","country":-1,"score":-9999,"is_player":true,"skin":{"name":"Tunda"},"afk":false,"team":0},{"name":"ZXC \xD0\xA5\xD0\xA3\xD0\x99","clan":"","country":-1,"score":-696,"is_player":true,"skin":{"name":"kitty_saddo"},"afk":false,"team":0},{"name":"DONT KNOW)","clan":"Bingiling","country":-1,"score":-9999,"is_player":true,"skin":{"name":"gayfox"},"afk":false,"team":0},{"name":"gogolll1349","clan":"","country":-1,"score":-9999,"is_player":true,"skin":{"name":"default"},"afk":false,"team":0},{"name":"h1zer x absolut","clan":"","country":643,"score":-1150,"is_player":true,"skin":{"name":"turtle_m"},"afk":false,"team":0},{"name":"Eriichi","clan":"","country":643,"score":-9999,"is_player":true,"skin":{"name":"chinese_by_whis","color_body":262144,"color_feet":0},"afk":false,"team":0},{"name":"\xE3\x83\x80\xE3\x83\x81\xE3\x83\xA7\xE3\x82\xA6\xE3\x81\xAE","clan":"","country":643,"score":-9999,"is_player":true,"skin":{"name":""},"afk":false,"team":0},{"name":"C-Moon","clan":"\xD0\xBB\xD1\x83\xD0\xBD\xD0\xB0","country":643,"score":-1378,"is_player":true,"skin":{"name":"EmeraldCat"},"afk":true,"team":0},{"name":"\xD0\xBA\xD1\x80\xD0\xB8\xD0\xBF","clan":"\xD1\x80\xD1\x83\xD1\x81\xD1\x81\xD0\xBA","country":662,"score":-9999,"is_player":true,"skin":{"name":"creeper"},"afk":false,"team":0},{"name":"DolbiT:D","clan":"","country":-1,"score":-9999,"is_player":true,"skin":{"body":{"name":"standard",color:4783872},"marking":{"name":"",color:-16776961},"decoration":{"name":"",color:1798004},"hands":{"name":"standard",color:16711424},"feet":{"name":"standard",color:16776960},"eyes":{"name":"standard",color:10928973}},"afk":false,"team":0},{"name":"Florency","clan":"","country":-1,"score":-602,"is_player":true,"skin":{"name":"whis","color_body":589568,"color_feet":2948864},"afk":false,"team":0}]}
```
On this part:
```
>>> b"xD0\xBA\xD1\x80\xD0\xB8\xD0\xBF".decode("utf-8")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xba in position 3: invalid start byte
```
I think hand-rolling json is a horrible mistake.

**Comment by def-** [comment]
Second problem:
```
>>> x = '{"max_clients":63,"max_players":63,"passworded":false,"game_type":"DDraceNetwork","name":"DDNet RUS - Novice","map":{"name":"Multeasymap","sha256":"5c80d1f6832fb4440962f8d0c9eeb8f670cdb7edee97bec8a10618955d1b914c","size":445478},"version":"0.6.4, 16.7.2","clients":[{"name":"Goldv3","clan":"","country":-1,"score":-9999,"is_player":true,"skin":{"name":"nersif"},"afk":false,"team":0},{"name":"noah.quignon","clan":"","country":-1,"score":-1507,"is_player":true,"skin":{"name":"glowdarkerfox4ahl"},"afk":false,"team":0},{"name":"nezna1o","clan":"","country":-1,"score":-9999,"is_player":true,"skin":{"name":"blacktee","color_body":12386048,"color_feet":13107199},"afk":false,"team":0},{"name":"SW:M1ku","clan":"","country":-1,"score":-9999,"is_player":true,"skin":{"name":"tkitty"},"afk":false,"team":0},{"name":"mjek642","clan":"","country":-1,"score":-1476,"is_player":true,"skin":{"name":"cutekitty"},"afk":false,"team":0},{"name":"барашек","clan":"петух","country":376,"score":-633,"is_player":true,"skin":{"name":"blacktee","color_body":11271936,"color_feet":10682193},"afk":false,"team":0},{"name":"axolotli","clan":"","country":-1,"score":-9999,"is_player":true,"skin":{"name":"axolotl"},"afk":false,"team":0},{"name":"anka1812008","clan":"","country":-1,"score":-9999,"is_player":true,"skin":{"name":"default"},"afk":false,"team":0},{"name":"あなたは終","clan":"","country":-1,"score":-9999,"is_player":true,"skin":{"name":"Tunda"},"afk":false,"team":0},{"name":"ZXC ХУЙ","clan":"","country":-1,"score":-696,"is_player":true,"skin":{"name":"kitty_saddo"},"afk":false,"team":0},{"name":"DONT KNOW)","clan":"Bingiling","country":-1,"score":-9999,"is_player":true,"skin":{"name":"gayfox"},"afk":false,"team":0},{"name":"gogolll1349","clan":"","country":-1,"score":-9999,"is_player":true,"skin":{"name":"default"},"afk":false,"team":0},{"name":"h1zer x absolut","clan":"","country":643,"score":-1150,"is_player":true,"skin":{"name":"turtle_m"},"afk":false,"team":0},{"name":"Eriichi","clan":"","country":643,"score":-9999,"is_player":true,"skin":{"name":"chinese_by_whis","color_body":262144,"color_feet":0},"afk":false,"team":0},{"name":"ダチョウの","clan":"","country":643,"score":-9999,"is_player":true,"skin":{"name":""},"afk":false,"team":0},{"name":"C-Moon","clan":"луна","country":643,"score":-1378,"is_player":true,"skin":{"name":"EmeraldCat"},"afk":true,"team":0},{"name":"крип","clan":"русск","country":662,"score":-9999,"is_player":true,"skin":{"name":"creeper"},"afk":false,"team":0},{"name":"DolbiT:D","clan":"","country":-1,"score":-9999,"is_player":true,"skin":{"body":{"name":"standard",color:4783872},"marking":{"name":"",color:-16776961},"decoration":{"name":"",color:1798004},"hands":{"name":"standard",color:16711424},"feet":{"name":"standard",color:16776960},"eyes":{"name":"standard",color:10928973}},"afk":false,"team":0},{"name":"Florency","clan":"","country":-1,"score":-602,"is_player":true,"skin":{"name":"whis","color_body":589568,"color_feet":2948864},"afk":false,"team":0}]}'
>>> json.loads(x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2597 (char 2597)
```
Hand rolling json is a horrible idea: `{"name":"standard",color:4783872}`, that should be `"color"`, not `color`.
