### ISSUE TITLE
New UBSAN findings from official server

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#6650]
```
/home/teeworlds/src/master/src/engine/shared/snapshot.cpp:206:21: runtime error: signed integer overflow: 1645289600 - -2139062144 cannot be represented in type 'int'
    #0 0x7650b7 in CSnapshotDelta::DiffItem(int const*, int const*, int*, int) /home/teeworlds/src/master/src/engine/shared/snapshot.cpp:206:21
    #1 0x765cea in CSnapshotDelta::CreateDelta(CSnapshot*, CSnapshot*, void*) /home/teeworlds/src/master/src/engine/shared/snapshot.cpp:323:7
    #2 0x51a0e2 in CServer::DoSnapshot() /home/teeworlds/src/master/src/engine/server/server.cpp:964:36
    #3 0x537486 in CServer::Run() /home/teeworlds/src/master/src/engine/server/server.cpp:2818:6
    #4 0x4feeb7 in main /home/teeworlds/src/master/src/engine/server/main.cpp:190:21
    #5 0x7efd50c4ed09 in __libc_start_main csu/../csu/libc-start.c:308:16
    #6 0x4c3819 in _start (/home/teeworlds/servers/DDNet-Server-ubsan+0x4c3819)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/teeworlds/src/master/src/engine/shared/snapshot.cpp:206:21 in
/home/teeworlds/src/master/src/game/server/entities/character.cpp:1364:22: runtime error: -nan is outside the range of representable values of type 'int'
    #0 0x5ac7fd in CCharacter::HandleSkippableTiles(int) /home/teeworlds/src/master/src/game/server/entities/character.cpp:1364:22
    #1 0x59fa77 in CCharacter::DDRacePostCoreTick() /home/teeworlds/src/master/src/game/server/entities/character.cpp:2083:2
    #2 0x59e92e in CCharacter::Tick() /home/teeworlds/src/master/src/game/server/entities/character.cpp:760:2
    #3 0x66e013 in CGameWorld::Tick() /home/teeworlds/src/master/src/game/server/gameworld.cpp:287:11
    #4 0x607d31 in CGameContext::OnTick() /home/teeworlds/src/master/src/game/server/gamecontext.cpp:945:10
    #5 0x5371cb in CServer::Run() /home/teeworlds/src/master/src/engine/server/server.cpp:2807:19
    #6 0x4feeb7 in main /home/teeworlds/src/master/src/engine/server/main.cpp:190:21
    #7 0x7fc51ec27d09 in __libc_start_main csu/../csu/libc-start.c:308:16
    #8 0x4c3819 in _start (/home/teeworlds/servers/DDNet-Server-ubsan+0x4c3819)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/teeworlds/src/master/src/game/server/entities/character.cpp:1364:22 in
/home/teeworlds/src/master/src/base/math.h:128:20: runtime error: negation of -2147483648 cannot be represented in type 'int'; cast to an unsigned type to negate this value to itself
    #0 0x5ac88f in int absolute<int>(int) /home/teeworlds/src/master/src/base/math.h:128:20
    #1 0x5ac88f in CCharacter::HandleSkippableTiles(int) /home/teeworlds/src/master/src/game/server/entities/character.cpp:1364:8
    #2 0x59fa77 in CCharacter::DDRacePostCoreTick() /home/teeworlds/src/master/src/game/server/entities/character.cpp:2083:2
    #3 0x59e92e in CCharacter::Tick() /home/teeworlds/src/master/src/game/server/entities/character.cpp:760:2
    #4 0x66e013 in CGameWorld::Tick() /home/teeworlds/src/master/src/game/server/gameworld.cpp:287:11
    #5 0x607d31 in CGameContext::OnTick() /home/teeworlds/src/master/src/game/server/gamecontext.cpp:945:10
    #6 0x5371cb in CServer::Run() /home/teeworlds/src/master/src/engine/server/server.cpp:2807:19
    #7 0x4feeb7 in main /home/teeworlds/src/master/src/engine/server/main.cpp:190:21
    #8 0x7fc51ec27d09 in __libc_start_main csu/../csu/libc-start.c:308:16
    #9 0x4c3819 in _start (/home/teeworlds/servers/DDNet-Server-ubsan+0x4c3819)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/teeworlds/src/master/src/base/math.h:128:20 in
/home/teeworlds/src/master/src/game/server/entities/character.cpp:1366:27: runtime error: -nan is outside the range of representable values of type 'int'
    #0 0x5ac8c3 in CCharacter::HandleSkippableTiles(int) /home/teeworlds/src/master/src/game/server/entities/character.cpp:1366:27
    #1 0x59fa77 in CCharacter::DDRacePostCoreTick() /home/teeworlds/src/master/src/game/server/entities/character.cpp:2083:2
    #2 0x59e92e in CCharacter::Tick() /home/teeworlds/src/master/src/game/server/entities/character.cpp:760:2
    #3 0x66e013 in CGameWorld::Tick() /home/teeworlds/src/master/src/game/server/gameworld.cpp:287:11
    #4 0x607d31 in CGameContext::OnTick() /home/teeworlds/src/master/src/game/server/gamecontext.cpp:945:10
    #5 0x5371cb in CServer::Run() /home/teeworlds/src/master/src/engine/server/server.cpp:2807:19
    #6 0x4feeb7 in main /home/teeworlds/src/master/src/engine/server/main.cpp:190:21
    #7 0x7fc51ec27d09 in __libc_start_main csu/../csu/libc-start.c:308:16
    #8 0x4c3819 in _start (/home/teeworlds/servers/DDNet-Server-ubsan+0x4c3819)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/teeworlds/src/master/src/game/server/entities/character.cpp:1366:27 in
/home/teeworlds/src/master/src/game/collision.cpp:485:17: runtime error: -nan is outside the range of representable values of type 'int'
    #0 0x79b758 in CCollision::MoveBox(vector2_base<float>*, vector2_base<float>*, vector2_base<float>, float) const /home/teeworlds/src/master/src/game/collision.cpp:485:17
    #1 0x7a6a68 in CCharacterCore::Move() /home/teeworlds/src/master/src/game/gamecore.cpp:494:16
    #2 0x5a1261 in CCharacter::TickDeferred() /home/teeworlds/src/master/src/game/server/entities/character.cpp:794:9
    #3 0x66e243 in CGameWorld::Tick() /home/teeworlds/src/master/src/game/server/gameworld.cpp:296:11
    #4 0x607d31 in CGameContext::OnTick() /home/teeworlds/src/master/src/game/server/gamecontext.cpp:945:10
    #5 0x5371cb in CServer::Run() /home/teeworlds/src/master/src/engine/server/server.cpp:2807:19
    #6 0x4feeb7 in main /home/teeworlds/src/master/src/engine/server/main.cpp:190:21
    #7 0x7fc51ec27d09 in __libc_start_main csu/../csu/libc-start.c:308:16
    #8 0x4c3819 in _start (/home/teeworlds/servers/DDNet-Server-ubsan+0x4c3819)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/teeworlds/src/master/src/game/collision.cpp:485:17 in
/home/teeworlds/src/master/src/base/math.h:16:40: runtime error: -nan is outside the range of representable values of type 'int'
    #0 0x7a75b7 in round_to_int(float) /home/teeworlds/src/master/src/base/math.h
    #1 0x7a75b7 in CCharacterCore::Write(CNetObj_CharacterCore*) /home/teeworlds/src/master/src/game/gamecore.cpp:551:21
    #2 0x7a7f8e in CCharacterCore::Quantize() /home/teeworlds/src/master/src/game/gamecore.cpp:641:2
    #3 0x5a1362 in CCharacter::TickDeferred() /home/teeworlds/src/master/src/game/server/entities/character.cpp:796:9
    #4 0x66e243 in CGameWorld::Tick() /home/teeworlds/src/master/src/game/server/gameworld.cpp:296:11
    #5 0x607d31 in CGameContext::OnTick() /home/teeworlds/src/master/src/game/server/gamecontext.cpp:945:10
    #6 0x5371cb in CServer::Run() /home/teeworlds/src/master/src/engine/server/server.cpp:2807:19
    #7 0x4feeb7 in main /home/teeworlds/src/master/src/engine/server/main.cpp:190:21
    #8 0x7fc51ec27d09 in __libc_start_main csu/../csu/libc-start.c:308:16
    #9 0x4c3819 in _start (/home/teeworlds/servers/DDNet-Server-ubsan+0x4c3819)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/teeworlds/src/master/src/base/math.h:16:40 in
/home/teeworlds/src/master/src/engine/shared/snapshot.cpp:206:21: runtime error: signed integer overflow: 256 - -2147483648 cannot be represented in type 'int'
    #0 0x7650b7 in CSnapshotDelta::DiffItem(int const*, int const*, int*, int) /home/teeworlds/src/master/src/engine/shared/snapshot.cpp:206:21
    #1 0x765cea in CSnapshotDelta::CreateDelta(CSnapshot*, CSnapshot*, void*) /home/teeworlds/src/master/src/engine/shared/snapshot.cpp:323:7
    #2 0x51a0e2 in CServer::DoSnapshot() /home/teeworlds/src/master/src/engine/server/server.cpp:964:36
    #3 0x537486 in CServer::Run() /home/teeworlds/src/master/src/engine/server/server.cpp:2818:6
    #4 0x4feeb7 in main /home/teeworlds/src/master/src/engine/server/main.cpp:190:21
    #5 0x7fc51ec27d09 in __libc_start_main csu/../csu/libc-start.c:308:16
    #6 0x4c3819 in _start (/home/teeworlds/servers/DDNet-Server-ubsan+0x4c3819)
```
Found while hunting for https://github.com/ddnet/ddnet/issues/6597, they seem unrelated.

**Comment by Robyt3** [comment]
Most of these seem to be caused by the character core velocity being NaN. Any way to find out at this point on which maps this undefined behavior was triggered?

**Comment by def-** [comment]
No

**Comment by AssassinTee** [comment]
> Most of these seem to be caused by the character core velocity being NaN. Any way to find out at this point on which maps this undefined behavior was triggered?

@Robyt3 Yes, I know how to make your velocity NaN: Use the old speedtiles and put them into a setup like this:

<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/78dc434a-0fb2-4b0c-90cb-58613d5419d8" />

https://github.com/user-attachments/assets/00641ae4-3dea-4ab6-bf38-cd639d0dad8a

(for reproducability: DO NOT hold right in the speedtiles, try to double jump as close over the ground as possible)

I was told this is a feature and that it's used in maps:

It's used at the end of https://ddnet.org/maps/Broken-32-brain

And it's used to enter the secret on `Cosyris 2`

**Comment by heinrich5991** [comment]
Usually, you can fix this without changing physics, by replacing the UB with the behavior that this UB usually produced.

**Comment by AssassinTee** [comment]
> Usually, you can fix this without changing physics, by replacing the UB with the behavior that this UB usually produced.

I know of a server, that had issues with this - by using a different compiler/OS, they weren't able to reproduce this anymore
