### ISSUE TITLE
server: double free or corruption (!prev)

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#6843]
```
Core was generated by `./DDRace64-Server_sql -f servers/block2.cfg'.
Program terminated with signal SIGABRT, Aborted.
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.
[Current thread is 1 (Thread 0x7f5e12c0ba00 (LWP 1469313))]
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
#1  0x00007f5e1375fd2f in __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  0x00007f5e13710ef2 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007f5e136fb472 in __GI_abort () at ./stdlib/abort.c:79
#4  0x00007f5e137542d0 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7f5e1386e459 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#5  0x00007f5e1376964a in malloc_printerr (str=str@entry=0x7f5e13871138 "double free or corruption (!prev)") at ./malloc/malloc.c:5660
#6  0x00007f5e1376b6bc in _int_free (av=0x7f5e138a7c60 <main_arena>, p=0x5581b2278ab0, have_lock=<optimized out>, have_lock@entry=0) at ./malloc/malloc.c:4587
#7  0x00007f5e1376dd2f in __GI___libc_free (mem=<optimized out>) at ./malloc/malloc.c:3385
#8  0x00007f5e14281409 in frame_dummy () from /home/teeworlds/servers/libantibot.so
#9  0x00007f5e000036ee in ?? ()
#10 0x00005581af0e5140 in gs_PoolDataCPlayer ()
#11 0x00007f5e11d8e670 in ?? ()
#12 0x0000000000000002 in ?? ()
#13 0x00007f5e10647020 in ?? ()
#14 0x00005581af0e5140 in gs_PoolDataCPlayer ()
#15 0x00007f5e11d8ee7c in ?? ()
#16 0x00005581aee61ffd in CPlayer::~CPlayer (this=0x5581b111d090, this@entry=0x5581b0dd7c60,  __in_chrg=<optimized out>) at /home/teeworlds/src/master/src/game/server/player.cpp:35
#17 0x00005581aee49e03 in CGameContext::OnClientDrop (this=0x7f5e10647010, ClientID=-1315688096, pReason=0x2 <error: Cannot access memory at address 0x2>) at /home/teeworlds/src/master/src/game/server/gamecontext.cpp:1639
#18 0x00005581aee1d8e1 in CServer::DelClientCallback (ClientID=2, pReason=0x7f5e11d8e670 "", pUser=0x7f5e1168a010) at /home/teeworlds/src/master/src/engine/server/server.cpp:1151
#19 0x00005581aeeba43b in CNetServer::Drop (pReason=0x7f5e11d8e670 "", ClientID=2, this=0x7f5e11d75490) at /home/teeworlds/src/master/src/engine/shared/network_server.cpp:104
#20 CNetServer::Update (this=this@entry=0x7f5e11d75490) at /home/teeworlds/src/master/src/engine/shared/network_server.cpp:120
#21 0x00005581aee2669d in CServer::PumpNetwork (this=this@entry=0x7f5e1168a010, PacketWaiting=PacketWaiting@entry=true) at /home/teeworlds/src/master/src/engine/server/server.cpp:2372
#22 0x00005581aee27694 in CServer::Run (this=this@entry=0x7f5e1168a010) at /home/teeworlds/src/master/src/engine/server/server.cpp:2866
#23 0x00005581aee0e529 in main (argc=<optimized out>, argv=<optimized out>) at /home/teeworlds/src/master/src/engine/server/main.cpp:191
```
@Jupeyy interested in looking into this even though the previous double free looks unrelated? https://github.com/ddnet/ddnet/issues/4785

**Comment by Jupeyy** [comment]
I don't have access to the antibot source code, so I cannot help, sry

**Comment by def-** [comment]
Oh, I missed the antibot in there. noby to the rescue!

**Comment by ChillerDragon** [comment]
Imo this issue should be moved to the antibot repo.
