### ISSUE TITLE
Crash in AntibotOnDirectInput

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#7101]
Happening hundreds of times on official servers:
```
Core was generated by `./DDRace64-Server_sql -f servers/8304.cfg'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f36d81b877b in ?? () from /home/teeworlds/servers/libantibot.so
[Current thread is 1 (Thread 0x7f36d6b37a00 (LWP 11904))]
(gdb) bt
#0  0x00007f36d81b877b in ?? () from /home/teeworlds/servers/libantibot.so
#1  0x00007f36d81adcec in AntibotOnDirectInput () from /home/teeworlds/servers/libantibot.so
#2  0x000055d10ae87f05 in CCharacter::OnDirectInput (this=0x55d10b0dcc60 <gs_PoolDataCCharacter>,
    pNewInput=0x7f36d4575620) at /home/teeworlds/src/master/src/game/server/entities/character.cpp:685
#3  0x000055d10aead098 in CPlayer::OnPredictedEarlyInput (this=<optimized out>,
    pNewInput=pNewInput@entry=0x7f36d4575620)
    at /home/teeworlds/src/master/src/game/server/player.cpp:566
#4  0x000055d10ae933c4 in CGameContext::OnClientPredictedEarlyInput (this=0x7f36d4565010, ClientID=0,
    pInput=<optimized out>) at /home/teeworlds/src/master/src/game/server/gamecontext.cpp:1307
#5  0x000055d10ae77de6 in CServer::Run (this=this@entry=0x7f36d55b5010)
    at /home/teeworlds/src/master/src/engine/server/server.cpp:2868
#6  0x000055d10ae62370 in main (argc=<optimized out>, argv=<optimized out>)
    at /home/teeworlds/src/master/src/engine/server/main.cpp:197
```
@heinrich5991 maybe related to your recent change?

**Comment by heinrich5991** [comment]
I added debug symbols to the antibot.

**Comment by heinrich5991** [comment]
Fixed the bug, probably.
