### ISSUE TITLE
Crash in CCollision::TileExists

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#7218]
```
Core was generated by `./DDRace64-Server_sql -f servers/block.cfg'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00005605936e3546 in CCollision::TileExists (this=0x7fcdd84f50b0, Index=Index@entry=12835)
    at /home/teeworlds/src/master/src/game/collision.cpp:819
819		if((m_pTiles[Index].m_Index >= TILE_FREEZE && m_pTiles[Index].m_Index <= TILE_TELE_LASER_DISABLE) || (m_pTiles[Index].m_Index >= TILE_LFREEZE && m_pTiles[Index].m_Index <= TILE_LUNFREEZE))
[Current thread is 1 (Thread 0x7fcddaac7a00 (LWP 1109761))]
(gdb) bt
#0  0x00005605936e3546 in CCollision::TileExists (this=0x7fcdd84f50b0, Index=Index@entry=12835)
    at /home/teeworlds/src/master/src/game/collision.cpp:819
#1  0x00005605936e368c in CCollision::GetMapIndex (this=<optimized out>, Pos=...)
    at /home/teeworlds/src/master/src/game/collision.cpp:884
#2  0x000056059364d6ce in CCharacter::HandleTuneLayer (
    this=this@entry=0x5605938a3c60 <gs_PoolDataCCharacter>)
    at /home/teeworlds/src/master/src/game/server/entities/character.cpp:1913
#3  0x000056059364d9df in CCharacter::DDRaceTick (this=this@entry=0x5605938a3c60 <gs_PoolDataCCharacter>)
    at /home/teeworlds/src/master/src/game/server/entities/character.cpp:2007
#4  0x000056059364dd30 in CCharacter::PreTick (this=0x5605938a3c60 <gs_PoolDataCCharacter>)
    at /home/teeworlds/src/master/src/game/server/entities/character.cpp:737
#5  0x0000560593653205 in CCharacter::Tick (this=0x5605938a3c60 <gs_PoolDataCCharacter>)
    at /home/teeworlds/src/master/src/game/server/entities/character.cpp:756
#6  0x00005605936720ba in CGameWorld::Tick (this=this@entry=0x7fcdd8506068)
    at /home/teeworlds/src/master/src/game/server/gameworld.cpp:287
#7  0x00005605936678be in CGameContext::OnTick (this=0x7fcdd84f5010)
    at /home/teeworlds/src/master/src/game/server/gamecontext.cpp:951
#8  0x000056059363ef54 in CServer::Run (this=this@entry=0x7fcdd9545010)
    at /home/teeworlds/src/master/src/engine/server/server.cpp:2893
#9  0x0000560593629370 in main (argc=<optimized out>, argv=<optimized out>)
    at /home/teeworlds/src/master/src/engine/server/main.cpp:197
(gdb) print Index
$1 = 12835
(gdb) print m_pTiles
$2 = (CTile *) 0x7fcdd83bb010
(gdb) print *m_pTiles
Cannot access memory at address 0x7fcdd83bb010
```

**Comment by def-** [comment]
Related:
```
Core was generated by `./DDRace64-Server_sql -f servers/block.cfg'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000056168cc7aa27 in CCollision::TileExists (this=0x7fd1a00430b0, Index=Index@entry=13648)
    at /home/teeworlds/src/master/src/game/collision.cpp:825
825		if(m_pSpeedup && m_pSpeedup[Index].m_Force > 0)
[Current thread is 1 (Thread 0x7fd1a2e1ca00 (LWP 346322))]
(gdb) bt
#0  0x000056168cc7aa27 in CCollision::TileExists (this=0x7fd1a00430b0, Index=Index@entry=13648)
    at /home/teeworlds/src/master/src/game/collision.cpp:825
#1  0x000056168cc7aaec in CCollision::GetMapIndex (this=<optimized out>, Pos=...)
    at /home/teeworlds/src/master/src/game/collision.cpp:884
#2  0x000056168cbe435e in CCharacter::HandleTuneLayer (
    this=this@entry=0x56168ce3dc00 <gs_PoolDataCCharacter>)
    at /home/teeworlds/src/master/src/game/server/entities/character.cpp:1914
#3  0x000056168cbe464f in CCharacter::DDRaceTick (this=this@entry=0x56168ce3dc00 <gs_PoolDataCCharacter>)
    at /home/teeworlds/src/master/src/game/server/entities/character.cpp:2008
#4  0x000056168cbe49a0 in CCharacter::PreTick (this=0x56168ce3dc00 <gs_PoolDataCCharacter>)
    at /home/teeworlds/src/master/src/game/server/entities/character.cpp:737
#5  0x000056168cbe9ee5 in CCharacter::Tick (this=0x56168ce3dc00 <gs_PoolDataCCharacter>)
    at /home/teeworlds/src/master/src/game/server/entities/character.cpp:756
#6  0x000056168cc09402 in CGameWorld::Tick (this=this@entry=0x7fd1a0054068)
    at /home/teeworlds/src/master/src/game/server/gameworld.cpp:224
#7  0x000056168cc01abc in CGameContext::OnTick (this=0x7fd1a0043010)
    at /home/teeworlds/src/master/src/game/server/gamecontext.cpp:949
#8  0x000056168cbd58b4 in CServer::Run (this=this@entry=0x7fd1a189c010)
    at /home/teeworlds/src/master/src/engine/server/server.cpp:2895
#9  0x000056168cbbfc70 in main (argc=<optimized out>, argv=<optimized out>)
    at /home/teeworlds/src/master/src/engine/server/main.cpp:197
```
