### ISSUE TITLE
macOS CI sometimes fails with `hdiutil: couldn't eject "disk2" - Resource busy`

### ISSUE THREAD

**Issue by Robyt3** [ddnet/ddnet#7545]
Relevant log from https://github.com/ddnet/ddnet/actions/runs/6989141790/job/19017413776?pr=7540:

```
  cd release
  cmake --build . --config Release --target package_default 
  mkdir artifacts
  mv *-macos.dmg artifacts
  shell: /bin/bash -e {0}
  env:
    CARGO_HTTP_MULTIPLEXING: false
    CACHE_ON_FAILURE: false
    CARGO_INCREMENTAL: 0
[1/1] Generating DDNet-17.4-macos.dmg
FAILED: DDNet-17.4-macos.dmg /Users/runner/work/ddnet/ddnet/release/DDNet-17.4-macos.dmg 
cd /Users/runner/work/ddnet/ddnet/release && /usr/local/Cellar/cmake/3.27.7/bin/cmake -E remove_directory pack_DDNet-17.4-macos_dmg && /usr/local/Cellar/cmake/3.27.7/bin/cmake -E make_directory pack_DDNet-17.4-macos_dmg/DDNet.app && /usr/local/Cellar/cmake/3.27.7/bin/cmake -E make_directory pack_DDNet-17.4-macos_dmg/DDNet.app/Contents && /usr/local/Cellar/cmake/3.27.7/bin/cmake -E make_directory pack_DDNet-17.4-macos_dmg/DDNet.app/Contents/Frameworks && /usr/local/Cellar/cmake/3.27.7/bin/cmake -E make_directory pack_DDNet-17.4-macos_dmg/DDNet.app/Contents/MacOS && /usr/local/Cellar/cmake/3.27.7/bin/cmake -E make_directory pack_DDNet-17.4-macos_dmg/DDNet.app/Contents/Resources && /usr/local/Cellar/cmake/3.27.7/bin/cmake -E make_directory pack_DDNet-17.4-macos_dmg/DDNet-Server.app && /usr/local/Cellar/cmake/3.27.7/bin/cmake -E make_directory pack_DDNet-17.4-macos_dmg/DDNet-Server.app/Contents && /usr/local/Cellar/cmake/3.27.7/bin/cmake -E make_directory pack_DDNet-17.4-macos_dmg/DDNet-Server.app/Contents/MacOS && /usr/local/Cellar/cmake/3.27.7/bin/cmake -E make_directory pack_DDNet-17.4-macos_dmg/DDNet-Server.app/Contents/Resources && /usr/local/Cellar/cmake/3.27.7/bin/cmake -E make_directory pack_DDNet-17.4-macos_dmg/DDNet-Server.app/Contents/Resources/data && /usr/local/Cellar/cmake/3.27.7/bin/cmake -E make_directory pack_DDNet-17.4-macos_dmg/DDNet-Server.app/Contents/Resources/data/mapres && /usr/local/Cellar/cmake/3.27.7/bin/cmake -E copy_directory /Users/runner/work/ddnet/ddnet/data pack_DDNet-17.4-macos_dmg/DDNet.app/Contents/Resources/data && /usr/local/Cellar/cmake/3.27.7/bin/cmake -E copy /Users/runner/work/ddnet/ddnet/other/icons/DDNet.icns pack_DDNet-17.4-macos_dmg/DDNet.app/Contents/Resources/ && /usr/local/Cellar/cmake/3.27.7/bin/cmake -E copy bundle/client/Info.plist /Users/runner/work/ddnet/ddnet/other/bundle/client/PkgInfo pack_DDNet-17.4-macos_dmg/DDNet.app/Contents/ && /usr/local/Cellar/cmake/3.27.7/bin/cmake -E copy /Users/runner/work/ddnet/ddnet/release/DDNet /Users/runner/work/ddnet/ddnet/release/config_retrieve /Users/runner/work/ddnet/ddnet/release/config_store /Users/runner/work/ddnet/ddnet/release/demo_extract_chat /Users/runner/work/ddnet/ddnet/release/dilate /Users/runner/work/ddnet/ddnet/release/map_convert_07 /Users/runner/work/ddnet/ddnet/release/map_diff /Users/runner/work/ddnet/ddnet/release/map_extract pack_DDNet-17.4-macos_dmg/DDNet.app/Contents/MacOS/ && /usr/local/Cellar/cmake/3.27.7/bin/cmake -E copy_directory /Users/runner/work/ddnet/ddnet/ddnet-libs/sdl/mac/lib64/SDL2.framework pack_DDNet-17.4-macos_dmg/DDNet.app/Contents/Frameworks/SDL2.framework && /usr/local/Cellar/cmake/3.27.7/bin/cmake -E copy /Users/runner/work/ddnet/ddnet/ddnet-libs/discord/mac/lib64/discord_game_sdk.dylib pack_DDNet-17.4-macos_dmg/DDNet.app/Contents/Frameworks/ && /usr/local/Cellar/cmake/3.27.7/bin/cmake -E copy /Users/runner/work/ddnet/ddnet/ddnet-libs/freetype/mac/lib64/libfreetype.6.dylib pack_DDNet-17.4-macos_dmg/DDNet.app/Contents/Frameworks/ && /usr/local/Cellar/cmake/3.27.7/bin/cmake -E copy /Users/runner/work/ddnet/ddnet/ddnet-libs/png/mac/lib64/libpng16.16.dylib pack_DDNet-17.4-macos_dmg/DDNet.app/Contents/Frameworks/ && /usr/local/Cellar/cmake/3.27.7/bin/cmake -E copy /Users/runner/work/ddnet/ddnet/ddnet-libs/ffmpeg/mac/lib64/libavcodec.60.dylib pack_DDNet-17.4-macos_dmg/DDNet.app/Contents/Frameworks/ && /usr/local/Cellar/cmake/3.27.7/bin/cmake -E copy /Users/runner/work/ddnet/ddnet/ddnet-libs/ffmpeg/mac/lib64/libavformat.60.dylib pack_DDNet-17.4-macos_dmg/DDNet.app/Contents/Frameworks/ && /usr/local/Cellar/cmake/3.27.7/bin/cmake -E copy /Users/runner/work/ddnet/ddnet/ddnet-libs/ffmpeg/mac/lib64/libavutil.58.dylib pack_DDNet-17.4-macos_dmg/DDNet.app/Contents/Frameworks/ && /usr/local/Cellar/cmake/3.27.7/bin/cmake -E copy /Users/runner/work/ddnet/ddnet/ddnet-libs/ffmpeg/mac/lib64/libswresample.4.dylib pack_DDNet-17.4-macos_dmg/DDNet.app/Contents/Frameworks/ && /usr/local/Cellar/cmake/3.27.7/bin/cmake -E copy /Users/runner/work/ddnet/ddnet/ddnet-libs/ffmpeg/mac/lib64/libswscale.7.dylib pack_DDNet-17.4-macos_dmg/DDNet.app/Contents/Frameworks/ && /usr/local/Cellar/cmake/3.27.7/bin/cmake -E copy /Users/runner/work/ddnet/ddnet/release/libsteam_api.dylib pack_DDNet-17.4-macos_dmg/DDNet.app/Contents/Frameworks/ && /usr/local/Frameworks/Python.framework/Versions/3.12/bin/python3.12 /Users/runner/work/ddnet/ddnet/scripts/darwin_strip_rpath.py /usr/bin/otool /usr/bin/install_name_tool pack_DDNet-17.4-macos_dmg/DDNet.app/Contents/MacOS/DDNet && /usr/bin/install_name_tool -add_rpath @loader_path/../Frameworks pack_DDNet-17.4-macos_dmg/DDNet.app/Contents/MacOS/DDNet && /usr/local/Cellar/cmake/3.27.7/bin/cmake -E copy_directory /Users/runner/work/ddnet/ddnet/data/maps pack_DDNet-17.4-macos_dmg/DDNet-Server.app/Contents/Resources/data/maps && /usr/local/Cellar/cmake/3.27.7/bin/cmake -E copy /Users/runner/work/ddnet/ddnet/other/icons/DDNet-Server.icns pack_DDNet-17.4-macos_dmg/DDNet-Server.app/Contents/Resources/ && /usr/local/Cellar/cmake/3.27.7/bin/cmake -E copy bundle/server/Info.plist /Users/runner/work/ddnet/ddnet/other/bundle/server/PkgInfo pack_DDNet-17.4-macos_dmg/DDNet-Server.app/Contents/ && /usr/local/Cellar/cmake/3.27.7/bin/cmake -E copy /Users/runner/work/ddnet/ddnet/release/DDNet-Server /Users/runner/work/ddnet/ddnet/release/DDNet-Server-Launcher pack_DDNet-17.4-macos_dmg/DDNet-Server.app/Contents/MacOS/ && /usr/local/Frameworks/Python.framework/Versions/3.12/bin/python3.12 /Users/runner/work/ddnet/ddnet/scripts/darwin_strip_rpath.py /usr/bin/otool /usr/bin/install_name_tool pack_DDNet-17.4-macos_dmg/DDNet-Server.app/Contents/MacOS/DDNet-Server && /usr/local/Cellar/cmake/3.27.7/bin/cmake -E copy pack_DDNet-17.4-macos_dmg/DDNet-Server.app/Contents/MacOS/DDNet-Server pack_DDNet-17.4-macos_dmg/DDNet.app/Contents/MacOS/DDNet-Server && dmgbuild -s /Users/runner/work/ddnet/ddnet/other/dmgsettings.py -D client=pack_DDNet-17.4-macos_dmg/DDNet.app -D server=pack_DDNet-17.4-macos_dmg/DDNet-Server.app -D background=/Users/runner/work/ddnet/ddnet/other/dmgbackground.png DDNet\ 17.4 DDNet-17.4-macos.dmg
Found paths:
	/Users/runner/work/ddnet/ddnet/ddnet-libs/sdl/mac/lib64
	/Users/runner/work/ddnet/ddnet/release
Found paths:
hdiutil: couldn't eject "disk2" - Resource busy
hdiutil: couldn't eject "disk2" - Resource busy
hdiutil: couldn't eject "disk2" - Resource busy
hdiutil: couldn't eject "disk2" - Resource busy
hdiutil: couldn't eject "disk2" - Resource busy
hdiutil: couldn't eject "disk2" - Resource busy
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/Current/bin/dmgbuild", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/dmgbuild/__main__.py", line 48, in main
    build_dmg(
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/dmgbuild/core.py", line 832, in build_dmg
    raise DMGError(callback, "Unable to detach device cleanly")
dmgbuild.core.DMGError: Unable to detach device cleanly
ninja: build stopped: subcommand failed.
Error: Process completed with exit code 1.
```

**Comment by heinrich5991** [comment]
Also e.g.: https://github.com/ddnet/ddnet/actions/runs/7738665112/job/21099957871:
```
Found paths:
	/Users/runner/work/ddnet/ddnet/ddnet-libs/sdl/mac/lib64
	/Users/runner/work/ddnet/ddnet/release
Found paths:
hdiutil: couldn't eject "disk2" - Resource busy
hdiutil: couldn't eject "disk2" - Resource busy
hdiutil: couldn't eject "disk2" - Resource busy
hdiutil: couldn't eject "disk2" - Resource busy
hdiutil: couldn't eject "disk2" - Resource busy
hdiutil: couldn't eject "disk2" - Resource busy
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/Current/bin/dmgbuild", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/dmgbuild/__main__.py", line 48, in main
    build_dmg(
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/dmgbuild/core.py", line 832, in build_dmg
    raise DMGError(callback, "Unable to detach device cleanly")
dmgbuild.core.DMGError: Unable to detach device cleanly
ninja: build stopped: subcommand failed.
Error: Process completed with exit code 1.
```

**Comment by heinrich5991** [comment]
Could probably look into replacing the hdiutil stuff with https://github.com/indygreg/apple-platform-rs/tree/634c7418151da01d3a3cc7081e63d6ea49a67f5e/apple-dmg.

**Comment by Robyt3** [comment]
I haven't seen this CI failure happen anymore since ~2 years, so I assume it's fixed.

@heinrich5991 I would close this issue until further notice unless you want to switch to apple-dmg anyway.
