### ISSUE TITLE
Segfault when starting client on Linux x86-64

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#759]
```
Core was generated by `./DDNet -f mine.cfg'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f6c2f368a10 in raise () from /usr/lib/libc.so.6
[Current thread is 1 (Thread 0x7f6c1f593700 (LWP 12201))]
(gdb) bt
#0  0x00007f6c2f368a10 in raise () from /usr/lib/libc.so.6
#1  0x00007f6c2f36a13a in abort () from /usr/lib/libc.so.6
#2  0x00007f6c2f3a72b0 in __libc_message () from /usr/lib/libc.so.6
#3  0x00007f6c2f3ad90e in malloc_printerr () from /usr/lib/libc.so.6
#4  0x00007f6c2f3aebae in _int_free () from /usr/lib/libc.so.6
#5  0x00000000004a193b in CCommandProcessorFragment_OpenGL::Cmd_Texture_Create(CCommandBuffer::SCommand_Texture_Create const*) ()
#6  0x00000000004a1d81 in CCommandProcessorFragment_OpenGL::RunCommand(CCommandBuffer::SCommand const*) ()
#7  0x00000000004a216b in CCommandProcessor_SDL_OpenGL::RunBuffer(CCommandBuffer*) ()
#8  0x00000000004a0e2e in CGraphicsBackend_Threaded::ThreadFunc(void*) ()
#9  0x00007f6c31aa92e7 in start_thread () from /usr/lib/libpthread.so.0
#10 0x00007f6c2f42154f in clone () from /usr/lib/libc.so.6
```

**Comment by heinrich5991** [comment]
When does this happen? Every time you start the client?

**Comment by def-** [comment]
At client start, with a 0.1% - 1% probability.
