### ISSUE TITLE
DDNet servers lock up on /map

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#7619]
Main thread:
```
#0  futex_wait (private=0, expected=2, futex_word=0x56534c15eab0) at ../sysdeps/nptl/futex-internal.h:146
#1  __GI___lll_lock_wait (futex=futex@entry=0x56534c15eab0, private=0) at ./nptl/lowlevellock.c:49
#2  0x00007fe8a57092d2 in lll_mutex_lock_optimized (mutex=0x56534c15eab0) at ./nptl/pthread_mutex_lock.c:48
#3  ___pthread_mutex_lock (mutex=0x56534c15eab0) at ./nptl/pthread_mutex_lock.c:93
#4  0x000056534a10ce02 in __gthread_mutex_lock (__mutex=0x56534c15eab0) at /usr/include/x86_64-linux-gnu/c++/12/bits/gthr-default.h:749
#5  std::mutex::lock (this=0x56534c15eab0) at /usr/include/c++/12/bits/std_mutex.h:100
#6  CLock::lock (this=0x56534c15eab0) at /home/teeworlds/src/master/src/base/lock.h:94
#7  aio_lock (aio=0x56534c15eab0) at /home/teeworlds/src/master/src/base/system.cpp:652
#8  aio_write (aio=0x56534c15eab0, buffer=0x7ffc174099e0, size=2) at /home/teeworlds/src/master/src/base/system.cpp:713
#9  0x000056534a0cb5b6 in CTeeHistorian::Write (DataSize=<optimized out>, pData=0x7ffc174099e0, this=0x7fe8a4365a10) at /home/teeworlds/src/master/src/game/server/teehistorian.cpp:381
#10 CTeeHistorian::WriteTick (this=0x7fe8a4365a10) at /home/teeworlds/src/master/src/game/server/teehistorian.cpp:404
#11 0x000056534a0cc50d in CTeeHistorian::EnsureTickWritten (this=0x7fe8a4365a10) at /home/teeworlds/src/master/src/game/server/teehistorian.cpp:388
#12 CTeeHistorian::RecordConsoleCommand (this=0x7fe8a4365a10, ClientID=-2, FlagMask=4, pCmd=0x56534a1e0e6f "sv_old_teleport_weapons", pResult=0x7ffc1740aac0)
    at /home/teeworlds/src/master/src/game/server/teehistorian.cpp:577
#13 0x000056534a0e7d7c in CConsole::ExecuteLineStroked (this=this@entry=0x56534c0e4010, Stroke=Stroke@entry=1, pStr=<optimized out>, pStr@entry=0x7ffc17414db0 "sv_old_teleport_weapons 0", 
    ClientID=ClientID@entry=-2, InterpretSemicolons=<optimized out>, InterpretSemicolons@entry=true) at /home/teeworlds/src/master/src/engine/shared/console.cpp:509
#14 0x000056534a0e7dc9 in CConsole::ExecuteLine (this=0x56534c0e4010, pStr=0x7ffc17414db0 "sv_old_teleport_weapons 0", ClientID=-2, InterpretSemicolons=true)
    at /home/teeworlds/src/master/src/engine/shared/console.cpp:589
#15 0x000056534a0e4f93 in SConfigVariable::ExecuteLine (this=0x56534c131430, pLine=0x7ffc17414db0 "sv_old_teleport_weapons 0") at /home/teeworlds/src/master/src/engine/shared/config.cpp:56
#16 SIntConfigVariable::SetValue (this=0x56534c131430, Value=<optimized out>) at /home/teeworlds/src/master/src/engine/shared/config.cpp:149
#17 0x000056534a0cfbd5 in CConfigManager::ResetGameSettings (this=<optimized out>) at /home/teeworlds/src/master/src/engine/shared/config.cpp:444
#18 0x000056534a0a2421 in CGameContext::OnShutdown (this=0x7fe8a4359010, pPersistentData=<optimized out>) at /home/teeworlds/src/master/src/game/server/gamecontext.cpp:3957
#19 0x000056534a076879 in CServer::Run (this=this@entry=0x7fe89f27d010) at /home/teeworlds/src/master/src/engine/server/server.cpp:2851
#20 0x000056534a0601a3 in main (argc=<optimized out>, argv=<optimized out>) at /home/teeworlds/src/master/src/engine/server/main.cpp:193
```

All other threads are just job pool threads/database workers waiting for work.

**Comment by heinrich5991** [comment]
Seems to be caused by #7552, config manager refactoring.

Resetting game settings should ideally not involve the console.

**Comment by def-** [comment]
@Robyt3 can you take a look?
