### ISSUE TITLE
Server segfault on Linux x86-64

### ISSUE THREAD

**Issue by timakro** [ddnet/ddnet#771]
I tested this on two separate Linux Debian 8 x86-64 machines with the server_release and sever_debug build i.e. not the SQL build. It seems to occur when no password is set in the autoexec_server.cfg file. I used the following configuration:

    sv_map "Kobra 4"

When a wrong username and password is entered in the rcon console (I used the newest DDNet Client and entered username "a" and password "a"), the server segfaults. The same happens for the debug build. Although when running with gdb the crash does not happen. Doing a bit of research I found other people with similar problems related to a `pthread_detach` call. They gave advise to check the return value. Funny enough the crash does not occur and it just prints 0 to the console when wrapping the `pthread_detach` call in src/base/system.c in a debug message call.

	dbg_msg("THREAD DETACH", "%d", pthread_detach((pthread_t)(thread)));

[Heisenbug](https://en.wikipedia.org/wiki/Heisenbug) or quantum mechanics? ^^

**Comment by Learath2** [comment]
Couldn't reproduce on either `Gentoo x86-64` nor `Devuan jessie x86-64`. Don't have a Debian installation anywhere but don't think systemd is an issue here (wouldn't be surprised...).

**Comment by def-** [comment]
Nice catch. Compiled with clang using `-fsanitize=address -fno-omit-frame-pointer` and get this when logging in:

```
=================================================================
==17187==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x608000000094 at pc 0x0000004bdde5 bp 0x7ffd0c664af0 sp 0x7ffd0c6642a0
READ of size 8 at 0x608000000094 thread T0
    #0 0x4bdde4  (/media/ddnet/DDNet-Server_d+0x4bdde4)
    #1 0x782e9c  (/media/ddnet/DDNet-Server_d+0x782e9c)
    #2 0x5e890f  (/media/ddnet/DDNet-Server_d+0x5e890f)
    #3 0x5d00fb  (/media/ddnet/DDNet-Server_d+0x5d00fb)
    #4 0x5d38d8  (/media/ddnet/DDNet-Server_d+0x5d38d8)
    #5 0x5d6ba0  (/media/ddnet/DDNet-Server_d+0x5d6ba0)
    #6 0x5e0b62  (/media/ddnet/DDNet-Server_d+0x5e0b62)
    #7 0x7f88257be439  (/usr/lib/libc.so.6+0x20439)
    #8 0x41ece9  (/media/ddnet/DDNet-Server_d+0x41ece9)

0x608000000094 is located 12 bytes to the left of 92-byte region [0x6080000000a0,0x6080000000fc)
allocated by thread T0 here:
    #0 0x50d8c0  (/media/ddnet/DDNet-Server_d+0x50d8c0)
    #1 0x5e962e  (/media/ddnet/DDNet-Server_d+0x5e962e)
    #2 0x5e9562  (/media/ddnet/DDNet-Server_d+0x5e9562)
    #3 0x5e9473  (/media/ddnet/DDNet-Server_d+0x5e9473)
    #4 0x5e9124  (/media/ddnet/DDNet-Server_d+0x5e9124)
    #5 0x5e7a78  (/media/ddnet/DDNet-Server_d+0x5e7a78)
    #6 0x5c4dc4  (/media/ddnet/DDNet-Server_d+0x5c4dc4)
    #7 0x5e0fe9  (/media/ddnet/DDNet-Server_d+0x5e0fe9)
    #8 0x5e0287  (/media/ddnet/DDNet-Server_d+0x5e0287)
    #9 0x7f88257be439  (/usr/lib/libc.so.6+0x20439)

SUMMARY: AddressSanitizer: heap-buffer-overflow (/media/ddnet/DDNet-Server_d+0x4bdde4) 
Shadow bytes around the buggy address:
  0x0c107fff7fc0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c107fff7fd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c107fff7fe0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c107fff7ff0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c107fff8000: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fd fd
=>0x0c107fff8010: fa fa[fa]fa 00 00 00 00 00 00 00 00 00 00 00 04
  0x0c107fff8020: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c107fff8030: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c107fff8040: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c107fff8050: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c107fff8060: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==17187==ABORTING
```

**Comment by def-** [comment]
Next step, inside gdb:
```
(gdb) break __asan::ReportGenericError
(gdb) run
[...]
#0  0x00000000004de160 in __asan::ReportGenericError(unsigned long, unsigned long, unsigned long, unsigned long, bool, unsigned long, unsigned int, bool) ()
#1  0x00000000004bde04 in __asan_memcpy ()
#2  0x0000000000782e9d in md5_append (pms=0x7fffffff9aa0, data=0x608000000094 "\377\377\377\016\\", nbytes=8)
    at src/engine/external/md5/md5.c:343
#3  0x00000000005e8910 in CAuthManager::CheckKey (this=0x7ffff3afe028, Slot=-1, pPw=0x7ffff3692b4e "a")
    at src/engine/server/authmanager.cpp:103
#4  0x00000000005d00fc in CServer::ProcessClientPacket (this=0x7ffff2d69800, pPacket=0x7fffffffd520)
    at src/engine/server/server.cpp:1221
#5  0x00000000005d38d9 in CServer::PumpNetwork (this=0x7ffff2d69800) at src/engine/server/server.cpp:1602
#6  0x00000000005d6ba1 in CServer::Run (this=0x7ffff2d69800) at src/engine/server/server.cpp:1900
#7  0x00000000005e0b63 in main (argc=1, argv=0x7fffffffe4d8) at src/engine/server/server.cpp:2770
```

**Comment by def-** [comment]
I guess I'll have to try out our code with a few sanitizers, finding bugs like that seems easy.
