### ISSUE TITLE
Crash on ddnet 18.1 steam version (Arch Linux KDE Wayland)

### ISSUE THREAD

**Issue by Bamcane** [ddnet/ddnet#8187]
```
2024-04-04 10:57:50 I engine: running on unix-linux-steam-amd64
2024-04-04 10:57:50 I engine: arch is little endian
2024-04-04 10:57:50 I engine: operating system version: Linux 6.8.1-arch1-1 (x86_64, #1 SMP PREEMPT_DYNAMIC Sat, 16 Mar 2024 17:15:35 +0000); "Arch Linux"
2024-04-04 10:57:50 I storage: added path '$USERDIR' ('/home/bamcane/.local/share/ddnet')
2024-04-04 10:57:50 I storage: added path '$DATADIR' ('data')
2024-04-04 10:57:50 I storage: added path '$CURRENTDIR' ('/home/bamcane/.local/share/Steam/steamapps/common/DDraceNetwork/ddnet')
2024-04-04 10:57:50 I discord: error initializing discord instance, error=4
[S_API] SteamAPI_Init(): Loaded '/home/bamcane/.local/share/Steam/linux64/steamclient.so' OK.
```
And the thread is blocking of 
```
#0  0x00007ffff73a90bf in poll () at /usr/lib/libc.so.6
#1  0x00007fffd6ecec5c in ??? () at /home/bamcane/.local/share/Steam/linux64/steamclient.so
#2  0x00007fffd6ecd3f3 in ??? () at /home/bamcane/.local/share/Steam/linux64/steamclient.so
#3  0x00007fffd6ecd7da in ??? () at /home/bamcane/.local/share/Steam/linux64/steamclient.so
#4  0x00007fffd6ebdaed in ??? () at /home/bamcane/.local/share/Steam/linux64/steamclient.so
#5  0x00007fffd6d2839e in ??? () at /home/bamcane/.local/share/Steam/linux64/steamclient.so
#6  0x00007ffff7dfacf6 in SteamAPI_Init ()
    at /home/bamcane/.local/share/Steam/steamapps/common/DDraceNetwork/ddnet/libsteam_api.so
#7  0x000000000051a51b in ??? ()
#8  0x0000000000480ead in ??? ()
#9  0x00007ffff72d3cd0 in ??? () at /usr/lib/libc.so.6
#10 0x00007ffff72d3d8a in __libc_start_main () at /usr/lib/libc.so.6
#11 0x00000000004835aa in ??? ()
```

EDIT: Change the title and new info:
```
[S_API] SteamAPI_Init(): Loaded '/home/bamcane/.local/share/Steam/linux64/steamclient.so' OK.
src/common/pipes.cpp (883) : fatal stalled cross-thread pipe.
src/common/pipes.cpp (883) : fatal stalled cross-thread pipe.
/data/src/common/pipes.cpp 883 fatal stalled cross-thread pipe.
```
```
#0  0x00007fffd6ecda1b in ??? () at /home/bamcane/.local/share/Steam/linux64/steamclient.so
#1  0x00007fffd6ebdaed in ??? () at /home/bamcane/.local/share/Steam/linux64/steamclient.so
#2  0x00007fffd6d2839e in ??? () at /home/bamcane/.local/share/Steam/linux64/steamclient.so
#3  0x00007ffff7dfacf6 in SteamAPI_Init ()
    at /home/bamcane/.local/share/Steam/steamapps/common/DDraceNetwork/ddnet/libsteam_api.so
#4  0x000000000051a51b in ??? ()
#5  0x0000000000480ead in ??? ()
#6  0x00007ffff72d3cd0 in ??? () at /usr/lib/libc.so.6
#7  0x00007ffff72d3d8a in __libc_start_main () at /usr/lib/libc.so.6
#8  0x00000000004835aa in ??? ()

```

**Comment by Bamcane** [comment]
Solved Last Month
