### ISSUE TITLE
RFC: Introduce random map feature on empty servers

### ISSUE THREAD

**Issue by gerdoe-jr** [ddnet/ddnet#8559]
By default server has it's set `sv_map` variable and so newbie player enters the server thinking "oh, sure, I have never played this map, I guess i should try it" in scenario when all empty servers have 3-10 different maps for same region. Mocking empty servers with "Random" map would be a better option because newbie will not know that servers and maps are not tied.

On first player join on empty server, server should behave like if someone called `random_map`

**Comment by def-** [comment]
I thought we could do this without a new command and tried putting `random_map` into a cfg file. It crashes the server:
```
Core was generated by `./DDRace64-Server_sql -f servers/8303.cfg'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055d53dd622c4 in CScore::GameServer (this=<optimized out>) at /home/teeworlds/src/master/src/game/server/score.h:19
19		CGameContext *GameServer() const { return m_pGameServer; }
[Current thread is 1 (Thread 0x7fafd6bf0ec0 (LWP 18321))]
(gdb) bt
#0  0x000055d53dd622c4 in CScore::GameServer (this=<optimized out>) at /home/teeworlds/src/master/src/game/server/score.h:19
#1  CScore::RandomMap (this=0x0, ClientId=0, Stars=-1) at /home/teeworlds/src/master/src/game/server/score.cpp:261
#2  0x000055d53dd9a525 in CConsole::ExecuteLineStroked (this=this@entry=0x55d53ff62b80, Stroke=Stroke@entry=1, pStr=<optimized out>, pStr@entry=0x55d53ff3c04a "random_map", ClientId=ClientId@entry=-1,
    InterpretSemicolons=<optimized out>, InterpretSemicolons@entry=true) at /home/teeworlds/src/master/src/engine/shared/console.cpp:528
#3  0x000055d53dd9aa19 in CConsole::ExecuteLine (InterpretSemicolons=true, ClientId=-1, pStr=0x55d53ff3c04a "random_map", this=0x55d53ff62b80) at /home/teeworlds/src/master/src/engine/shared/console.cpp:595
#4  CConsole::ExecuteFile (this=this@entry=0x55d53ff62b80, pFilename=pFilename@entry=0x7ffc83719b5a "servers/8303.cfg", ClientId=ClientId@entry=-1, LogFailure=LogFailure@entry=true,
    StorageType=StorageType@entry=-2) at /home/teeworlds/src/master/src/engine/shared/console.cpp:635
#5  0x000055d53dd9ad67 in CConsole::ExecuteFile (StorageType=-2, LogFailure=true, ClientId=-1, pFilename=0x7ffc83719b5a "servers/8303.cfg", this=0x55d53ff62b80)
    at /home/teeworlds/src/master/src/engine/shared/console.cpp:817
#6  CConsole::ParseArguments (this=0x55d53ff62b80, NumArgs=2, ppArguments=0x7ffc837189c0) at /home/teeworlds/src/master/src/engine/shared/console.cpp:816
#7  0x000055d53dd0f5f1 in main (argc=<optimized out>, argv=<optimized out>) at /home/teeworlds/src/master/src/engine/server/main.cpp:168
```

**Comment by ChillerDragon** [comment]
I can already see how this delays the realization that votes exist xd. There will be people with 300 points switching server after every finish haha. And there will be more people on discord asking "can we get a server with map xy?" xxxD

**Comment by def-** [comment]
Done
