### ISSUE TITLE
Crash in AntibotOnHookAttach

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#8587]
```
Core was generated by `./DDRace64-Server_sql -f servers/8321.cfg'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f199e046a62 in ?? () from /home/teeworlds/servers/libantibot.so
[Current thread is 1 (Thread 0x7f199c9ceec0 (LWP 2485944))]
(gdb) bt
#0  0x00007f199e046a62 in ?? () from /home/teeworlds/servers/libantibot.so
#1  0x00007f199e049c4e in AntibotOnHookAttach () from /home/teeworlds/servers/libantibot.so
#2  0x0000556ef2a735cb in CCharacter::Tick (this=0x556ef2cbab68 <gs_PoolDataCCharacter+172040>)
    at /home/teeworlds/src/master/src/game/server/entities/character.cpp:790
#3  CCharacter::Tick (this=0x556ef2cbab68 <gs_PoolDataCCharacter+172040>)
    at /home/teeworlds/src/master/src/game/server/entities/character.cpp:761
#4  0x0000556ef2a935e2 in CGameWorld::Tick (this=this@entry=0x7f199c186120)
    at /home/teeworlds/src/master/src/game/server/gameworld.cpp:237
#5  0x0000556ef2a8ca12 in CGameContext::OnTick (this=0x7f199c175010)
    at /home/teeworlds/src/master/src/game/server/gamecontext.cpp:1016
#6  0x0000556ef2a5d354 in CServer::Run (this=this@entry=0x7f199724c010)
    at /home/teeworlds/src/master/src/engine/server/server.cpp:2949
#7  0x0000556ef2a4686b in main (argc=<optimized out>, argv=<optimized out>)
    at /home/teeworlds/src/master/src/engine/server/main.cpp:197
```
This is happening a bunch of times. @Learath2 Could it be related to the way we pass IPs now?

**Comment by Learath2** [comment]
Mh, unlikely. Do we have any logs?

**Comment by def-** [comment]
CC @nobody-mb 
Last logs:
```
2024-07-14 12:44:43 I net_ban: banned 'X' (Blocking is forbidden. Until Jul 14 11:42 UTC)
2024-07-14 12:44:44 I chat: 50:-2:(1)whyskylend: 23
2024-07-14 12:44:44 I antibot: 53: кыс-кыс 54 possible hookbot (2 18)
2024-07-14 12:44:46 I chat: *** 'watafaj' has left the game
2024-07-14 12:44:46 I game: leave player='42:watafaj'
2024-07-14 12:44:47 I chat: 35:-2:xsailent: ИФАЫШГТФЫГТАГФТЩАТЗЩГФША
2024-07-14 12:44:48 I antibot: 18: koptilka 1 possible eyefollow (21 18)
2024-07-14 12:44:50 I antibot: 23: known_bot
```

**Comment by Learath2** [comment]
Actually with those logs maybe possible, are the rest of the logs available?

**Comment by def-** [comment]
rus.ddnet.org:servers/servers/8321.log

**Comment by def-** [comment]
```
(gdb) print m_pPlayer->m_ClientId
$3 = 23
(gdb) print *m_pPlayer
$2 = {m_ViewPos = {{x = 5843, u = 5843}, {y = 5041, v = 5041}}, m_TuneZone = 0, m_TuneZoneOld = 0,
  m_PlayerFlags = 17, m_aCurLatency = {0 <repeats 23 times>, 112, 0 <repeats 40 times>},
  m_SentSnaps = 10681, m_SpectatorId = -1, m_IsReady = true, m_Vote = -1, m_VotePos = 2,
  m_LastVoteCall = 0, m_LastVoteTry = 1818542, m_LastChat = 1822984, m_LastSetTeam = 0,
  m_LastSetSpectatorMode = 0, m_LastChangeInfo = 1803466, m_LastEmote = 1823680,
  m_LastEmoteGlobal = 1823680, m_LastKill = 1821993, m_aLastCommands = {0, 0, 0, 0},
  m_LastCommandPos = 0, m_LastWhisperTo = -1, m_LastInvited = 0, m_SendVoteIndex = 345, m_TeeInfos = {
    static ms_DarkestLGT7 = 0.239215687, m_aSkinName = "zombie1", '\000' <repeats 16 times>,
    m_UseCustomColor = 1, m_ColorBody = 65288, m_ColorFeet = 16056064, m_apSkinPartNames = {
      "standard", '\000' <repeats 15 times>, '\000' <repeats 23 times>, '\000' <repeats 23 times>,
      "standard", '\000' <repeats 15 times>, "standard", '\000' <repeats 15 times>,
      "standard", '\000' <repeats 15 times>}, m_aUseCustomColors = {true, true, true, true, true,
      false}, m_aSkinPartColors = {65373, 587202559, 65373, 65373, 16056151, 0}}, m_DieTick = 1821993,
  m_PreviousDieTick = 1815105, m_Score = std::optional<int> [no contained value], m_JoinTick = 1803447,
  m_ForceBalanced = false, m_LastActionTick = 1824861, m_TeamChangeTick = 1803447, m_Latency = {
    m_Accum = 1267, m_AccumMin = 105, m_AccumMax = 127, m_Avg = 119, m_Min = 105, m_Max = 145},
  m_UniqueClientId = 761, m_pCharacter = 0x556ef2cbab68 <gs_PoolDataCCharacter+172040>,
  m_NumInputs = 20619, m_pGameServer = 0x7f199c175010, m_Spawning = false, m_WeakHookSpawn = false,
  m_ClientId = 23, m_Team = 0, m_Paused = 0, m_ForcePauseTime = 0, m_LastPause = 0, m_Afk = false,
  m_DefEmote = 0, m_OverrideEmote = 0, m_OverrideEmoteReset = -1, m_Halloween = false, m_DND = false,
  m_FirstVoteTick = 1804947, m_aTimeoutCode = '\000' <repeats 63 times>, m_Last_KickVote = 0,
  m_Last_Team = 0, m_ShowOthers = 0, m_ShowAll = false, m_ShowDistance = {{x = 1429, u = 1429}, {
      y = 804, v = 804}}, m_SpecTeam = false, m_NinjaJetpack = false, m_ChatScore = 0,
  m_Moderating = false, m_LastPlaytime = 37153978389009, m_LastEyeEmote = 0, m_LastBroadcast = 0,
  m_LastBroadcastImportance = false, m_pLastTarget = 0x556ef48ede30, m_LastTargetInit = true,
  m_EyeEmoteEnabled = true, m_TimerType = 0, m_FirstPacket = true, m_LastSqlQuery = 0,
  m_ScoreQueryResult = std::shared_ptr<CScorePlayerResult> (empty) = {get() = 0x0},
  m_ScoreFinishResult = std::shared_ptr<CScorePlayerResult> (empty) = {get() = 0x0},
  m_NotEligibleForFinish = false, m_EligibleForFinishCheck = 36726277218332, m_VotedForPractice = false,
  m_SwapTargetsClientId = -1, m_BirthdayAnnounced = false, m_RescueMode = 0, m_LastTeleTee = {
    m_ClientId = 0, m_aString = '\000' <repeats 2047 times>, m_aName = '\000' <repeats 15 times>,
    m_Alive = 0, m_Paused = 0, m_NeededFaketuning = 0, m_TeeStarted = 0, m_TeeFinished = 0,
    m_IsSolo = 0, m_aWeapons = {{m_AmmoRegenStart = 0, m_Ammo = 0, m_Ammocost = 0, m_Got = 0}, {
        m_AmmoRegenStart = 0, m_Ammo = 0, m_Ammocost = 0, m_Got = 0}, {m_AmmoRegenStart = 0, m_Ammo = 0,
        m_Ammocost = 0, m_Got = 0}, {m_AmmoRegenStart = 0, m_Ammo = 0, m_Ammocost = 0, m_Got = 0}, {
        m_AmmoRegenStart = 0, m_Ammo = 0, m_Ammocost = 0, m_Got = 0}, {m_AmmoRegenStart = 0, m_Ammo = 0,
        m_Ammocost = 0, m_Got = 0}}, m_Ninja = {m_ActivationDir = {{x = 0, u = 0}, {y = 0, v = 0}},
      m_ActivationTick = 0, m_CurrentMoveTime = 0, m_OldVelAmount = 0}, m_LastWeapon = 0,
    m_QueuedWeapon = 0, m_EndlessJump = 0, m_Jetpack = 0, m_NinjaJetpack = 0, m_FreezeTime = 0,
    m_FreezeStart = 0, m_DeepFrozen = 0, m_LiveFrozen = 0, m_EndlessHook = 0, m_DDRaceState = 0,
    m_HitDisabledFlags = 0, m_CollisionEnabled = 0, m_TuneZone = 0, m_TuneZoneOld = 0,
    m_HookHitEnabled = 0, m_Time = 0, m_Pos = {{x = 0, u = 0}, {y = 0, v = 0}}, m_PrevPos = {{x = 0,
        u = 0}, {y = 0, v = 0}}, m_TeleCheckpoint = 0, m_LastPenalty = 0, m_TimeCpBroadcastEndTime = 0,
    m_LastTimeCp = 0, m_LastTimeCpBroadcasted = 0, m_aCurrentTimeCp = {0 <repeats 25 times>},
    m_NotEligibleForFinish = 0, m_HasTelegunGun = 0, m_HasTelegunGrenade = 0, m_HasTelegunLaser = 0,
    m_CorePos = {{x = 0, u = 0}, {y = 0, v = 0}}, m_Vel = {{x = 0, u = 0}, {y = 0, v = 0}},
    m_ActiveWeapon = 0, m_Jumped = 0, m_JumpedTotal = 0, m_Jumps = 0, m_HookPos = {{x = 0, u = 0}, {
        y = 0, v = 0}}, m_HookDir = {{x = 0, u = 0}, {y = 0, v = 0}}, m_HookTeleBase = {{x = 0, u = 0}, {
        y = 0, v = 0}}, m_HookTick = 0, m_HookState = 0, m_HookedPlayer = 0, m_NewHook = 0,
    m_InputDirection = 0, m_InputJump = 0, m_InputFire = 0, m_InputHook = 0, m_ReloadTimer = 0,
    m_aGameUuid = '\000' <repeats 36 times>}}
```

**Comment by Learath2** [comment]
Somehow ended up with an empty address in the antibot, which is then assumed to not be empty. I'll keep digging around but that is the issue indeed
