### ISSUE TITLE
Crash when quitting from the editor

### ISSUE THREAD

**Issue by Henningstone** [ddnet/ddnet#881]
Opened the editor, loaded a map (dunno if that's necessary), did CTRL+SHIFT+Q.
Always reproducable.

```
Thread 1 "DDNet" received signal SIGSEGV, Segmentation fault.
0x0000000000524391 in CEditorImage::~CEditorImage (this=0xd3ea90, __in_chrg=<optimized out>) at src/game/editor/editor.cpp:63
63              m_pEditor->Graphics()->UnloadTexture(m_TexID);
(gdb) bt
#0  0x0000000000524391 in CEditorImage::~CEditorImage (this=0x11f3110, __in_chrg=<optimized out>) at src/game/editor/editor.cpp:63
#1  0x0000000000547a6d in array<CEditorImage*, allocator_default<CEditorImage*> >::delete_all (this=0xa6ead8) at src/base/tl/array.h:70
#2  0x0000000000542a5f in CEditorMap::Clean (this=0xa6eab8) at src/game/editor/editor.cpp:5445
#3  0x0000000000544cc5 in CEditorMap::~CEditorMap (this=0xa6eab8, __in_chrg=<optimized out>) at src/game/editor/editor.h:348
#4  0x000000000054ae1b in CEditor::~CEditor (this=0xa6daf0, __in_chrg=<optimized out>) at src/game/editor/editor.h:607
#5  0x000000000054aed3 in CEditor::~CEditor (this=0xa6daf0, __in_chrg=<optimized out>) at src/game/editor/editor.h:607
#6  0x0000000000593123 in CKernel::~CKernel (this=0xa385a0, __in_chrg=<optimized out>) at src/engine/shared/kernel.cpp:55
#7  0x00000000005931b1 in CKernel::~CKernel (this=0xa385a0, __in_chrg=<optimized out>) at src/engine/shared/kernel.cpp:59
#8  0x0000000000471316 in main (argc=1, argv=0x7fffffffdc78) at src/engine/client/client.cpp:3577
```

**Comment by heinrich5991** [comment]
Sounds like #848. @def-?

**Comment by Henningstone** [comment]
Updated the backtrace, I accidentally debugged a release build before. Now it should be a little more useful...
